export type SourceType = "currículo" | "libro" | "curso" | "videos" | "repositorio" | "documentación"

export type ProgrammingSourceV50 = {
  id: string
  title: string
  author: string
  type: SourceType
  url: string
  note: string
  license: string
}

export type ConceptV50 = {
  id: string
  title: string
  what: string
  why: string
  when: string
  whenNot: string
  mentalModel: string
  how: string[]
  terms: { term: string; meaning: string }[]
  exampleLanguage: "python" | "javascript" | "text"
  example: string
  breakdown: string[]
  guidedTask: string[]
  soloTask: string
  mistakes: string[]
  debug: string[]
  check: { q: string; a: string }[]
  mastery: string
}

export type GuidedLevelV50 = {
  code: string
  title: string
  phase: string
  orientation: string
  prerequisites: string[]
  outcomes: string[]
  concepts: ConceptV50[]
  project: string
  gate: string
  sources: string[]
}

export const programmingSourcesV50: ProgrammingSourceV50[] = [
  { id: "cs2023", title: "Computer Science Curricula 2023", author: "ACM / IEEE-CS / AAAI", type: "currículo", url: "https://csed.acm.org/", note: "Cobertura curricular de fundamentos de desarrollo, algoritmos, lenguajes, sistemas, seguridad, paralelismo y otras áreas de computación.", license: "Consulta oficial; usar como marco de cobertura." },
  { id: "swebok", title: "Software Engineering Body of Knowledge", author: "IEEE Computer Society", type: "currículo", url: "https://www.computer.org/education/bodies-of-knowledge/software-engineering", note: "Marco de requisitos, diseño, construcción, pruebas, mantenimiento, configuración, calidad y práctica profesional.", license: "Consulta oficial; no copiar contenido protegido." },
  { id: "cs50", title: "CS50x", author: "Harvard University", type: "curso", url: "https://cs50.harvard.edu/x/", note: "Introducción amplia con Scratch, C, memoria, estructuras, Python, SQL y web; incluye problemas y proyecto final.", license: "OpenCourseWare; respetar licencia y atribución." },
  { id: "stanford106", title: "CS106A Programming Methodology", author: "Stanford University", type: "curso", url: "https://see.stanford.edu/Course/CS106A", note: "Introducción a programación y principios de ingeniería: descomposición, abstracción, encapsulación, estilo y pruebas.", license: "Material educativo de Stanford; enlazar, no redistribuir sin permiso." },
  { id: "cs61a", title: "CS61A Structure and Interpretation of Computer Programs", author: "UC Berkeley", type: "curso", url: "https://cs61a.org/", note: "Abstracción, composición, recursión, datos, lenguajes e intérpretes; laboratorios y proyectos.", license: "Consultar términos del curso; enlazar recursos oficiales." },
  { id: "mit6031", title: "Software Construction", author: "MIT", type: "curso", url: "https://web.mit.edu/6.031/www/sp21/", note: "Tipos, pruebas, revisiones, especificaciones, ADTs, abstracción, concurrencia, networking y pequeños lenguajes.", license: "Material educativo MIT; enlazar y redactar contenido propio." },
  { id: "htdp", title: "How to Design Programs", author: "Felleisen, Findler, Flatt, Krishnamurthi", type: "libro", url: "https://htdp.org/", note: "Método sistemático de diseño de programas, definición de datos, funciones, pruebas y ejercicios graduados.", license: "CC BY-NC-ND en la edición web actual; no adaptar/copiar dentro del producto." },
  { id: "sicp", title: "Structure and Interpretation of Computer Programs", author: "Abelson, Sussman et al.", type: "libro", url: "https://mitpress.mit.edu/9780262367622/structure-and-interpretation-of-computer-programs/", note: "Modelos mentales de computación, abstracción, estado, funciones de orden superior, concurrencia y lenguajes.", license: "Existe edición open access; respetar licencia específica." },
  { id: "ods", title: "Open Data Structures", author: "Pat Morin", type: "libro", url: "https://opendatastructures.org/", note: "Implementación y análisis de listas, colas, diccionarios, árboles, heaps, ordenamientos y grafos con código fuente abierto.", license: "CC BY; reutilizable con atribución." },
  { id: "ostep", title: "Operating Systems: Three Easy Pieces", author: "Remzi & Andrea Arpaci-Dusseau", type: "libro", url: "https://pages.cs.wisc.edu/~remzi/OSTEP/", note: "Virtualización, concurrencia y persistencia con capítulos, tareas, simuladores y proyectos.", license: "Libro gratuito en línea; revisar licencia del capítulo antes de redistribuir." },
  { id: "nand2tetris", title: "Nand to Tetris", author: "Noam Nisan & Shimon Schocken", type: "curso", url: "https://www.nand2tetris.org/", note: "Doce proyectos para construir hardware, VM, ensamblador, compilador y sistema operativo desde primeros principios.", license: "Material gratuito para aprendizaje; no publicar soluciones." },
  { id: "missing", title: "The Missing Semester of Your CS Education", author: "MIT", type: "videos", url: "https://missing.csail.mit.edu/", note: "Shell, herramientas, debugging, profiling, Git, packaging, calidad y prácticas de trabajo reales.", license: "Material educativo público; enlazar notas y videos oficiales." },
  { id: "crafting", title: "Crafting Interpreters", author: "Robert Nystrom", type: "libro", url: "https://craftinginterpreters.com/", note: "Construcción paso a paso de dos intérpretes completos: scanner, parser, AST, resolución, bytecode, VM y GC.", license: "Texto accesible en web; no copiar extensamente sin permiso." },
  { id: "rustbook", title: "The Rust Programming Language", author: "Rust Project", type: "documentación", url: "https://doc.rust-lang.org/book/", note: "Guía oficial de Rust: ownership, tipos, errores, testing, concurrencia, traits, macros y unsafe.", license: "Documentación oficial; respetar licencias del proyecto Rust." },
  { id: "ossu", title: "OSSU Computer Science", author: "Open Source Society University", type: "repositorio", url: "https://github.com/ossu/computer-science", note: "Ruta autodidacta completa y estructurada de ciencias de la computación basada en cursos universitarios.", license: "Repositorios/enlaces con licencias diversas; usar como mapa y enlazar." },
  { id: "fcc", title: "freeCodeCamp", author: "freeCodeCamp", type: "repositorio", url: "https://github.com/freeCodeCamp/freeCodeCamp", note: "Currículo abierto con miles de retos de programación, web, JavaScript, Python, bases de datos y proyectos.", license: "BSD-3-Clause para código; revisar licencias del contenido específico." },
  { id: "odin", title: "The Odin Project Curriculum", author: "The Odin Project", type: "repositorio", url: "https://github.com/TheOdinProject/curriculum", note: "Currículo full-stack organizado en lecciones y proyectos; útil para diseño de práctica por proyecto.", license: "CC BY-NC-SA para currículo; enlazar, no integrar en producto comercial sin cumplir licencia." },
  { id: "fso", title: "Full Stack Open", author: "University of Helsinki", type: "curso", url: "https://fullstackopen.com/es/", note: "React, Node.js, testing, TypeScript, GraphQL, CI/CD, contenedores y bases de datos; disponible en español.", license: "CC BY-NC-SA; enlazar y usar como referencia." },
  { id: "exercism", title: "Exercism", author: "Exercism", type: "repositorio", url: "https://exercism.org/", note: "Práctica y mentoría en decenas de lenguajes, con ejercicios conceptuales y feedback.", license: "Código y contenido con licencias por repositorio; enlazar a tracks oficiales." },
  { id: "buildx", title: "Build Your Own X", author: "CodeCrafters community", type: "repositorio", url: "https://github.com/codecrafters-io/build-your-own-x", note: "Colección de guías para recrear bases de datos, Git, Docker, motores, lenguajes, redes, sistemas y otros proyectos desde cero.", license: "Índice de enlaces; cada tutorial posee su propia licencia." },
]

const C = (
  id: string,
  title: string,
  what: string,
  why: string,
  when: string,
  mentalModel: string,
  exampleLanguage: "python" | "javascript" | "text",
  example: string,
  breakdown: string[],
  mastery: string,
  terms: { term: string; meaning: string }[] = [],
  whenNot = "No lo uses por costumbre: primero confirma que el problema realmente necesita este concepto.",
): ConceptV50 => ({
  id,
  title,
  what,
  why,
  when,
  whenNot,
  mentalModel,
  how: [
    `1. Identifica qué problema resuelve ${title.toLowerCase()}.`,
    "2. Escribe un ejemplo pequeño con entrada y salida concretas.",
    "3. Predice el resultado antes de ejecutar.",
    "4. Ejecuta y compara el resultado real con tu predicción.",
    "5. Cambia una sola cosa y vuelve a observar qué efecto produce.",
    "6. Explica con tus propias palabras por qué funcionó.",
  ],
  terms,
  exampleLanguage,
  example,
  breakdown,
  guidedTask: [
    "Lee el ejemplo sin ejecutarlo y predice la salida.",
    "Señala qué parte representa datos, qué parte representa una decisión/operación y qué parte produce un resultado.",
    "Ejecuta el ejemplo.",
    "Modifica un valor y vuelve a predecir antes de ejecutar.",
    "Describe qué cambió y cuál fue la causa exacta.",
  ],
  soloTask: `Crea un ejemplo nuevo de ${title.toLowerCase()} sin copiar el ejemplo anterior. Debe tener al menos un caso normal y un caso límite.`,
  mistakes: [
    "Memorizar sintaxis sin comprender qué estado o dato está cambiando.",
    "Cambiar muchas líneas a la vez y luego no saber cuál cambio produjo el resultado.",
    "Dar por correcto un programa porque funciona con un solo ejemplo.",
  ],
  debug: [
    "Reproduce el fallo con el caso más pequeño posible.",
    "Compara estado esperado y estado real en cada paso.",
    "Localiza la primera línea donde ambos divergen.",
    "Corrige una sola causa, vuelve a ejecutar y agrega un test que evite la regresión.",
  ],
  check: [
    { q: `¿Qué problema resuelve ${title}?`, a: why },
    { q: `¿Cuándo usarías ${title}?`, a: when },
    { q: "¿Cómo comprobarías que tu solución es correcta?", a: "Con predicción, casos normales, casos límite, ejecución y una explicación de por qué el resultado satisface el objetivo." },
  ],
  mastery,
})

const concepts: Record<string, ConceptV50> = {
  secuencias: C("secuencias", "Secuencias", "Una secuencia es una lista ordenada de instrucciones que se ejecutan una después de otra.", "Permite expresar procedimientos deterministas: primero A, después B, después C.", "Úsala cuando el orden de las acciones cambia el resultado.", "Piensa en una receta: cada paso deja el sistema en un estado que recibe el siguiente paso.", "python", `nombre = "Ada"\nprint("Hola", nombre)\nprint("Fin")`, ["Línea 1 guarda un dato.", "Línea 2 usa ese dato para producir una salida.", "Línea 3 se ejecuta después porque está más abajo."], "Puedes predecir y explicar el estado después de cada instrucción.", [{term:"instrucción",meaning:"Una orden concreta que el lenguaje puede ejecutar."},{term:"estado",meaning:"Los valores que existen en un momento del programa."}]),
  variables: C("variables", "Variables", "Una variable es un nombre que referencia un valor que el programa necesita recordar.", "Hace posible trabajar con datos que cambian o que todavía no conoces al escribir el programa.", "Úsala para entradas, resultados intermedios, contadores, configuraciones y cualquier dato que deba reutilizarse.", "Piensa en una etiqueta pegada a un valor. El nombre ayuda a recordar qué representa.", "python", `precio = 25\ncantidad = 3\ntotal = precio * cantidad\nprint(total)`, ["precio representa el valor unitario.", "cantidad representa cuántas unidades hay.", "total se deriva de precio × cantidad.", "print muestra el valor calculado."], "Puedes elegir nombres claros, distinguir dato base de dato derivado y predecir cómo cambia el resultado."),
  booleanos: C("booleanos", "Booleanos", "Un booleano representa una condición con solo dos posibilidades: verdadero o falso.", "Permite que el programa tome decisiones basadas en hechos verificables.", "Úsalo en validaciones, permisos, reglas, filtros y condiciones de control.", "Es una pregunta cerrada: ¿se cumple esta condición? Sí o no.", "python", `edad = 20\npuede_entrar = edad >= 18\nprint(puede_entrar)`, ["edad es un dato.", ">= compara edad con 18.", "El resultado de la comparación es True o False.", "Ese booleano puede alimentar un if."], "Puedes formular condiciones claras y explicar cuándo son verdaderas o falsas."),
  diagramas: C("diagramas", "Diagramas de flujo", "Un diagrama representa visualmente decisiones, secuencias y repeticiones antes de escribir sintaxis.", "Ayuda a separar la lógica del problema del lenguaje de programación.", "Úsalo cuando una lógica tiene varias ramas o cuesta explicarla solo con texto.", "Cada bloque representa una acción; cada rombo, una pregunta; cada flecha, el siguiente paso.", "text", `INICIO → leer edad → ¿edad >= 18? → sí: permitir | no: rechazar → FIN`, ["INICIO marca el punto de entrada.", "leer edad obtiene un dato.", "la pregunta divide el flujo.", "cada rama produce una acción diferente."], "Puedes dibujar el flujo de un problema y convertirlo después a código."),
  trazas: C("trazas", "Trazas manuales", "Trazar es simular el programa paso a paso anotando cómo cambia el estado.", "Permite comprender y depurar sin adivinar.", "Úsala con bucles, recursión, condiciones y cualquier código cuyo resultado no sea obvio.", "Construye una tabla con número de paso y valores de las variables.", "python", `total = 0\nfor n in [2, 4, 6]:\n    total += n\nprint(total)`, ["total empieza en 0.", "iteración 1: total=2.", "iteración 2: total=6.", "iteración 3: total=12."], "Puedes completar una tabla de estados sin ejecutar el programa."),
  errores: C("errores", "Errores", "Un error es una diferencia entre el comportamiento esperado y el comportamiento real; puede ser de sintaxis, ejecución o lógica.", "Aprender a clasificar errores evita corregir al azar.", "Úsalo como marco cada vez que algo falle: primero identifica el tipo de fallo.", "Sintaxis: el programa no se puede leer; runtime: falla al ejecutar; lógica: ejecuta pero hace lo incorrecto.", "python", `numeros = [10, 20]\n# print(numeros[2])  # IndexError\nprint(sum(numeros))`, ["La lista tiene índices 0 y 1.", "Pedir índice 2 sería un error de ejecución.", "sum usa los dos valores existentes."], "Puedes clasificar un fallo y localizar la primera causa en lugar de cambiar código al azar."),

  tipos: C("tipos", "Tipos de datos", "Un tipo describe qué clase de valor es un dato y qué operaciones tienen sentido sobre él.", "Evita mezclar conceptos incompatibles y ayuda a razonar sobre operaciones válidas.", "Úsalo cada vez que modeles datos: números, texto, booleanos, colecciones u objetos.", "El tipo es el conjunto de valores posibles más las operaciones permitidas.", "python", `edad = 20\nnombre = "Ada"\nactivo = True\nprint(type(edad), type(nombre), type(activo))`, ["20 es entero.", "Ada es texto.", "True es booleano.", "type permite inspeccionar el tipo en Python."], "Puedes escoger el tipo adecuado y explicar qué operaciones son válidas."),
  if: C("if", "Condicionales if/else", "Una condición elige qué bloque ejecutar según un booleano.", "Permite que el mismo programa responda distinto ante datos distintos.", "Úsalo cuando el comportamiento dependa de una regla o condición.", "Una puerta: evalúa una pregunta y deja pasar por una rama.", "python", `saldo = 80\nif saldo >= 50:\n    print("Compra permitida")\nelse:\n    print("Saldo insuficiente")`, ["saldo es el dato.", "saldo >= 50 produce True/False.", "if ejecuta una rama si es True.", "else cubre el caso contrario."], "Puedes diseñar ramas completas y detectar casos que no quedaron cubiertos."),
  "for/while": C("loops", "Bucles for/while", "Un bucle repite un bloque controladamente.", "Evita duplicar instrucciones y permite procesar colecciones o repetir hasta cumplir una condición.", "Usa for cuando recorres elementos o un rango conocido; while cuando repites hasta que cambie una condición.", "for = por cada elemento; while = mientras siga siendo cierto.", "python", `total = 0\nfor n in [3, 5, 7]:\n    total += n\nprint(total)`, ["total acumula el resultado.", "for asigna cada elemento a n.", "+= actualiza el acumulador.", "al terminar se imprime 15."], "Puedes decidir entre for y while y demostrar por qué el bucle termina."),
  funciones: C("funciones", "Funciones", "Una función agrupa una operación con nombre, entradas y un resultado o efecto.", "Reduce repetición, permite probar partes pequeñas y crea abstracciones reutilizables.", "Úsala cuando una tarea tenga significado propio o se repita.", "Una mini máquina: recibe argumentos, trabaja y devuelve un resultado.", "python", `def area_rectangulo(ancho, alto):\n    return ancho * alto\n\nprint(area_rectangulo(4, 3))`, ["def crea la función.", "ancho y alto son parámetros.", "return entrega el resultado al llamador.", "la llamada usa argumentos 4 y 3."], "Puedes diseñar funciones pequeñas con responsabilidades y contratos claros."),
  listas: C("listas", "Listas", "Una lista es una colección ordenada de valores accesibles por posición.", "Permite manejar una cantidad variable de datos como un conjunto secuencial.", "Úsala cuando el orden importe y quieras recorrer, agregar o quitar elementos.", "Una fila numerada: cada elemento tiene una posición.", "python", `notas = [15, 18, 12]\nnotas.append(20)\nprint(notas[0], len(notas))`, ["[] crea una lista.", "append agrega al final.", "índice 0 accede al primer elemento.", "len devuelve cantidad de elementos."], "Puedes recorrer, modificar y explicar el coste básico de operaciones sobre listas."),
  diccionarios: C("diccionarios", "Diccionarios", "Un diccionario asocia claves con valores.", "Permite buscar datos por identidad o nombre en vez de posición.", "Úsalo para registros, índices, configuraciones y conteos por clave.", "Como una agenda: buscas por nombre y obtienes el dato asociado.", "python", `usuario = {"nombre": "Ada", "edad": 20}\nusuario["activo"] = True\nprint(usuario["nombre"])`, ["cada entrada es clave→valor.", "la clave nombre recupera Ada.", "se puede agregar una nueva clave activo."], "Puedes modelar entidades simples y elegir claves estables y descriptivas."),

  debug: C("debug", "Depuración", "Depurar es localizar la causa de un comportamiento incorrecto mediante evidencia.", "Reduce tiempo perdido y convierte fallos en información.", "Úsalo ante cualquier diferencia entre esperado y real.", "No preguntes '¿qué cambio?'; pregunta '¿dónde aparece por primera vez la diferencia?'.", "python", `datos = [1, 2, 3]\nresultado = 0\nfor x in datos:\n    resultado += x\n    print("DEBUG", x, resultado)`, ["la salida intermedia muestra el estado tras cada iteración.", "si aparece una divergencia, sabes en qué paso comenzó."], "Puedes aislar un bug con caso mínimo, inspección de estado y prueba de regresión."),
  tests: C("tests", "Pruebas", "Una prueba ejecuta el programa con una entrada y comprueba automáticamente una propiedad o salida esperada.", "Da confianza al cambiar código y documenta qué comportamiento se considera correcto.", "Úsalas desde funciones pequeñas hasta sistemas completos.", "Cada test es una hipótesis ejecutable: dada esta entrada, espero esta salida.", "python", `def doble(n): return n * 2\nassert doble(3) == 6\nassert doble(0) == 0`, ["se define una función.", "assert falla si la condición es falsa.", "los dos casos verifican comportamiento distinto."], "Puedes escribir casos normales, límite y de error antes de refactorizar."),
  "edge cases": C("edge", "Casos límite", "Un caso límite está en el borde del dominio: vacío, cero, máximo, mínimo o combinaciones poco comunes.", "Muchos bugs aparecen fuera del caso típico.", "Úsalo al diseñar pruebas y especificaciones.", "Imagina los extremos del conjunto de entradas, no solo el ejemplo feliz.", "python", `def primero(xs):\n    return xs[0] if xs else None\n\nprint(primero([]))`, ["xs vacío es un borde.", "if xs evita acceder a índice inexistente.", "None representa ausencia de resultado."], "Puedes enumerar bordes importantes antes de ejecutar y decidir cómo debe responder el sistema."),
  recursión: C("recursion", "Recursión", "Una función recursiva resuelve un problema llamándose con una versión más pequeña del mismo problema.", "Expresa naturalmente estructuras recursivas como árboles y divide problemas por reducción.", "Úsala cuando el problema tenga estructura autosimilar y puedas definir un caso base claro.", "Cada llamada baja un escalón hasta el caso base y luego devuelve resultados hacia arriba.", "python", `def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nprint(factorial(5))`, ["n<=1 es el caso base.", "n-1 hace el problema más pequeño.", "cada retorno multiplica al regresar."], "Puedes demostrar terminación y dibujar la pila de llamadas."),
  "complejidad inicial": C("complexity", "Complejidad inicial", "La complejidad estima cómo crece el trabajo o memoria al crecer la entrada.", "Permite comparar soluciones más allá de 'funciona en mi ejemplo'.", "Úsala al elegir algoritmos y estructuras, especialmente con entradas grandes.", "Pregunta: si duplico los datos, ¿el trabajo crece igual, el doble, cuatro veces o mucho más?", "text", `O(1) constante\nO(log n) logarítmico\nO(n) lineal\nO(n log n) casi lineal\nO(n²) cuadrático`, ["Big-O describe crecimiento asintótico.", "no mide segundos exactos.", "permite razonar independientemente del hardware."], "Puedes estimar el orden de crecimiento de bucles y búsquedas comunes."),

  scope: C("scope", "Scope / ámbito", "El scope define en qué región del programa existe y puede verse un nombre.", "Evita colisiones y controla qué estado puede tocar cada parte.", "Úsalo para razonar sobre variables locales, módulos y closures.", "Cada bloque o función crea una zona de visibilidad.", "javascript", `const global = 1;\nfunction demo() {\n  const local = 2;\n  console.log(global, local);\n}\ndemo();`, ["global está en ámbito exterior.", "local solo existe dentro de demo.", "la función puede leer ámbitos exteriores."], "Puedes predecir qué nombre resuelve cada referencia y evitar estado global innecesario."),
  closures: C("closures", "Closures", "Un closure es una función que conserva acceso al entorno léxico donde fue creada.", "Permite encapsular estado y construir callbacks, fábricas y APIs funcionales.", "Úsalo cuando una función necesite recordar datos privados entre llamadas.", "La función lleva una mochila con referencias a variables de su entorno.", "javascript", `function contador() {\n  let n = 0;\n  return () => ++n;\n}\nconst siguiente = contador();\nconsole.log(siguiente(), siguiente());`, ["n nace dentro de contador.", "la función retornada captura n.", "cada llamada modifica el mismo n privado."], "Puedes explicar qué variables captura una función y cuánto viven."),
  promises: C("promises", "Promises", "Una Promise representa un resultado que llegará más tarde o fallará.", "Permite coordinar operaciones asíncronas sin bloquear toda la aplicación.", "Úsala para red, archivos, timers y APIs asíncronas.", "Es un recibo: todavía no tienes el resultado, pero tienes una promesa de éxito o error.", "javascript", `Promise.resolve(5)\n  .then(n => n * 2)\n  .then(console.log);`, ["Promise.resolve crea un resultado futuro ya resuelto.", "then transforma el valor.", "el siguiente then recibe 10."], "Puedes encadenar éxito/error y evitar mezclar asincronía con flujo síncrono."),
  "async/await": C("async", "async/await", "async/await es sintaxis para expresar Promises como un flujo secuencial legible.", "Hace más comprensible el código asíncrono y el manejo de errores.", "Úsalo dentro de funciones async cuando dependas de resultados asíncronos.", "await dice: pausa esta función, no todo el programa, hasta que llegue el resultado.", "javascript", `async function demo() {\n  const n = await Promise.resolve(5);\n  return n * 2;\n}\ndemo().then(console.log);`, ["async hace que demo devuelva una Promise.", "await obtiene el valor resuelto.", "return se convierte en resolución de Promise."], "Puedes explicar qué se pausa y qué no cuando usas await."),
  módulos: C("modules", "Módulos", "Un módulo agrupa código con una interfaz explícita de importación/exportación.", "Reduce acoplamiento y permite dividir un sistema en partes mantenibles.", "Úsalo cuando una responsabilidad tenga identidad propia y consumidores claros.", "Cada módulo es una caja con una API pública y detalles privados.", "javascript", `// math.js\nexport const doble = n => n * 2;\n// app.js\n// import { doble } from './math.js'`, ["export define API pública.", "import consume esa API.", "el resto puede permanecer interno."], "Puedes diseñar límites de módulo y evitar exportar detalles accidentales."),
  "event loop": C("eventloop", "Event loop", "El event loop coordina tareas síncronas, callbacks y colas asíncronas en JavaScript.", "Explica por qué operaciones asíncronas no ejecutan exactamente cuando las escribes.", "Úsalo para razonar sobre UI, timers, Promises y orden de callbacks.", "Una sola persona atiende una cola: termina la tarea actual y luego toma la siguiente.", "javascript", `console.log("A");\nsetTimeout(() => console.log("C"), 0);\nPromise.resolve().then(() => console.log("B"));\nconsole.log("D");`, ["A y D son síncronos.", "la microtarea de Promise ocurre antes del timer.", "el orden típico es A, D, B, C."], "Puedes predecir el orden de ejecución de tareas síncronas, microtareas y timers."),

  arrays: C("arrays", "Arrays", "Un array almacena elementos contiguos o indexados por posición y permite acceso rápido por índice.", "Es la base de muchas colecciones y algoritmos.", "Úsalo cuando necesites secuencia compacta y acceso por posición.", "Una hilera de casillas numeradas.", "javascript", `const xs = [10, 20, 30];\nconsole.log(xs[1]);\nxs.push(40);`, ["índice 1 es el segundo elemento.", "push agrega al final.", "el acceso por índice es directo."], "Puedes analizar acceso, inserción y borrado según la posición."),
  "linked lists": C("linkedlists", "Listas enlazadas", "Una lista enlazada conecta nodos mediante referencias al siguiente nodo.", "Permite inserciones locales sin mover todos los elementos, a costa de acceso secuencial.", "Úsala cuando importen inserciones/eliminaciones locales y no necesites acceso aleatorio frecuente.", "Cada vagón sabe cuál es el siguiente.", "javascript", `const c = { value: 3, next: null };\nconst b = { value: 2, next: c };\nconst a = { value: 1, next: b };\nconsole.log(a.next.value);`, ["cada nodo guarda valor y next.", "a apunta a b.", "para llegar a c debes seguir enlaces."], "Puedes comparar costes de array vs lista enlazada."),
  stack: C("stack", "Pila (stack)", "Una pila es una colección LIFO: el último en entrar es el primero en salir.", "Modela llamadas, undo, parsers y navegación.", "Úsala cuando el orden natural sea 'lo último pendiente se atiende primero'.", "Una pila de platos.", "javascript", `const pila = [];\npila.push("A");\npila.push("B");\nconsole.log(pila.pop());`, ["push apila.", "pop retira el último.", "sale B antes que A."], "Puedes identificar problemas LIFO y simular sus operaciones."),
  queue: C("queue", "Cola (queue)", "Una cola es FIFO: el primero en entrar es el primero en salir.", "Modela tareas, eventos, BFS y sistemas de mensajería.", "Úsala cuando quieras respetar orden de llegada.", "Una fila de personas.", "javascript", `const cola = ["A", "B"];\ncola.push("C");\nconsole.log(cola.shift());`, ["push agrega al final.", "shift retira el primero.", "sale A."], "Puedes identificar problemas FIFO y diferenciar cola de pila."),
  hash: C("hash", "Hash maps", "Un hash map transforma una clave en una posición de almacenamiento para búsquedas rápidas promedio.", "Permite índices, conteos, caches y asociaciones clave→valor eficientes.", "Úsalo cuando necesites buscar por clave y el orden no sea lo principal.", "Una función hash decide en qué casillero buscar la clave.", "python", `conteo = {}\nfor letra in "casa":\n    conteo[letra] = conteo.get(letra, 0) + 1\nprint(conteo)`, ["cada letra es clave.", "get obtiene conteo previo o 0.", "se incrementa el valor asociado."], "Puedes explicar colisiones a alto nivel y elegir claves adecuadas."),
  "Big-O": C("bigo", "Big-O", "Big-O describe una cota del crecimiento del coste de un algoritmo al crecer la entrada.", "Permite comparar escalabilidad sin depender de una máquina concreta.", "Úsalo para justificar decisiones de estructura y algoritmo.", "Ignora detalles pequeños y observa el término que domina para entradas grandes.", "text", `Acceso array: O(1)\nBúsqueda lineal: O(n)\nBúsqueda binaria: O(log n)\nDos bucles anidados: O(n²)`, ["O(1) no crece con n.", "O(n) crece aproximadamente proporcional.", "O(log n) reduce el problema por factor.", "O(n²) aparece a menudo con pares."], "Puedes derivar complejidad temporal y espacial de código sencillo."),

  "binary search": C("binary", "Búsqueda binaria", "Busca en datos ordenados descartando la mitad del espacio en cada comparación.", "Reduce una búsqueda de O(n) a O(log n) cuando se cumplen sus condiciones.", "Úsala sobre una colección ordenada con acceso al elemento medio.", "Abres un diccionario por la mitad y decides en qué mitad seguir.", "python", `def buscar(xs, objetivo):\n    lo, hi = 0, len(xs)-1\n    while lo <= hi:\n        mid = (lo + hi)//2\n        if xs[mid] == objetivo: return mid\n        if xs[mid] < objetivo: lo = mid + 1\n        else: hi = mid - 1\n    return -1`, ["lo/hi delimitan el intervalo posible.", "mid elige el centro.", "cada comparación elimina media búsqueda."], "Puedes mantener el invariante del intervalo y evitar errores off-by-one."),
  sorting: C("sorting", "Ordenamiento", "Ordenar reorganiza datos según una relación: menor→mayor, fecha, prioridad, etc.", "Muchos algoritmos posteriores dependen del orden y una presentación ordenada facilita análisis.", "Úsalo cuando el coste de ordenar se amortice con búsquedas, agrupación o salida requerida.", "Conviertes una colección desordenada en una secuencia con una regla establecida.", "javascript", `const xs = [8, 2, 5, 1];\nconst ordenados = [...xs].sort((a,b) => a-b);\nconsole.log(ordenados);`, ["[...] copia para no mutar xs.", "comparador a-b define orden numérico.", "sort devuelve la colección ordenada."], "Puedes comparar selection/insertion/merge/quick sort y reconocer estabilidad e in-place."),
  "two pointers": C("twopointers", "Dos punteros", "Mantiene dos posiciones que avanzan según una regla para evitar trabajo repetido.", "Convierte muchos problemas de pares o ventanas de O(n²) a O(n) tras ordenar o usar estructura adecuada.", "Úsalo en arrays/cadenas cuando dos extremos o dos posiciones puedan moverse monotónicamente.", "Dos dedos recorren la secuencia sin volver atrás innecesariamente.", "python", `xs = [1,2,4,6,9]\ni,j = 0,len(xs)-1\nobjetivo=10\nwhile i<j:\n    s=xs[i]+xs[j]\n    if s==objetivo: break\n    if s<objetivo: i+=1\n    else: j-=1\nprint(xs[i],xs[j])`, ["i parte al inicio y j al final.", "la suma decide qué puntero mover.", "cada puntero avanza como máximo n veces."], "Puedes demostrar por qué no descartas una solución al mover cada puntero."),
  window: C("window", "Sliding window", "Mantiene una subregión móvil y actualiza su estado al entrar/salir elementos.", "Evita recalcular desde cero cada subsegmento.", "Úsalo en secuencias para máximos, sumas, longitudes o restricciones sobre segmentos contiguos.", "Una ventana se desliza sobre datos manteniendo un resumen de lo que contiene.", "python", `xs=[2,1,5,1,3,2]\nk=3\ns=sum(xs[:k]); mejor=s\nfor i in range(k,len(xs)):\n    s += xs[i]-xs[i-k]\n    mejor=max(mejor,s)\nprint(mejor)`, ["s resume la ventana actual.", "entra xs[i].", "sale xs[i-k].", "no se vuelve a sumar toda la ventana."], "Puedes identificar estado incremental de una ventana fija o variable."),
  "divide & conquer": C("divide", "Divide y vencerás", "Divide el problema en subproblemas, los resuelve y combina resultados.", "Permite diseños eficientes como merge sort y muchas estrategias recursivas.", "Úsalo cuando subproblemas sean similares e independientes y exista una combinación clara.", "Rompe, resuelve piezas, junta.", "text", `resolver(problema):\n  si es pequeño → solución directa\n  dividir → A, B\n  x = resolver(A)\n  y = resolver(B)\n  combinar(x, y)`, ["hay un caso base.", "se divide en partes más pequeñas.", "las soluciones parciales se combinan."], "Puedes definir subproblemas, caso base y coste de combinación."),
  greedy: C("greedy", "Greedy / voraz", "Un algoritmo voraz elige en cada paso la opción local que parece mejor.", "Para ciertos problemas produce una solución óptima simple y eficiente.", "Úsalo solo cuando puedas justificar la propiedad de elección voraz y estructura óptima.", "Toma la mejor decisión disponible sin volver atrás.", "python", `monedas=[25,10,5,1]\nresto=41\nusadas=[]\nfor m in monedas:\n    while resto>=m:\n        resto-=m; usadas.append(m)\nprint(usadas)`, ["se prueban monedas grandes primero.", "cada paso toma la opción local mayor.", "no todos los sistemas de monedas admiten este greedy como óptimo."], "Puedes distinguir cuándo un greedy es correcto y cuándo requiere prueba o contraejemplo."),

  trees: C("trees", "Árboles", "Un árbol es una estructura jerárquica de nodos conectados sin ciclos entre padre e hijos.", "Modela jerarquías, búsquedas, sintaxis y estructuras recursivas.", "Úsalo cuando los datos tengan relación jerárquica o particiones recursivas.", "Un árbol genealógico: raíz, ramas y hojas.", "python", `arbol = {"valor": 8, "izq": {"valor": 3}, "der": {"valor": 10}}\nprint(arbol["izq"]["valor"])`, ["la raíz vale 8.", "izq y der son subárboles.", "la estructura se define recursivamente."], "Puedes recorrer un árbol y definir invariantes para BST u otras variantes."),
  heaps: C("heaps", "Heaps", "Un heap mantiene el elemento de mayor o menor prioridad accesible en la raíz.", "Implementa colas de prioridad con inserción/extracción O(log n).", "Úsalo cuando repetidamente necesites el mínimo/máximo sin ordenar todo.", "Un torneo: el ganador está arriba y solo una ruta necesita reajustarse.", "python", `import heapq\nh=[5,1,8]\nheapq.heapify(h)\nheapq.heappush(h,2)\nprint(heapq.heappop(h))`, ["heapify reorganiza con propiedad de heap.", "heappush conserva la propiedad.", "heappop devuelve el mínimo."], "Puedes explicar propiedad de heap y sus costes."),
  graphs: C("graphs", "Grafos", "Un grafo modela entidades como nodos y relaciones como aristas.", "Representa redes, rutas, dependencias, recomendaciones y estados.", "Úsalo cuando las relaciones no formen una simple secuencia o jerarquía.", "Un mapa de ciudades conectadas por carreteras.", "python", `grafo={"A":["B","C"],"B":["D"],"C":[],"D":[]}\nprint(grafo["A"])`, ["A es un nodo.", "B/C son vecinos de A.", "la lista de adyacencia guarda conexiones."], "Puedes elegir representación y razonar sobre dirigido/no dirigido, peso y ciclos."),
  "BFS/DFS": C("bfsdfs", "BFS y DFS", "BFS recorre por capas usando cola; DFS profundiza una rama usando pila/recursión.", "Son patrones fundamentales para explorar grafos y árboles.", "Usa BFS para menor número de aristas en grafos no ponderados; DFS para componentes, ciclos, ordenamientos y exploración profunda.", "BFS = ondas que se expanden; DFS = explorador que sigue un túnel hasta el final.", "python", `from collections import deque\ng={"A":["B","C"],"B":["D"],"C":[],"D":[]}\nq=deque(["A"]); seen={"A"}\nwhile q:\n    u=q.popleft(); print(u)\n    for v in g[u]:\n        if v not in seen: seen.add(v); q.append(v)`, ["cola define orden BFS.", "seen evita ciclos/repeticiones.", "cada vecino nuevo entra al final."], "Puedes implementar ambos, justificar su estructura auxiliar y analizar O(V+E)."),
  Dijkstra: C("dijkstra", "Dijkstra", "Dijkstra calcula caminos mínimos desde una fuente cuando los pesos son no negativos.", "Permite rutas y costes mínimos en redes ponderadas.", "Úsalo con aristas de peso no negativo; con negativos necesitas otros algoritmos.", "Expande siempre el nodo conocido más barato y relaja sus vecinos.", "text", `dist[origen]=0\nheap=[(0,origen)]\nmientras heap:\n  coste,u = extraer mínimo\n  para cada (v,peso):\n    si coste+peso < dist[v]: actualizar`, ["dist guarda mejor coste conocido.", "heap elige el siguiente nodo más prometedor.", "relajación mejora distancias."], "Puedes explicar relajación, restricción de pesos y complejidad con heap."),
  DP: C("dp", "Programación dinámica", "DP resuelve problemas con subproblemas solapados guardando resultados para no repetir trabajo.", "Convierte muchas recursiones exponenciales en soluciones polinómicas.", "Úsala cuando exista subestructura óptima y los mismos subproblemas aparezcan varias veces.", "Una tabla de respuestas parciales reutilizables.", "python", `def fib(n):\n    if n<2: return n\n    dp=[0,1]\n    for i in range(2,n+1):\n        dp.append(dp[-1]+dp[-2])\n    return dp[n]\nprint(fib(10))`, ["casos base 0/1.", "cada estado depende de estados anteriores.", "cada subproblema se calcula una vez."], "Puedes definir estado, transición, base y orden de cálculo."),

  OOP: C("oop", "Programación orientada a objetos", "OOP organiza comportamiento y estado alrededor de objetos con identidad e interfaces.", "Puede modelar dominios con entidades que mantienen invariantes y comportamiento relacionado.", "Úsala cuando estado y operaciones pertenezcan claramente a una abstracción con identidad.", "Un objeto protege su estado detrás de métodos.", "python", `class Cuenta:\n    def __init__(self, saldo): self._saldo = saldo\n    def depositar(self, monto): self._saldo += monto\n    def saldo(self): return self._saldo`, ["__init__ establece estado válido.", "_saldo es detalle interno.", "métodos controlan cómo cambia el objeto."], "Puedes distinguir encapsulación útil de clases que solo agrupan datos sin propósito."),
  FP: C("fp", "Programación funcional", "FP enfatiza funciones, datos inmutables y composición, reduciendo efectos secundarios.", "Facilita razonamiento, pruebas y concurrencia cuando las transformaciones son predecibles.", "Úsala para pipelines de datos, transformaciones y lógica que puede expresarse sin mutación global.", "Entrada → función pura → nueva salida, sin cambiar el mundo ocultamente.", "javascript", `const xs=[1,2,3,4];\nconst pares=xs.filter(x=>x%2===0);\nconst dobles=pares.map(x=>x*2);\nconsole.log(dobles);`, ["filter selecciona sin mutar xs.", "map transforma produciendo otra colección.", "la composición hace explícito el flujo."], "Puedes identificar efectos y separar lógica pura de I/O."),
  SOLID: C("solid", "Principios SOLID", "SOLID es un conjunto de heurísticas para diseñar módulos/clases con responsabilidades y dependencias más manejables.", "Ayuda a reducir cambios en cascada y facilita pruebas, aunque no son leyes absolutas.", "Úsalos al revisar diseño, no como ritual antes de entender el problema.", "Pregunta qué cambia junto, qué interfaz necesita el cliente y de qué depende la lógica.", "text", `S: una razón coherente para cambiar\nO: extender sin reescribir todo\nL: sustitución válida\nI: interfaces pequeñas por cliente\nD: depender de abstracciones útiles`, ["cada letra ataca una forma de acoplamiento.", "aplicarlos mecánicamente puede sobre-diseñar."], "Puedes reconocer violaciones concretas y explicar el trade-off de corregirlas."),
  patterns: C("patterns", "Patrones de diseño", "Un patrón nombra una solución recurrente a un problema de diseño en un contexto.", "Proporciona vocabulario y estructuras conocidas, evitando reinventar sin necesidad.", "Úsalo cuando el problema coincida con el contexto y consecuencias del patrón.", "No empieces por el patrón; empieza por la fuerza del problema y luego reconoce una forma conocida.", "text", `Strategy: intercambiar algoritmo detrás de una interfaz\nObserver: notificar cambios a suscriptores\nAdapter: traducir una interfaz a otra`, ["el patrón describe roles y relaciones.", "no es copiar una clase exacta."], "Puedes justificar por qué un patrón mejora un problema específico y cuándo añadiría complejidad innecesaria."),
  "DDD básico": C("ddd", "DDD básico", "Domain-Driven Design intenta alinear el modelo del software con conceptos y lenguaje del dominio del negocio.", "Reduce traducciones ambiguas entre personas y código en dominios complejos.", "Úsalo cuando las reglas del dominio sean ricas y cambien; no para CRUD trivial.", "El mismo lenguaje debe aparecer en conversación, requisitos, nombres y modelos.", "text", `Pedido.confirmar()\nReserva.cancelar()\nFactura.emitir()`, ["los nombres expresan acciones del dominio.", "las reglas viven cerca del modelo que protegen."], "Puedes construir un vocabulario ubicuo y separar dominio de detalles técnicos."),
  refactor: C("refactor", "Refactorización", "Refactorizar cambia la estructura interna sin cambiar comportamiento observable.", "Mejora legibilidad, diseño y capacidad de cambio manteniendo seguridad mediante tests.", "Úsalo en pasos pequeños con pruebas verdes.", "Limpias la habitación sin cambiar lo que la habitación permite hacer.", "text", `antes: función de 120 líneas\ndespués: funciones pequeñas con nombres que expresan intención\ncomportamiento externo: igual`, ["primero existe una red de seguridad.", "cada cambio estructural debe preservar resultados."], "Puedes realizar refactors pequeños y demostrar equivalencia con tests."),

  HTTP: C("http", "HTTP", "HTTP es un protocolo de petición/respuesta para intercambiar representaciones y comandos entre clientes y servidores.", "Es la base de la web y muchas APIs.", "Úsalo al construir clientes, servidores, APIs, caches y navegación web.", "Cliente envía método+URL+headers+body; servidor devuelve status+headers+body.", "text", `GET /productos/42 HTTP/1.1\nAccept: application/json\n\nHTTP/1.1 200 OK\nContent-Type: application/json\n\n{"id":42}`, ["GET expresa operación de lectura.", "URL identifica recurso.", "status 200 indica éxito.", "headers describen metadatos."], "Puedes elegir método/status y explicar idempotencia, cache y cuerpo."),
  "semantic HTML": C("html", "HTML semántico", "HTML describe estructura y significado del contenido, no solo cómo se ve.", "Mejora accesibilidad, SEO, mantenibilidad y comportamiento del navegador.", "Úsalo siempre en documentos web eligiendo el elemento por significado.", "La página es un documento con secciones, navegación, encabezados, formularios y controles.", "text", `<main>\n  <article>\n    <h1>Título</h1>\n    <p>Contenido</p>\n  </article>\n</main>`, ["main identifica contenido principal.", "article representa una unidad autónoma.", "h1 establece encabezado.", "p representa párrafo."], "Puedes justificar cada etiqueta por semántica y no por estilo."),
  CSS: C("css", "CSS", "CSS define presentación, layout y estados visuales de un documento.", "Separa contenido de apariencia y permite diseño adaptable.", "Úsalo para tipografía, espacio, color, layout, responsive y estados.", "HTML es estructura; CSS son reglas que seleccionan elementos y aplican propiedades.", "text", `.card {\n  display: grid;\n  gap: 1rem;\n  padding: 1.5rem;\n}`, [".card es selector.", "display:grid elige modelo de layout.", "gap separa hijos.", "padding crea espacio interior."], "Puedes explicar cascade, specificity, box model, flex/grid y responsive."),
  DOM: C("dom", "DOM", "El DOM es la representación en memoria del documento HTML como árbol de nodos manipulable por JavaScript.", "Permite que una página cambie en respuesta a datos y eventos.", "Úsalo cuando JavaScript deba leer o modificar la interfaz sin framework.", "HTML se parsea a un árbol; JavaScript obtiene referencias a nodos y cambia propiedades/estructura.", "javascript", `const out = document.querySelector('#out');\nout.textContent = 'Hola';`, ["querySelector busca un nodo.", "textContent cambia su contenido textual."], "Puedes manipular DOM evitando consultas y cambios innecesarios."),
  a11y: C("a11y", "Accesibilidad web", "Accesibilidad significa que personas con distintas capacidades y tecnologías de asistencia puedan usar el producto.", "Es parte de la calidad y la inclusión, no un añadido estético.", "Considérala desde la estructura HTML, teclado, foco, contraste y nombres accesibles.", "Construye primero con controles nativos y semántica; agrega ARIA solo cuando falta semántica nativa.", "text", `<label for="email">Correo</label>\n<input id="email" type="email" required>`, ["label da nombre accesible.", "for conecta label con input.", "type=email aporta semántica/validación."], "Puedes navegar tu interfaz solo con teclado y explicar nombres/roles/estados."),
  responsive: C("responsive", "Diseño responsive", "Responsive adapta layout y contenido al espacio y capacidades disponibles.", "Evita interfaces rotas entre móvil, tablet y escritorio.", "Úsalo desde el primer componente, no como parche final.", "Diseña fluidamente y añade breakpoints solo cuando el contenido lo exige.", "text", `.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(240px,1fr)); }`, ["auto-fit usa columnas posibles.", "minmax evita tarjetas demasiado estrechas.", "1fr reparte espacio."], "Puedes diseñar sin overflow y verificar touch, texto, controles y orientación."),

  types: C("types-ts", "Tipos estáticos", "Un sistema de tipos estático verifica propiedades del programa antes de ejecutarlo.", "Detecta clases de errores temprano y documenta contratos entre componentes.", "Úsalo en sistemas donde múltiples partes deben acordar estructuras y operaciones.", "El compilador actúa como revisor automático de ciertas reglas.", "javascript", `type Usuario = { id: number; nombre: string };\nconst ada: Usuario = { id: 1, nombre: "Ada" };`, ["type define forma esperada.", "id debe ser number.", "nombre debe ser string."], "Puedes modelar tipos útiles sin abusar de any o anotaciones redundantes."),
  components: C("components", "Componentes", "Un componente encapsula una unidad de interfaz con entrada, estado opcional y salida visual.", "Permite componer UIs y aislar responsabilidades.", "Úsalo cuando una pieza tenga identidad, comportamiento o reutilización propios.", "Una función visual: props → UI.", "javascript", `function Saludo({ nombre }) {\n  return '<h1>Hola ' + nombre + '</h1>';\n}`, ["nombre es entrada.", "la salida representa UI.", "en frameworks reales se usa su sintaxis de render."], "Puedes definir fronteras de componentes por responsabilidad, no por cada div."),
  state: C("state", "Estado de UI", "El estado es información que cambia con el tiempo y afecta lo que se muestra o cómo responde la interfaz.", "Permite UIs interactivas y consistentes con acciones del usuario/datos.", "Guarda solo aquello que realmente cambia y no puede derivarse fácilmente de otra fuente.", "UI = función del estado actual.", "javascript", `let cantidad = 1;\nconst precio = 20;\nconst total = () => cantidad * precio;\ncantidad++;\nconsole.log(total());`, ["cantidad es estado mutable.", "precio es constante.", "total es derivado y no necesita duplicarse."], "Puedes distinguir estado fuente de estado derivado y evitar inconsistencias."),
  testing: C("frontend-testing", "Testing de aplicaciones", "Testing verifica unidades, integración y comportamiento visible bajo condiciones controladas.", "Evita regresiones y permite refactorizar con confianza.", "Usa el nivel de prueba más barato que detecte el riesgo importante.", "Pirámide: muchas pruebas rápidas, menos integraciones y pocas end-to-end críticas.", "text", `unit: función pura\nintegration: componentes + API simulada\ne2e: flujo usuario completo`, ["cada nivel cubre riesgos distintos.", "más realismo suele costar más tiempo y fragilidad."], "Puedes elegir qué probar y evitar tests acoplados a detalles internos."),
  performance: C("frontend-performance", "Performance", "Performance mide latencia, uso de CPU/memoria/red y capacidad de respuesta percibida.", "Una interfaz lenta afecta usabilidad y escalabilidad.", "Optimiza después de medir un cuello de botella reproducible.", "Medir → localizar → cambiar → volver a medir.", "javascript", `const inicio = performance.now();\n// trabajo\nconsole.log(performance.now() - inicio);`, ["performance.now mide alta resolución.", "una medición aislada no basta para benchmark serio."], "Puedes perfilar antes de optimizar y distinguir CPU, red, render y memoria."),
  "design systems": C("designsystems", "Design systems", "Un design system reúne decisiones reutilizables de diseño, componentes, tokens y reglas de uso.", "Reduce inconsistencias y acelera desarrollo de productos grandes.", "Úsalo cuando múltiples pantallas/equipos comparten patrones repetidos.", "Tokens → componentes → patrones → páginas.", "text", `--space-2: .5rem;\n--radius-card: 1rem;\nButton / Input / Card / Modal`, ["tokens capturan decisiones básicas.", "componentes implementan comportamientos y accesibilidad.", "patrones combinan componentes."], "Puedes separar lenguaje visual, implementación y reglas de producto."),

  REST: C("rest", "REST", "REST es un estilo para diseñar APIs alrededor de recursos, representaciones y semántica HTTP.", "Aprovecha convenciones web y hace APIs más predecibles.", "Úsalo para APIs HTTP orientadas a recursos; no es obligatorio para todo sistema.", "URLs nombran recursos; métodos expresan operaciones; status expresan resultado.", "text", `GET /users/42\nPOST /users\nPATCH /users/42\nDELETE /users/42`, ["GET lee.", "POST suele crear/accionar.", "PATCH modifica parcialmente.", "DELETE elimina."], "Puedes diseñar endpoints coherentes, idempotencia y errores."),
  GraphQL: C("graphql", "GraphQL", "GraphQL define un esquema tipado y permite al cliente solicitar exactamente campos y relaciones necesarios.", "Reduce over/under-fetching en dominios conectados y centraliza contrato de consulta.", "Úsalo cuando múltiples clientes necesitan vistas variables de un grafo de datos.", "El cliente describe la forma de la respuesta y el servidor resuelve cada campo.", "text", `query {\n  user(id: 42) { id name posts { title } }\n}`, ["query inicia una lectura.", "user recibe argumento.", "subselecciones definen campos solicitados."], "Puedes diseñar esquema, resolver N+1 y controlar autorización por campo/objeto."),
  auth: C("auth", "Autenticación y autorización", "Autenticación responde quién eres; autorización responde qué puedes hacer.", "Protege datos y acciones con identidad y políticas explícitas.", "Úsalo en cualquier sistema con cuentas, roles o recursos privados.", "Identidad → sesión/token → política → decisión de acceso.", "text", `login → verificar credencial → emitir sesión\nrequest → identificar usuario → autorizar acción → ejecutar`, ["autenticación ocurre antes de confiar en identidad.", "autorización debe ejecutarse en servidor para recursos protegidos."], "Puedes separar autenticación de autorización y modelar políticas por recurso."),
  queues: C("queues-backend", "Colas de trabajo", "Una cola desacopla productor y consumidor almacenando tareas/eventos pendientes.", "Absorbe picos, permite trabajo asíncrono y reintentos.", "Úsala cuando el trabajo no deba bloquear la petición y pueda procesarse después.", "Productor deja mensaje; worker lo toma, procesa y confirma.", "text", `API → cola → worker → email\n          ↘ retry / dead-letter`, ["la cola no garantiza mágicamente exactamente-una-vez.", "el consumidor debe ser idempotente cuando sea necesario."], "Puedes diseñar reintentos, idempotencia y dead-letter queues."),
  events: C("events", "Arquitectura orientada a eventos", "Un evento representa un hecho ocurrido que otros componentes pueden observar.", "Desacopla productores de múltiples reacciones y permite integración asíncrona.", "Úsala para hechos de dominio que interesen a varios consumidores.", "Hecho inmutable publicado → múltiples consumidores deciden qué hacer.", "text", `OrderPlaced { orderId, occurredAt }\n → inventory\n → billing\n → analytics`, ["el nombre expresa pasado.", "el evento transporta datos del hecho.", "consumidores no deberían controlar al productor."], "Puedes distinguir evento de comando y diseñar versionado/compatibilidad."),
  observability: C("observability", "Observabilidad", "Observabilidad permite inferir el estado interno de un sistema mediante señales como logs, métricas y trazas.", "En producción no puedes depurar mirando el código únicamente.", "Diseñala desde el inicio para operaciones críticas y sistemas distribuidos.", "Logs cuentan hechos; métricas resumen tendencias; trazas conectan recorrido de una petición.", "text", `log: payment_failed order=42\nmetric: http_errors_total\ntrace: gateway → orders → payments`, ["cada señal responde preguntas distintas.", "los identificadores de correlación conectan eventos."], "Puedes diagnosticar un fallo con señales y definir SLI/SLO útiles."),

  normalization: C("normalization", "Normalización", "Normalizar organiza relaciones para reducir duplicación y anomalías de actualización.", "Mantiene consistencia y hace explícitas dependencias entre entidades.", "Úsala como base de modelado relacional, luego desnormaliza solo por necesidad medida.", "Cada hecho se almacena una vez en la tabla que representa su entidad/relación.", "text", `usuarios(id,nombre)\npedidos(id,usuario_id,total)`, ["usuario no se repite entero en cada pedido.", "usuario_id crea relación."], "Puedes identificar dependencias y justificar 1NF/2NF/3NF a nivel práctico."),
  SQL: C("sql", "SQL", "SQL es un lenguaje declarativo para definir, consultar y modificar datos relacionales.", "Permite expresar qué conjunto de datos necesitas sin programar manualmente el algoritmo de acceso.", "Úsalo con bases relacionales para consultas, agregaciones y transacciones.", "Describe el resultado; el optimizador decide un plan físico.", "text", `SELECT customer_id, SUM(total)\nFROM orders\nGROUP BY customer_id;`, ["SELECT define columnas/resultados.", "FROM define fuente.", "GROUP BY agrupa.", "SUM agrega."], "Puedes escribir joins, agregaciones, subconsultas y leer planes básicos."),
  indexes: C("indexes", "Índices", "Un índice mantiene una estructura auxiliar para localizar filas sin escanear toda la tabla.", "Reduce latencia de lecturas a cambio de espacio y coste en escrituras.", "Úsalo según patrones reales de filtros, joins y orden; no indexes cada columna.", "Es el índice alfabético de un libro: acelera encontrar páginas, pero hay que actualizarlo.", "text", `CREATE INDEX idx_orders_customer ON orders(customer_id);`, ["el índice se basa en customer_id.", "consultas que filtran/unen por esa columna pueden beneficiarse."], "Puedes proponer índices basados en consultas y verificar con EXPLAIN."),
  transactions: C("transactions", "Transacciones", "Una transacción agrupa operaciones que deben observarse como una unidad coherente.", "Evita estados parciales ante fallos y coordina concurrencia.", "Úsala cuando varias operaciones relacionadas deban confirmar o revertir juntas.", "BEGIN crea una frontera; COMMIT confirma; ROLLBACK deshace.", "text", `BEGIN;\nUPDATE accounts SET balance=balance-50 WHERE id=1;\nUPDATE accounts SET balance=balance+50 WHERE id=2;\nCOMMIT;`, ["ambos cambios pertenecen a la transferencia.", "un error antes de COMMIT debe permitir rollback."], "Puedes explicar atomicidad, aislamiento y anomalías comunes."),
  NoSQL: C("nosql", "NoSQL", "NoSQL agrupa modelos no relacionales como documentos, clave-valor, columnas y grafos.", "Ofrece modelos y escalabilidad útiles para patrones donde tablas/joins no son la mejor forma.", "Úsalo por requisitos concretos de modelo, escala, latencia o distribución, no por moda.", "El modelo de almacenamiento debe parecerse a los accesos dominantes.", "text", `documento usuario { id, perfil, preferencias }\nclave-valor session:abc → {...}\ngrafo user → follows → user`, ["cada familia optimiza relaciones/accesos distintos.", "las garantías transaccionales varían."], "Puedes comparar modelo de acceso, consistencia, consultas y operaciones."),
  cache: C("cache", "Cache", "Una cache guarda resultados reutilizables cerca del consumidor para evitar trabajo repetido.", "Reduce latencia y carga, pero introduce invalidación y datos potencialmente obsoletos.", "Úsala cuando el coste de recomputar/leer sea significativo y toleres una política de frescura.", "Antes de hacer trabajo caro, mira si existe una copia válida.", "text", `key = "user:42"\ncache.get(key) ?? db.load(42) → cache.set(key,value,ttl)`, ["key identifica resultado.", "miss consulta origen.", "TTL limita antigüedad."], "Puedes definir key, TTL, invalidación y comportamiento ante cache miss."),

  shell: C("shell", "Shell", "Una shell interpreta comandos y conecta programas mediante archivos, pipes y procesos.", "Es una herramienta universal para automatizar, inspeccionar y componer sistemas.", "Úsala para tareas repetibles, pipelines, administración y tooling.", "Cada comando es una herramienta; | conecta salida de una con entrada de otra.", "text", `cat app.log | grep ERROR | sort | uniq -c`, ["cat produce texto.", "grep filtra líneas.", "sort ordena.", "uniq -c cuenta repetidos."], "Puedes componer comandos y explicar stdin/stdout/stderr y códigos de salida."),
  processes: C("processes", "Procesos", "Un proceso es una instancia de un programa en ejecución con memoria, recursos y contexto propios.", "Permite aislamiento y concurrencia a nivel del sistema operativo.", "Úsalo para razonar sobre ejecución, servicios, señales y pipelines.", "Programa = receta en disco; proceso = receta cocinándose con estado vivo.", "text", `programa → proceso PID 1234\nmemoria + archivos abiertos + hilos + entorno`, ["PID identifica proceso.", "el OS administra recursos y scheduling."], "Puedes distinguir programa, proceso e hilo y rastrear recursos básicos."),
  git: C("git", "Git", "Git es un sistema de control de versiones distribuido que modela snapshots/commits y referencias.", "Permite historial, colaboración, experimentación y recuperación.", "Úsalo para todo proyecto de software con cambios que deban rastrearse.", "Un commit es un snapshot con referencia a padre(s); una rama es una etiqueta móvil.", "text", `git add .\ngit commit -m "feat: validación"\ngit switch -c feature/x`, ["add prepara contenido.", "commit crea snapshot.", "branch permite línea de trabajo separada."], "Puedes explicar working tree, staging, commit, branch, merge/rebase y resolver conflictos."),
  debugging: C("debug-tools", "Debuggers", "Un debugger controla ejecución: breakpoints, step, inspección de variables y call stack.", "Hace visible el estado sin llenar el código de prints permanentes.", "Úsalo cuando necesites entender flujo y estado de ejecución.", "Congelas el programa en un instante y lo recorres paso a paso.", "text", `breakpoint → step over → inspect x → step into → call stack`, ["breakpoint detiene.", "step over ejecuta una línea sin entrar.", "step into entra en llamada.", "stack muestra cadena de llamadas."], "Puedes aislar un bug usando breakpoint y evidencia de estado."),
  profiling: C("profiling", "Profiling", "Un profiler mide dónde se consume tiempo, CPU, memoria o I/O.", "Evita optimizar por intuición y permite atacar cuellos reales.", "Úsalo cuando exista un problema medible de rendimiento.", "Mapa de calor del coste: encuentra el 10% del código que consume la mayor parte del recurso.", "text", `medir baseline → perfiler → hotspot → cambio → medir otra vez`, ["baseline es referencia.", "hotspot es zona costosa.", "la segunda medición valida mejora."], "Puedes producir benchmark reproducible y localizar hotspot antes de cambiar."),
  CI: C("ci", "Integración continua", "CI ejecuta automáticamente build, tests y checks ante cambios.", "Detecta problemas temprano y convierte estándares del equipo en reglas ejecutables.", "Úsala en repositorios colaborativos y despliegues repetibles.", "Cada commit pasa por una línea de inspección automática antes de integrarse.", "text", `push → lint → typecheck → tests → build → artifact`, ["cada etapa debe fallar claramente.", "artefactos se generan desde código versionado."], "Puedes diseñar pipeline rápido, determinista y con feedback útil."),

  memory: C("memory", "Memoria", "La memoria de un proceso contiene regiones para código, datos, stack, heap y mapeos administrados por OS/runtime.", "Comprenderla explica punteros, rendimiento, fugas, stack overflow y seguridad.", "Es esencial en C/C++, Rust, sistemas, runtimes y optimización.", "Direcciones identifican posiciones; distintas regiones tienen ciclos de vida y reglas diferentes.", "text", `stack: llamadas/locales\nheap: asignaciones dinámicas\ncode: instrucciones\nOS: memoria virtual → páginas físicas`, ["stack suele seguir llamadas.", "heap permite vidas dinámicas.", "memoria virtual aísla y abstrae memoria física."], "Puedes dibujar memoria de un programa simple y explicar ciclo de vida de datos."),
  pointers: C("pointers", "Punteros", "Un puntero almacena una dirección de memoria que permite acceder indirectamente a otro dato.", "Hace posibles estructuras enlazadas, buffers, APIs de bajo nivel y control explícito.", "Úsalo cuando el lenguaje/sistema requiera referencias explícitas y comprende ownership/lifetime.", "No contiene el objeto; contiene dónde encontrarlo.", "text", `int x = 42;\nint *p = &x;\n*p = 50;`, ["&x obtiene dirección.", "p guarda dirección.", "*p accede al valor en esa dirección."], "Puedes distinguir valor, dirección y desreferencia y evitar punteros colgantes."),
  processes_os: C("os-processes", "Procesos del sistema operativo", "El OS crea procesos aislados, los planifica y arbitra recursos.", "Permite ejecutar programas concurrentemente con protección.", "Úsalo para entender fork/exec, señales, scheduling e IPC.", "El kernel cambia de contexto entre procesos y controla privilegios.", "text", `process A ─┐\nprocess B ─┼→ scheduler → CPU\nprocess C ─┘`, ["scheduler elige quién ejecuta.", "context switch guarda/restaura estado."], "Puedes explicar creación, scheduling y comunicación básica entre procesos."),
  threads: C("threads", "Hilos", "Un hilo es una secuencia de ejecución dentro de un proceso que comparte memoria con otros hilos del mismo proceso.", "Permite concurrencia con comunicación rápida, pero introduce carreras.", "Úsalo cuando trabajo concurrente comparta estado y puedas sincronizarlo correctamente.", "Varios trabajadores comparten la misma mesa de datos.", "text", `process\n ├─ thread A\n ├─ thread B\n └─ shared heap`, ["cada hilo tiene stack propio.", "heap suele ser compartido.", "el orden de ejecución puede variar."], "Puedes identificar datos compartidos y posibles race conditions."),
  filesystems: C("filesystems", "Sistemas de archivos", "Un filesystem organiza nombres, directorios y datos persistentes sobre almacenamiento.", "Proporciona abstracción de archivos, permisos, metadata y durabilidad.", "Úsalo al guardar datos locales, diseñar formatos y razonar sobre persistencia.", "Nombre de archivo → metadata/inodo → bloques de datos.", "text", `/home/user/app.txt\nopen → fd → read/write → close`, ["ruta resuelve un archivo.", "descriptor identifica recurso abierto.", "write puede pasar por caches antes de disco."], "Puedes explicar ruta, descriptor, permisos, buffering y durabilidad básica."),
  sockets: C("sockets", "Sockets", "Un socket es una abstracción de comunicación entre endpoints, local o por red.", "Es la base de clientes/servidores TCP/UDP y muchos protocolos.", "Úsalo al construir networking de bajo nivel o entender qué hacen librerías HTTP.", "Un extremo abre un canal; otro se conecta; ambos leen/escriben bytes.", "text", `server: socket → bind → listen → accept\nclient: socket → connect\nboth: send/recv`, ["server escucha dirección/puerto.", "accept crea conexión.", "send/recv mueven bytes."], "Puedes explicar diferencia entre conexión, puerto, socket y protocolo de aplicación."),

  TCP: C("tcp", "TCP", "TCP ofrece un flujo de bytes confiable, ordenado y orientado a conexión sobre IP.", "Simplifica aplicaciones que necesitan entrega ordenada y retransmisión.", "Úsalo para HTTP tradicional, bases de datos, SSH y protocolos que necesitan stream confiable.", "TCP numera bytes, confirma recepción y reenvía pérdidas.", "text", `SYN → SYN/ACK → ACK\nbytes → ACKs / retransmission → ordered stream`, ["handshake establece estado.", "la aplicación ve stream, no mensajes originales."], "Puedes explicar handshake, stream, latencia, pérdida y por qué TCP no preserva mensajes."),
  concurrency: C("concurrency", "Concurrencia", "Concurrencia significa que varias tareas progresan en periodos solapados, aunque no necesariamente ejecuten al mismo instante.", "Permite manejar múltiples eventos, usuarios o trabajos y aprovechar recursos.", "Úsala cuando el problema tenga actividades independientes que esperan o progresan simultáneamente.", "Varias tareas comparten un calendario; paralelismo es ejecutarlas literalmente al mismo tiempo.", "text", `task A: compute → wait I/O → compute\ntask B:      compute → wait → compute`, ["la espera de una tarea deja oportunidad a otra.", "el orden relativo puede variar."], "Puedes distinguir concurrencia de paralelismo y reconocer estado compartido."),
  locks: C("locks", "Locks y exclusión mutua", "Un lock garantiza que una sección crítica sea ejecutada por un participante a la vez.", "Previene ciertas carreras cuando varias tareas modifican estado compartido.", "Úsalo cuando no puedas evitar estado mutable compartido y necesites una región atómica.", "Solo quien tiene la llave entra a la habitación crítica.", "text", `lock.acquire()\ntry:\n  shared = update(shared)\nfinally:\n  lock.release()`, ["adquirir antes de tocar estado.", "release debe ocurrir incluso ante error.", "orden de múltiples locks puede causar deadlock."], "Puedes identificar sección crítica, carrera y riesgo de deadlock."),
  consistency: C("consistency", "Consistencia distribuida", "Consistencia describe qué versiones de datos pueden observar distintos nodos/usuarios y en qué orden.", "En sistemas distribuidos no existe una única memoria instantánea gratis.", "Define el modelo según requisitos de negocio: fuerte, eventual, causal u otros.", "Cada réplica puede ver actualizaciones en momentos distintos; el contrato dice qué observaciones son válidas.", "text", `write A=v2 → replica 1 now\n              → replica 2 later\nclient may read v1 or v2 depending model`, ["replicación crea copias.", "latencia/fallos retrasan propagación.", "modelo de consistencia define garantías."], "Puedes relacionar garantía de consistencia con latencia/disponibilidad."),
  replication: C("replication", "Replicación", "Replicación mantiene copias de datos/servicios en varios nodos.", "Mejora disponibilidad, lectura y tolerancia a fallos, pero obliga a coordinar cambios.", "Úsala cuando una sola copia sea insuficiente por disponibilidad, latencia o escala.", "Múltiples copias deben recibir y ordenar cambios con una política.", "text", `leader → replica A\n       → replica B\nread replicas / failover`, ["leader puede ordenar escrituras.", "replicas pueden retrasarse.", "failover cambia quién sirve."], "Puedes explicar lag, failover y trade-offs de multi-leader/leaderless."),
  "fault tolerance": C("fault", "Tolerancia a fallos", "Un sistema tolerante a fallos continúa ofreciendo un nivel definido de servicio aunque algunos componentes fallen.", "En producción fallan máquinas, redes, discos, procesos y dependencias.", "Diseñala cuando el impacto de un fallo simple sea inaceptable.", "Asume fallos, detecta, limita daño, recupera y prueba el mecanismo.", "text", `timeout → retry limitado → circuit breaker → fallback\nreplication → health check → failover`, ["timeouts evitan esperas infinitas.", "retry puede empeorar sobrecarga.", "redundancia sin pruebas no garantiza recuperación."], "Puedes enumerar fallos, detectar punto único y diseñar recuperación probada."),

  DI: C("di", "Dependency Injection", "DI entrega dependencias desde fuera en vez de crearlas escondidamente dentro de una clase/función.", "Reduce acoplamiento y facilita pruebas/sustitución de implementaciones.", "Úsala cuando una lógica dependa de servicios externos o implementaciones intercambiables.", "La lógica declara qué necesita; el ensamblador decide qué implementación darle.", "javascript", `function service(repo) {\n  return { get: id => repo.load(id) };\n}`, ["repo entra como dependencia.", "service no sabe cómo se construye repo.", "test puede pasar un fake."], "Puedes identificar dependencia estable y evitar service locator/globales ocultos."),
  layers: C("layers", "Arquitectura por capas", "Las capas agrupan responsabilidades y restringen direcciones de dependencia.", "Ayudan a separar UI, aplicación, dominio e infraestructura en sistemas medianos/grandes.", "Úsala cuando esa separación reduzca cambios cruzados; evita capas ceremoniales en programas triviales.", "Cada capa habla con vecinas mediante contratos; reglas del dominio no dependen de frameworks.", "text", `UI → Application → Domain\n               ↑\n        Infrastructure adapters`, ["dirección de dependencias importa más que carpetas.", "adapters conectan detalles externos."], "Puedes explicar responsabilidades y evitar lógica de negocio en controllers/UI."),
  contracts: C("contracts", "Contratos", "Un contrato especifica entradas, salidas, invariantes, errores y garantías de una interfaz.", "Permite que equipos/componentes evolucionen sin depender de detalles internos.", "Úsalo en APIs, módulos, eventos, servicios y librerías.", "Consumidor programa contra una promesa estable, no contra implementación.", "text", `pre: amount > 0\npost: balance' = balance + amount\nerrors: AccountClosed`, ["precondición define requisitos.", "postcondición define efecto.", "errores forman parte de la API."], "Puedes escribir contratos verificables y versionarlos de forma compatible."),
  messaging: C("messaging", "Mensajería", "Mensajería intercambia comandos/eventos mediante brokers o canales en lugar de llamada directa.", "Desacopla tiempos de vida y permite buffering/reintentos.", "Úsala cuando productores y consumidores no deban estar disponibles simultáneamente.", "Mensaje entra a canal; consumidor lo procesa y confirma.", "text", `producer → topic/queue → consumer\n                    ↘ retry / DLQ`, ["la entrega puede repetirse.", "orden y garantía dependen del sistema.", "idempotencia suele ser importante."], "Puedes definir semántica de entrega, orden, retry y claves de idempotencia."),
  enterprise_testing: C("enterprise-testing", "Testing mantenible", "Testing mantenible prueba contratos y comportamiento con una estrategia por riesgo.", "Suites frágiles frenan cambios; suites pobres no protegen.", "Diseña tests junto con arquitectura y contratos.", "Prueba lógica pura cerca; integración donde hay fronteras; end-to-end solo caminos críticos.", "text", `unit → service integration → contract → e2e`, ["cada capa tiene coste distinto.", "mocks no deben reemplazar todo el sistema."], "Puedes construir pirámide/diamante de tests adecuada al producto."),
  maintainability: C("maintainability", "Mantenibilidad", "Mantenibilidad es la facilidad con la que un sistema puede entenderse, modificarse, probarse y operar sin introducir fallos.", "La mayor parte del coste de software ocurre después de la primera versión.", "Optimízala en sistemas que vivirán y cambiarán: claridad, modularidad, tests, docs, observabilidad.", "Código mantenible reduce la cantidad de contexto que necesitas cargar para hacer un cambio seguro.", "text", `nombres claros + contratos + módulos cohesionados + tests + docs + observabilidad`, ["no existe una métrica única.", "simplicidad y feedback rápido son indicadores prácticos."], "Puedes explicar cómo una decisión afecta coste futuro de cambio."),

  Android: C("android", "Android", "Android es una plataforma móvil con ciclo de vida de componentes, UI, permisos, almacenamiento y APIs de dispositivo.", "Permite construir aplicaciones para un ecosistema amplio de dispositivos y factores de forma.", "Úsalo para experiencias nativas Android o cuando necesites integración profunda del sistema.", "La app no controla completamente su proceso: el sistema crea/pausa/destruye componentes según recursos y navegación.", "text", `UI state ↔ ViewModel\nrepository ↔ network/database\nOS lifecycle + permissions`, ["estado debe sobrevivir recomposición/ciclo cuando corresponda.", "I/O suele estar fuera del hilo principal."], "Puedes diseñar flujo de estado, navegación, permisos y persistencia sin fugas de ciclo de vida."),
  iOS: C("ios", "iOS", "iOS es la plataforma móvil de Apple con APIs nativas, ciclo de vida, permisos y distribución propias.", "Permite experiencias optimizadas para dispositivos Apple.", "Úsalo para aplicaciones nativas Apple o integraciones específicas del ecosistema.", "Vista declarativa/imperativa refleja estado; el sistema administra ciclo y recursos.", "text", `App state → View → user action → state update\nservices → persistence/network`, ["separa estado/UI de efectos.", "respeta permisos y ciclo."], "Puedes diseñar estado, navegación, persistencia y testing en entorno móvil."),
  Flutter: C("flutter", "Flutter", "Flutter es un toolkit multiplataforma basado en Dart que renderiza su propia UI a partir de widgets.", "Permite compartir gran parte del código entre plataformas con una interfaz consistente.", "Úsalo cuando el producto valore base compartida y el acceso nativo requerido pueda cubrirse con plugins/canales.", "UI es árbol de widgets derivado del estado.", "text", `state → build() → widget tree\nuser event → set/update state → rebuild`, ["build describe UI actual.", "rebuild recalcula widgets según estado."], "Puedes decidir qué estado es local/global y separar lógica de widgets."),
  offline: C("offline", "Offline-first", "Offline-first diseña la app para seguir siendo útil sin red y sincronizar después.", "Las redes móviles son lentas, intermitentes o inexistentes.", "Úsalo cuando tareas importantes no deban depender de conectividad continua.", "Local es fuente operativa inmediata; sincronización reconcilia con servidor cuando vuelve conexión.", "text", `user action → local DB → UI immediate\n             ↘ sync queue → server later`, ["cambio local se confirma al usuario.", "cola registra pendientes.", "conflictos requieren política."], "Puedes definir sincronización, conflictos, retries e idempotencia."),
  sensors: C("sensors", "Sensores", "Sensores exponen mediciones del dispositivo como ubicación, movimiento, cámara o biometría.", "Permiten experiencias contextuales, pero añaden permisos, ruido y privacidad.", "Úsalos solo cuando aporten valor funcional claro y con consentimiento apropiado.", "Sensor produce muestras imperfectas → filtrar/interpretar → acción.", "text", `permission → subscribe → samples → filter → UI/action → unsubscribe`, ["solicitar permiso cuando sea necesario.", "cancelar suscripción evita consumo/fugas."], "Puedes manejar permisos, frecuencia, errores y privacidad."),
  "mobile testing": C("mobiletesting", "Testing móvil", "Testing móvil verifica lógica, UI, integración, dispositivos y condiciones reales como red lenta, rotación o suspensión.", "Los fallos móviles dependen mucho de ciclo, recursos y variedad de dispositivos.", "Úsalo desde unit tests hasta pruebas en emuladores/dispositivos de flujos críticos.", "Prueba no solo pantalla feliz: cambia orientación, mata proceso, pierde red, cambia permisos.", "text", `unit + widget/UI + integration + device matrix + network/lifecycle cases`, ["cada nivel reduce un riesgo diferente."], "Puedes definir matriz mínima de dispositivos/estados y automatizar caminos críticos."),

  containers: C("containers", "Contenedores", "Un contenedor empaqueta proceso y dependencias con aislamiento del sistema operativo compartido.", "Hace entornos reproducibles y despliegues consistentes.", "Úsalo para servicios y tooling que necesitan packaging uniforme; no es una VM completa.", "Imagen es plantilla inmutable; contenedor es una instancia de proceso basada en esa imagen.", "text", `Dockerfile → image → container\nconfig/secrets mounted at runtime`, ["build crea imagen.", "run crea proceso aislado.", "datos persistentes deben externalizarse."], "Puedes construir imagen mínima, no-root y reproducible y explicar capas."),
  "CI/CD": C("cicd", "CI/CD", "CI valida continuamente; CD prepara o automatiza entrega segura a entornos.", "Reduce pasos manuales y hace releases repetibles y auditables.", "Úsalo en equipos/productos con cambios frecuentes y pruebas automatizables.", "Commit → checks → artifact inmutable → despliegue → verificación → rollback si falla.", "text", `lint → test → build → scan → deploy staging → smoke → production`, ["artefacto debe promoverse, no reconstruirse distinto.", "rollback necesita estrategia previa."], "Puedes diseñar pipeline con gates, secretos, artefactos y rollback."),
  IaC: C("iac", "Infrastructure as Code", "IaC describe infraestructura mediante archivos versionables y herramientas declarativas/imperativas.", "Hace cambios revisables, reproducibles y automatizables.", "Úsalo cuando infraestructura sea parte estable del producto y deba repetirse entre entornos.", "Estado deseado versionado → plan de diferencias → aplicar cambios.", "text", `desired: 3 instances + network + database\nplan → review → apply`, ["el plan muestra impacto.", "estado y secretos requieren manejo seguro."], "Puedes hacer cambio reproducible, revisar drift y separar secretos."),
  SRE: C("sre", "SRE", "Site Reliability Engineering aplica ingeniería de software a confiabilidad y operación mediante objetivos y automatización.", "Evita operar solo reaccionando a incidentes y conecta confiabilidad con prioridades de negocio.", "Úsalo en servicios donde disponibilidad/latencia sean requisitos medibles.", "SLI mide; SLO fija objetivo; error budget permite balancear cambios y confiabilidad.", "text", `SLI availability = good requests / total\nSLO = 99.9%\nerror budget = 0.1%`, ["SLI debe reflejar experiencia del usuario.", "SLO no debe ser 100% por defecto."], "Puedes definir SLI/SLO, alertas accionables y postmortems."),
  observability2: C("observability2", "Observabilidad operativa", "Logs, métricas, trazas, perfiles y eventos permiten comprender sistemas en producción.", "Los fallos distribuidos atraviesan múltiples componentes.", "Instrumenta operaciones críticas, fronteras y dependencias.", "Una petición lleva un trace id que conecta lo ocurrido en cada servicio.", "text", `traceId=abc gateway 120ms → api 90ms → db 70ms`, ["trace distribuye causalidad temporal.", "métricas alertan tendencias.", "logs explican eventos concretos."], "Puedes responder 'qué falló, dónde, desde cuándo y a quién afecta'."),
  AppSec: C("appsec", "Application Security", "AppSec integra amenazas y controles de seguridad durante diseño, implementación, prueba y despliegue.", "Corregir vulnerabilidades temprano reduce riesgo y coste.", "Aplícalo transversalmente: autenticación, inputs, secretos, dependencias, permisos y supply chain.", "Modelo de amenaza → superficie → controles → verificación → monitoreo.", "text", `validate input\nauthorize server-side\nleast privilege\nsecrets outside code\ndependency scanning`, ["validación no sustituye autorización.", "defensa en profundidad evita depender de un solo control."], "Puedes modelar amenazas y demostrar controles verificables."),

  lexer: C("lexer", "Lexer / scanner", "Un lexer transforma caracteres en tokens con categorías como identificador, número u operador.", "Separa detalles del texto del análisis sintáctico.", "Úsalo en compiladores, intérpretes, DSLs y herramientas de análisis.", "Texto continuo → pequeñas fichas etiquetadas.", "javascript", `const src="x = 12 + 3";\nconst tokens=src.match(/[A-Za-z_]+|\\d+|\\S/g);\nconsole.log(tokens);`, ["regex identifica grupos léxicos simples.", "un lexer real registra tipo y posición."], "Puedes definir tokens, whitespace, errores y posiciones de fuente."),
  parser: C("parser", "Parser", "Un parser convierte tokens en una estructura sintáctica según una gramática.", "Permite reconocer precedencia, agrupación y estructura del lenguaje.", "Úsalo después del lexer en compiladores/DSLs o para formatos estructurados.", "Tokens son palabras; parser construye la oración estructurada.", "text", `expr → term ((+|-) term)*\nterm → factor ((*|/) factor)*`, ["la gramática define formas válidas.", "precedencia aparece en niveles de reglas."], "Puedes construir parser simple y producir errores con posición útil."),
  AST: C("ast", "AST", "Un AST es un árbol que representa la estructura esencial del código omitiendo detalles sintácticos innecesarios.", "Sirve como modelo común para análisis, optimización y generación/ejecución.", "Úsalo después del parsing en compiladores, linters y transformadores.", "Expresión 1+2*3 se vuelve árbol donde * queda debajo de + según precedencia.", "text", `Add(\n  Number(1),\n  Multiply(Number(2), Number(3))\n)`, ["cada nodo representa una construcción semántica.", "la forma refleja precedencia."], "Puedes recorrer AST y separar sintaxis concreta de significado."),
  "types-lang": C("types-lang", "Sistemas de tipos", "Un sistema de tipos clasifica valores/expresiones y define reglas de compatibilidad.", "Previene operaciones inválidas, documenta intención y habilita optimizaciones/herramientas.", "Diseñalo según objetivos del lenguaje: estático/dinámico, inferencia, subtipado, polimorfismo.", "Juicios de tipo comprueban si una expresión es válida bajo un entorno.", "text", `Γ ⊢ 1 : Int\nΓ,x:Int ⊢ x+1 : Int`, ["Γ representa entorno de nombres/tipos.", "la regla produce tipo de expresión."], "Puedes explicar qué errores detecta el sistema y qué expresividad permite."),
  bytecode: C("bytecode", "Bytecode", "Bytecode es una representación intermedia compacta para una máquina virtual.", "Separa lenguaje fuente de hardware y simplifica interpretación/JIT.", "Úsalo en runtimes cuando quieras portabilidad y ejecución más eficiente que AST directo.", "Compilador traduce AST a instrucciones de una VM abstracta.", "text", `CONST 2\nCONST 3\nMUL\nPRINT`, ["cada opcode es una operación de VM.", "la VM mantiene stack/registros."], "Puedes diseñar un conjunto mínimo de opcodes y ejecutar un programa pequeño."),
  runtime: C("runtime", "Runtime", "El runtime es la infraestructura que ejecuta programas: memoria, objetos, llamadas, excepciones, GC, scheduler o VM según el lenguaje.", "Explica comportamientos que no están escritos explícitamente en el código fuente.", "Estúdialo al implementar lenguajes, depurar performance o interoperabilidad.", "Código fuente depende de una máquina de ejecución con reglas de representación y ciclo de vida.", "text", `source → compiler/interpreter → runtime\nheap + stack + GC + native calls`, ["runtime administra servicios del lenguaje.", "distintos lenguajes delegan responsabilidades diferentes."], "Puedes seguir una función desde fuente hasta representación y ejecución."),

  architecture: C("architecture", "Arquitectura de software", "Arquitectura son decisiones estructurales de alto impacto: componentes, límites, comunicación, datos y cualidades.", "Condiciona escalabilidad, seguridad, rendimiento y capacidad de cambio.", "Diseñala según fuerzas concretas; no copies microservicios o patrones por moda.", "Primero atributos de calidad y restricciones; después estructura que los satisfaga con trade-offs explícitos.", "text", `drivers → options → trade-offs → decision (ADR) → validate`, ["drivers son requisitos importantes.", "ADR registra contexto y consecuencias."], "Puedes justificar una arquitectura con escenarios de calidad y alternativas descartadas."),
  performance2: C("performance2", "Ingeniería de rendimiento", "Es el proceso de medir, modelar y mejorar latencia, throughput, CPU, memoria e I/O.", "Los sistemas reales tienen cuellos que no se resuelven con intuición.", "Aplica cuando existe objetivo medible y una carga representativa.", "Baseline → benchmark → profile → hypothesis → change → benchmark.", "text", `p50 / p95 / p99 latency\nrequests/s\nCPU / memory / IO\nflamegraph`, ["percentiles muestran cola de latencia.", "throughput y latency interactúan bajo carga."], "Puedes diseñar benchmark reproducible y demostrar mejora sin degradar corrección."),
  security: C("security", "Seguridad de software", "Seguridad protege confidencialidad, integridad y disponibilidad ante amenazas dentro de un modelo explícito.", "El software expuesto recibe entradas y actores no confiables.", "Inclúyela en diseño, código, dependencias, despliegue y operación.", "Activos + atacantes + superficies + controles + evidencia.", "text", `threat model → validation/authz → least privilege → secure defaults → monitoring`, ["control debe corresponder a amenaza.", "seguridad absoluta no existe; se gestiona riesgo."], "Puedes identificar activos, amenazas, trust boundaries y controles verificables."),
  OSS: C("oss", "Open Source", "Open source combina código con una licencia que concede permisos y condiciones explícitas de uso/modificación/distribución.", "Enseña colaboración real, revisión, issues, documentación y gobernanza.", "Contribuye cuando puedes entender alcance, licencia y normas del proyecto.", "Issue → discusión → branch → cambios + tests → PR → review → merge/release.", "text", `README + LICENSE + CONTRIBUTING + issue tracker + CI`, ["licencia define permisos legales.", "contribuir implica seguir convenciones y revisión."], "Puedes realizar una contribución pequeña siguiendo licencia, tests y revisión."),
  ADRs: C("adrs", "ADRs", "Architecture Decision Records documentan una decisión importante, contexto, alternativas y consecuencias.", "Evitan perder el porqué histórico y ayudan a futuros cambios.", "Úsalos para decisiones costosas de revertir o que afectan múltiples equipos/componentes.", "Una decisión es una hipótesis registrada con contexto y trade-offs, no una verdad eterna.", "text", `ADR-012 Use PostgreSQL\nContext\nDecision\nAlternatives\nConsequences\nStatus`, ["context explica fuerzas.", "consequences incluye costes.", "status permite superseder decisiones."], "Puedes escribir ADR breve con alternativas reales y consecuencias."),
  benchmarks: C("benchmarks", "Benchmarks", "Un benchmark mide rendimiento bajo un escenario reproducible.", "Permite comparar cambios con datos y detectar regresiones.", "Úsalo para operaciones críticas después de definir qué métrica importa.", "Fija entorno/carga, repite mediciones y compara distribuciones, no un número aislado.", "javascript", `const samples=[];\nfor(let i=0;i<100;i++){\n  const t=performance.now();\n  // operación\n  samples.push(performance.now()-t);\n}\nconsole.log(samples.length);`, ["repetición reduce ruido relativo.", "un benchmark serio controla warmup, entorno y variabilidad."], "Puedes producir baseline, percentiles y reporte de metodología."),
}

const levelSpecs = [
  ["L00","Cómo piensa un programa","Cero absoluto","Empieza sin asumir que sabes qué es código. Primero entenderás instrucciones, datos, decisiones y trazas.",["ninguno"],["Explicar un algoritmo cotidiano.","Predecir un programa corto.","Distinguir dato, estado e instrucción."],["secuencias","variables","booleanos","diagramas","trazas","errores"],"Simulador visual de instrucciones y decisiones.","Explicar un algoritmo sin código y predecir su salida.",["cs50","stanford106","htdp"]],
  ["L01","Python desde cero","Fundamentos","Ahora traduces el razonamiento a un lenguaje textual sencillo y aprendes los bloques universales de casi todo lenguaje.",["L00"],["Modelar datos con tipos.","Controlar flujo con decisiones y bucles.","Descomponer con funciones y colecciones."],["tipos","if","for/while","funciones","listas","diccionarios"],"Juego de texto con inventario y decisiones.","Resolver ejercicios nuevos sin copiar.",["cs50","stanford106","ossu"]],
  ["L02","Pensamiento algorítmico","Fundamentos","Aprenderás a razonar sobre corrección, casos límite, pruebas, recursión y coste antes de perseguir sintaxis.",["L01"],["Depurar con evidencia.","Diseñar pruebas.","Razonar sobre terminación y coste."],["trazas","debug","tests","edge cases","recursión","complejidad inicial"],"Motor de retos con casos de prueba.","Detectar y corregir errores deliberados.",["htdp","cs61a","mit6031"]],
  ["L03","JavaScript y el modelo de ejecución","Lenguaje","Cambias de lenguaje para demostrar que los conceptos transfieren y profundizas en scope, closures y asincronía.",["L02"],["Explicar scope/closure.","Razonar sobre Promises/event loop.","Organizar código en módulos."],["scope","closures","promises","async/await","módulos","event loop"],"Aplicación interactiva sin framework.","Explicar sincronía vs asincronía y depurar una carrera simple.",["cs61a","mit6031","fcc"]],
  ["L04","Estructuras de datos I","CS núcleo","Aprenderás cómo organizar datos cambia el coste de cada operación.",["L02"],["Implementar estructuras básicas.","Comparar costes.","Elegir estructura por patrón de uso."],["arrays","linked lists","stack","queue","hash","Big-O"],"Biblioteca de estructuras con tests y benchmarks.","Elegir estructura por coste y justificarla.",["ods","cs2023"]],
  ["L05","Algoritmos I","CS núcleo","Pasas de estructuras a estrategias generales para buscar, ordenar y reducir trabajo.",["L04"],["Implementar búsquedas/ordenamientos.","Reconocer patrones.","Analizar tiempo y espacio."],["binary search","sorting","two pointers","window","divide & conquer","greedy"],"Visualizador de algoritmos y comparador de rendimiento.","Resolver problemas con análisis temporal/espacial.",["ods","cs2023","cs50"]],
  ["L06","Árboles, grafos y algoritmos II","CS núcleo","Trabajas con relaciones no lineales y técnicas de exploración/optimización más potentes.",["L05"],["Modelar árboles/grafos.","Aplicar BFS/DFS/Dijkstra.","Formular DP."],["trees","heaps","graphs","BFS/DFS","Dijkstra","DP"],"Motor de rutas y dependencias.","Resolver un problema nuevo de grafos justificando algoritmo.",["ods","cs61a","cs2023"]],
  ["L07","Paradigmas y diseño de software","Diseño","Ya sabes resolver problemas; ahora aprenderás a estructurar soluciones para que sobrevivan cambios.",["L06"],["Comparar OOP/FP.","Diseñar límites.","Refactorizar con pruebas."],["OOP","FP","SOLID","patterns","DDD básico","refactor"],"Aplicación modular con dominio y adaptadores.","Defender decisiones de diseño y refactor con tests.",["mit6031","swebok","sicp"]],
  ["L08","Web desde los fundamentos","Plataforma","Construyes web entendiendo primero el protocolo, documento y navegador, no solo frameworks.",["L03","L07"],["Explicar HTTP.","Construir HTML/CSS accesible.","Manipular DOM y responsive."],["HTTP","semantic HTML","CSS","DOM","a11y","responsive"],"Sitio web accesible, responsive e interactivo.","Auditar semántica, teclado, responsive y red.",["fcc","odin","fso"]],
  ["L09","TypeScript y frontend moderno","Frontend","Introduces tipos y arquitectura de UI para manejar aplicaciones complejas con estado y pruebas.",["L08"],["Modelar tipos.","Diseñar componentes/estado.","Medir calidad y performance."],["types","components","state","testing","performance","design systems"],"Aplicación frontend tipada con tests y design system mínimo.","Explicar flujo de estado y demostrar pruebas/performance.",["fso","mit6031","fcc"]],
  ["L10","Backend, APIs y autenticación","Backend","Construyes servicios que validan entradas, aplican reglas, protegen recursos y se observan en producción.",["L09"],["Diseñar APIs.","Separar authn/authz.","Modelar asincronía y observabilidad."],["REST","GraphQL","auth","queues","events","observability"],"API con autenticación, trabajo asíncrono y telemetría.","Probar contratos, permisos, reintentos y fallos.",["fso","swebok","mit6031"]],
  ["L11","SQL, modelado y persistencia","Datos","Aprendes a modelar hechos, consultar eficientemente y proteger consistencia bajo concurrencia.",["L10"],["Normalizar y consultar.","Diseñar índices/transacciones.","Comparar NoSQL/cache."],["normalization","SQL","indexes","transactions","NoSQL","cache"],"Servicio con esquema relacional, migraciones e índices medidos.","Justificar modelo, consultas, aislamiento e índices.",["cs50","fso","swebok"]],
  ["L12","Git, Linux y herramientas","Tooling","La programación profesional incluye dominar el entorno, versiones, diagnóstico y automatización.",["L03"],["Componer shell.","Entender procesos/Git.","Debuggear, perfilar y automatizar CI."],["shell","processes","git","debugging","profiling","CI"],"Pipeline reproducible con Git, tests, build y perfilado.","Recuperar un bug y una regresión desde herramientas, no intuición.",["missing","mit6031"]],
  ["L13","C, memoria y sistemas operativos","Sistemas","Bajas al nivel donde se entienden memoria, punteros, procesos, hilos, archivos y sockets.",["L04","L12"],["Dibujar memoria.","Razonar sobre procesos/hilos.","Usar archivos/sockets de bajo nivel."],["memory","pointers","processes_os","threads","filesystems","sockets"],"Herramienta de sistemas cliente/servidor con manejo de memoria.","Explicar memoria, ciclo de vida y concurrencia sin abstracciones mágicas.",["ostep","nand2tetris","cs50"]],
  ["L14","Redes, concurrencia y distribuidos","Sistemas avanzados","Asumes que hay latencia, concurrencia y fallos; aprendes garantías en vez de esperar un mundo perfecto.",["L13"],["Explicar TCP/concurrencia.","Evitar carreras.","Diseñar consistencia/replicación/fallos."],["TCP","concurrency","locks","consistency","replication","fault tolerance"],"Servicio distribuido simulado con reintentos, réplicas y fallos.","Explicar garantías y trade-offs bajo particiones/fallos.",["ostep","mit6031","cs2023"]],
  ["L15","Java/Kotlin y .NET a escala","Ecosistemas","Estudias patrones de sistemas empresariales duraderos: inyección, capas, contratos, mensajería y mantenibilidad.",["L07","L10"],["Diseñar dependencias/layers.","Versionar contratos.","Construir tests mantenibles."],["DI","layers","contracts","messaging","enterprise_testing","maintainability"],"Servicio empresarial modular con contratos y mensajería.","Modificar requisito sin propagar cambios innecesarios.",["swebok","mit6031"]],
  ["L16","Móvil y multiplataforma","Plataformas","Aplicas fundamentos a dispositivos con ciclo de vida, recursos, sensores y redes intermitentes.",["L09","L10"],["Comparar plataformas.","Diseñar offline-first.","Probar ciclo/permiso/dispositivo."],["Android","iOS","Flutter","offline","sensors","mobile testing"],"Aplicación móvil offline-first con sincronización y sensor opcional.","Demostrar recuperación de proceso/red y manejo de permisos.",["cs2023","swebok"]],
  ["L17","Cloud, DevOps, SRE y AppSec","Operación","El software no termina al compilar: debes empaquetar, desplegar, observar, asegurar y operar.",["L10","L12","L14"],["Contenerizar/desplegar.","Automatizar infraestructura.","Definir SLO y seguridad."],["containers","CI/CD","IaC","SRE","observability2","AppSec"],"Servicio desplegable con pipeline, IaC, observabilidad y threat model.","Operar incidente simulado con métricas y rollback.",["missing","swebok","cs2023"]],
  ["L18","Compiladores, runtimes y lenguajes","Lenguajes","Construyes las capas que convierten texto en ejecución y comprendes tipos, bytecode y runtime.",["L06","L13"],["Implementar lexer/parser/AST.","Razonar tipos.","Ejecutar bytecode en una VM."],["lexer","parser","AST","types-lang","bytecode","runtime"],"Intérprete/VM de un lenguaje pequeño.","Añadir una característica al lenguaje sin romper tests.",["crafting","nand2tetris","cs61a"]],
  ["L19","Arquitectura, rendimiento y capstone","Maestría","Cierras integrando decisiones, performance, seguridad, open source y evidencia técnica de extremo a extremo.",["L00-L18"],["Diseñar arquitectura con trade-offs.","Medir rendimiento/seguridad.","Documentar y defender decisiones."],["architecture","performance2","security","OSS","ADRs","benchmarks"],"Capstone completo: requisitos, arquitectura, implementación, pruebas, despliegue, operación, documentación y defensa.","Defender el sistema frente a revisión técnica y demostrar evidencia reproducible.",["swebok","cs2023","buildx","ossu"]],
] as const

export const guidedProgrammingLevelsV50: GuidedLevelV50[] = levelSpecs.map(([code,title,phase,orientation,prerequisites,outcomes,conceptIds,project,gate,sources]) => ({
  code,
  title,
  phase,
  orientation,
  prerequisites: [...prerequisites],
  outcomes: [...outcomes],
  concepts: [...conceptIds].map((id) => concepts[id]).filter(Boolean),
  project,
  gate,
  sources: [...sources],
}))

export const getGuidedLevelV50 = (code: string) => guidedProgrammingLevelsV50.find((level) => level.code === code) ?? guidedProgrammingLevelsV50[0]
export const getSourceV50 = (id: string) => programmingSourcesV50.find((source) => source.id === id)
