// Generated from the user-provided career/profession scope list. Search index only; durable curriculum is normalized into macrodomains.
export const careerCatalogV43 = [
  "Ingeniería Informática",
  "Informática",
  "Ciencias de la Computación",
  "Ciencia de la Computación",
  "Computer Science",
  "Computación",
  "Ciencias Computacionales",
  "Ciencias Informáticas",
  "Computación e Informática",
  "Ingeniería de Computación",
  "Ingeniería en Computación",
  "Ingeniería de Computadores",
  "Ingeniería de Computadoras",
  "Computer Engineering",
  "Ingeniería Computacional",
  "Ingeniería de Sistemas",
  "Ingeniería de Sistemas e Informática",
  "Ingeniería de Sistemas y Computación",
  "Ingeniería Informática y de Sistemas",
  "Ingeniería de Sistemas Computacionales",
  "Ingeniería de Sistemas de Información",
  "Sistemas de Información",
  "Information Systems",
  "Sistemas Informáticos",
  "Sistemas Computacionales",
  "Tecnologías de la Información",
  "Tecnología de Información",
  "Information Technology",
  "Ingeniería de Tecnologías de Información",
  "Ingeniería TIC",
  "Tecnologías de Información y Comunicación",
  "Informática Empresarial",
  "Business Informatics",
  "Informática de Gestión",
  "Management Information Systems",
  "Computer Information Systems",
  "Business Information Systems",
  "Tecnología en Computación e Informática",
  "Técnico en Computación e Informática",
  "Tec. en Computación e Informática",
  "Tecnología Informática",
  "Tecnología de Computación",
  "Computer Technology",
  "Applied Computing",
  "Computación Aplicada",
  "Applied Computer Science",
  "Information Science",
  "Ciencias de la Información",
  "Ingeniería Digital",
  "Tecnologías Digitales",
  "Digital Systems Engineering",
  "Computer and Information Sciences",
  "Computer and Information Technology",
  "Ingeniería de Telecomunicaciones",
  "Telecomunicaciones",
  "Telecommunications Engineering",
  "Ingeniería Telemática",
  "Telemática",
  "Ingeniería de Comunicaciones",
  "Communications Engineering",
  "Ingeniería de Redes y Telecomunicaciones",
  "Ingeniería Electrónica y Telecomunicaciones",
  "Ingeniería de Software",
  "Software Engineering",
  "Desarrollo de Software",
  "Software Development",
  "Tecnología en Desarrollo de Software",
  "Desarrollo de Sistemas",
  "Desarrollo de Aplicaciones",
  "Programación",
  "Computer Programming",
  "Programador",
  "Computer Programmer",
  "Analista Programador",
  "Programmer Analyst",
  "Programador de Sistemas",
  "Systems Programmer",
  "Programador de Aplicaciones",
  "Programador Científico",
  "Scientific Programmer",
  "Programador Matemático",
  "Programador Estadístico",
  "Statistical Programmer",
  "Programador Web",
  "Programador Frontend",
  "Programador Backend",
  "Programador Full Stack",
  "Full Stack",
  "Full-Stack Development",
  "Full Stack Developer",
  "Full Stack Engineer",
  "Desarrollo Web",
  "Web Development",
  "Ingeniería Web",
  "Web Engineering",
  "Web Computing",
  "Front-End Development",
  "Back-End Development",
  "Frontend Developer",
  "Frontend Engineer",
  "Backend Developer",
  "Backend Engineer",
  "Web Developer",
  "Web Application Developer",
  "Web Software Engineer",
  "Web Architect",
  "JavaScript Developer",
  "TypeScript Developer",
  "React Developer",
  "Angular Developer",
  "Vue Developer",
  "Svelte Developer",
  "Next.js Developer",
  "Node.js Developer",
  "PHP Developer",
  "Laravel Developer",
  "Django Developer",
  "Flask Developer",
  "Ruby on Rails Developer",
  "ASP.NET Developer",
  "Java Web Developer",
  "Spring Developer",
  "WordPress Developer",
  "Drupal Developer",
  "CMS Developer",
  "Headless CMS Developer",
  "E-Commerce Developer",
  "Shopify Developer",
  "WooCommerce Developer",
  "Progressive Web App Developer",
  "Web Accessibility Engineer",
  "Web Performance Engineer",
  "Web Security Engineer",
  "Webmaster",
  "Web Administrator",
  "Desarrollo Móvil",
  "Mobile Computing",
  "Mobile Application Development",
  "Ingeniería de Aplicaciones Móviles",
  "Mobile Software Engineering",
  "Mobile Developer",
  "Mobile Engineer",
  "Android Developer",
  "Android Engineer",
  "iOS Developer",
  "iOS Engineer",
  "Flutter Developer",
  "React Native Developer",
  "Kotlin Developer",
  "Kotlin Multiplatform Developer",
  "Swift Developer",
  "Mobile UI Engineer",
  "Mobile Backend Engineer",
  "Mobile Security Engineer",
  "Mobile QA Engineer",
  "Mobile DevOps Engineer",
  "Mobile Architect",
  "Wearable Application Developer",
  "Software Engineer",
  "Software Developer",
  "Application Developer",
  "Application Engineer",
  "Systems Developer",
  "Software Architect",
  "Application Architect",
  "Solutions Architect",
  "Software Design Engineer",
  "Product Engineer",
  "Platform Engineer",
  "Platform Software Engineer",
  "Integration Engineer",
  "Integration Developer",
  "Middleware Engineer",
  "API Engineer",
  "API Developer",
  "SDK Engineer",
  "Runtime Engineer",
  "Distributed Systems Engineer",
  "Concurrent Systems Engineer",
  "Performance Engineer",
  "Software Performance Engineer",
  "Reliability Engineer",
  "Software Reliability Engineer",
  "Software Maintenance Engineer",
  "Legacy Systems Engineer",
  "Software Modernization Engineer",
  "Migration Engineer",
  "Enterprise Software Engineer",
  "Enterprise Application Developer",
  "Automation Software Engineer",
  "Principal Software Engineer",
  "Staff Engineer",
  "Senior Staff Engineer",
  "Distinguished Engineer",
  "Technical Lead",
  "Lead Developer",
  "Software Engineering Manager",
  "Java Developer",
  "C Developer",
  "C++ Developer",
  "C# Developer",
  "NET Developer",
  "Python Developer",
  "Go Developer",
  "Rust Developer",
  "Ruby Developer",
  "Perl Developer",
  "Scala Developer",
  "R Developer",
  "MATLAB Developer",
  "Fortran Programmer",
  "COBOL Programmer",
  "Assembly Programmer",
  "Lisp Developer",
  "Functional Programmer",
  "Embedded Programmer",
  "Firmware Programmer",
  "Kernel Programmer",
  "Driver Developer",
  "Compiler Developer",
  "GPU Programmer",
  "CUDA Developer",
  "Parallel Programmer",
  "HPC Programmer",
  "Quantum Programmer",
  "Robotics Programmer",
  "PLC Programmer",
  "Database Programmer",
  "SQL Developer",
  "PL/SQL Developer",
  "Scripting Developer",
  "Automation Programmer",
  "Operating Systems Engineering",
  "Ingeniería de Sistemas Operativos",
  "Operating Systems Engineer",
  "Operating Systems Developer",
  "Kernel Developer",
  "Kernel Engineer",
  "Linux Kernel Developer",
  "Windows Systems Developer",
  "Unix Systems Developer",
  "Device Driver Developer",
  "Driver Engineer",
  "Firmware Developer",
  "Firmware Engineer",
  "BIOS Engineer",
  "UEFI Engineer",
  "Bootloader Engineer",
  "Embedded Runtime Engineer",
  "Memory Systems Engineer",
  "Memory Management Engineer",
  "File Systems Engineer",
  "Storage Systems Engineer",
  "Virtualization Engineer",
  "Hypervisor Engineer",
  "Container Runtime Engineer",
  "Compiler Engineer",
  "Linker Engineer",
  "Loader Engineer",
  "Toolchain Engineer",
  "Programming Language Engineer",
  "Language Runtime Engineer",
  "JIT Compiler Engineer",
  "Real-Time Systems Engineer",
  "Ciencias de la Computación Teórica",
  "Theoretical Computer Science",
  "Algorithmics",
  "Teoría de Algoritmos",
  "Algorithm Design",
  "Algorithm Engineering",
  "Teoría de la Computabilidad",
  "Computability Theory",
  "Complexity Theory",
  "Computational Complexity",
  "Teoría de Autómatas",
  "Automata Theory",
  "Lenguajes Formales",
  "Formal Languages",
  "Métodos Formales",
  "Formal Methods",
  "Formal Verification",
  "Verification Science",
  "Model Checking",
  "Type Theory",
  "Teoría de Tipos",
  "Programming Language Theory",
  "Semantics of Programming Languages",
  "Computational Logic",
  "Logic in Computer Science",
  "Algorithm Designer",
  "Algorithm Engineer",
  "Algorithms Researcher",
  "Complexity Theorist",
  "Formal Methods Engineer",
  "Formal Verification Engineer",
  "Proof Engineer",
  "Theorem Proving Researcher",
  "Programming Languages Researcher",
  "Compiler Researcher",
  "Arquitectura de Computadores",
  "Computer Architecture",
  "Ingeniería de Hardware",
  "Computer Hardware Engineering",
  "Ingeniería Electrónica Digital",
  "Microelectrónica",
  "Microelectronics",
  "Ingeniería de Semiconductores",
  "Semiconductor Engineering",
  "Microprocessor Engineering",
  "Processor Architecture",
  "Computer Hardware Engineer",
  "Hardware Engineer",
  "Hardware Architect",
  "CPU Architect",
  "GPU Architect",
  "NPU Architect",
  "AI Accelerator Architect",
  "Processor Architect",
  "Microprocessor Engineer",
  "Microarchitecture Engineer",
  "SoC Engineer",
  "System-on-Chip Architect",
  "ASIC Engineer",
  "FPGA Engineer",
  "FPGA Developer",
  "RTL Engineer",
  "RTL Designer",
  "Digital Design Engineer",
  "Logic Design Engineer",
  "VLSI Engineer",
  "IC Design Engineer",
  "Chip Design Engineer",
  "Semiconductor Engineer",
  "Silicon Engineer",
  "Silicon Validation Engineer",
  "Hardware Validation Engineer",
  "Hardware Verification Engineer",
  "Physical Design Engineer",
  "Electronic Design Automation Engineer",
  "EDA Software Engineer",
  "PCB Engineer",
  "PCB Designer",
  "Computer Hardware Technician",
  "Hardware Reliability Engineer",
  "Hardware Security Engineer",
  "Ingeniería de Redes",
  "Redes Informáticas",
  "Computer Networking",
  "Network Engineering",
  "Network Systems",
  "Redes y Comunicaciones",
  "Network Engineer",
  "Network Administrator",
  "Network Architect",
  "Network Analyst",
  "Network Specialist",
  "Network Technician",
  "Network Support Specialist",
  "Network Operations Engineer",
  "NOC Engineer",
  "NOC Analyst",
  "NOC Technician",
  "Network Automation Engineer",
  "Network Software Engineer",
  "Network Programmability Engineer",
  "Routing Engineer",
  "Switching Engineer",
  "LAN Engineer",
  "WAN Engineer",
  "WLAN Engineer",
  "Wi-Fi Engineer",
  "SDN Engineer",
  "SD-WAN Engineer",
  "Network Virtualization Engineer",
  "NFV Engineer",
  "Network Protocol Engineer",
  "Internet Protocol Engineer",
  "Network Performance Engineer",
  "Network Reliability Engineer",
  "Network Capacity Engineer",
  "Network Planning Engineer",
  "Network Security Engineer",
  "Telecommunications Engineer",
  "Telecommunications Engineering Specialist",
  "Telecom Network Engineer",
  "Telecom Systems Engineer",
  "Telecom Architect",
  "Telecommunications Technician",
  "Telecom Analyst",
  "Telecom Consultant",
  "Telecom Software Engineer",
  "Telecom Security Engineer",
  "Telecom Data Engineer",
  "Telecom Data Analyst",
  "Radio Engineer",
  "RF Engineer",
  "Radio Frequency Engineer",
  "RF Planning Engineer",
  "RF Optimization Engineer",
  "RF Design Engineer",
  "Antenna Engineer",
  "Radio Propagation Engineer",
  "Spectrum Engineer",
  "Spectrum Management Engineer",
  "Spectrum Analyst",
  "Wireless Engineer",
  "Wireless Network Engineer",
  "Cellular Network Engineer",
  "Mobile Network Engineer",
  "RAN Engineer",
  "RAN Architect",
  "RAN Optimization Engineer",
  "RAN Planning Engineer",
  "Open RAN Engineer",
  "vRAN Engineer",
  "Core Network Engineer",
  "Mobile Core Engineer",
  "Packet Core Engineer",
  "EPC Engineer",
  "IMS Engineer",
  "VoIP Engineer",
  "VoLTE Engineer",
  "VoNR Engineer",
  "Unified Communications Engineer",
  "Microwave Engineer",
  "Microwave Network Planner",
  "Fiber Optic Engineer",
  "Optical Network Engineer",
  "Optical Communications Engineer",
  "Fiber Network Planner",
  "Fiber Technician",
  "Fiber Splicing Technician",
  "Broadband Engineer",
  "Cable Network Engineer",
  "Satellite Communications Engineer",
  "Satellite Network Engineer",
  "Ground Station Engineer",
  "Space Communications Engineer",
  "NTN Engineer",
  "OSS Engineer",
  "BSS Engineer",
  "OSS/BSS Engineer",
  "OSS/BSS Architect",
  "Telecom Operations Engineer",
  "Telecommunications Reliability Engineer",
  "2G Engineer",
  "3G Engineer",
  "LTE Engineer",
  "4G Engineer",
  "5G Engineer",
  "5G Advanced Engineer",
  "6G Engineer",
  "6G Research Engineer",
  "Future Wireless Systems Researcher",
  "Internet de las Cosas",
  "IoT",
  "Internet of Things",
  "Ingeniería IoT",
  "IoT Engineering",
  "Embedded IoT Systems",
  "Industrial IoT",
  "IIoT",
  "Cyber-Physical Systems",
  "Sistemas Ciberfísicos",
  "Smart Systems",
  "Connected Systems",
  "IoT Engineer",
  "IoT Developer",
  "IoT Software Engineer",
  "IoT Hardware Engineer",
  "IoT Architect",
  "IoT Solutions Architect",
  "IoT Systems Engineer",
  "IoT Platform Engineer",
  "IoT Network Engineer",
  "IoT Connectivity Engineer",
  "IoT Cloud Engineer",
  "IoT Data Engineer",
  "IoT Analytics Engineer",
  "IoT Security Engineer",
  "IoT Firmware Engineer",
  "IoT Embedded Engineer",
  "IoT Device Engineer",
  "IoT Integration Engineer",
  "IoT Test Engineer",
  "IoT Product Engineer",
  "IoT Product Manager",
  "Industrial IoT Engineer",
  "Smart Home Engineer",
  "Smart Building Engineer",
  "Smart City Systems Engineer",
  "Connected Vehicle Engineer",
  "Connected Device Engineer",
  "Sensor Network Engineer",
  "Wireless Sensor Network Engineer",
  "Machine-to-Machine Engineer",
  "M2M Engineer",
  "Sistemas Embebidos",
  "Embedded Systems Engineering",
  "Embedded Software Engineer",
  "Embedded Hardware Engineer",
  "Embedded Firmware Engineer",
  "Embedded Linux Engineer",
  "Embedded C Developer",
  "Microcontroller Engineer",
  "RTOS Engineer",
  "Real-Time Embedded Systems Engineer",
  "Embedded Security Engineer",
  "Embedded AI Engineer",
  "Edge AI Engineer",
  "TinyML Engineer",
  "Sensor Systems Engineer",
  "Embedded Robotics Engineer",
  "Automotive Embedded Engineer",
  "Aerospace Embedded Engineer",
  "Medical Embedded Systems Engineer",
  "Distributed Computing",
  "Computación Distribuida",
  "Distributed Systems",
  "Edge Computing",
  "Computación en el Borde",
  "Fog Computing",
  "Cloud-Edge Computing",
  "Edge Computing Engineer",
  "Edge Architect",
  "Edge Infrastructure Engineer",
  "Edge Platform Engineer",
  "Fog Computing Engineer",
  "Distributed Storage Engineer",
  "Distributed Database Engineer",
  "Distributed Consensus Engineer",
  "Distributed Computing Researcher",
  "Cloud Computing",
  "Computación en la Nube",
  "Ingeniería Cloud",
  "Cloud Engineering",
  "Cloud Architecture",
  "Cloud Systems Engineering",
  "Cloud Engineer",
  "Cloud Architect",
  "Cloud Developer",
  "Cloud Administrator",
  "Cloud Consultant",
  "Cloud Infrastructure Engineer",
  "Cloud Platform Engineer",
  "Cloud Operations Engineer",
  "Cloud Network Engineer",
  "Cloud Security Engineer",
  "Cloud Security Architect",
  "Cloud Reliability Engineer",
  "Cloud Automation Engineer",
  "Cloud Migration Engineer",
  "Cloud Integration Engineer",
  "Cloud Native Engineer",
  "Cloud Solutions Architect",
  "Multi-Cloud Architect",
  "Hybrid Cloud Architect",
  "Serverless Engineer",
  "Kubernetes Engineer",
  "Container Platform Engineer",
  "Cloud Governance Specialist",
  "Cloud FinOps Engineer",
  "Cloud Cost Analyst",
  "DevOps",
  "DevOps Engineering",
  "DevOps Engineer",
  "DevOps Architect",
  "DevOps Developer",
  "DevOps Consultant",
  "DevSecOps",
  "DevSecOps Engineer",
  "DevSecOps Architect",
  "Site Reliability Engineering",
  "Site Reliability Engineer",
  "SRE",
  "Platform Engineering",
  "Platform Architect",
  "Production Engineer",
  "Production Reliability Engineer",
  "Release Engineer",
  "Build Engineer",
  "CI/CD Engineer",
  "Infrastructure Automation Engineer",
  "Infrastructure-as-Code Engineer",
  "Configuration Management Engineer",
  "Observability Engineer",
  "Monitoring Engineer",
  "Chaos Engineer",
  "Developer Productivity Engineer",
  "Developer Experience Engineer",
  "Internal Developer Platform Engineer",
  "System Administrator",
  "Sysadmin",
  "Linux Administrator",
  "Unix Administrator",
  "Windows Administrator",
  "Server Administrator",
  "Infrastructure Administrator",
  "Infrastructure Engineer",
  "Systems Operations Engineer",
  "IT Operations Engineer",
  "Data Center Engineer",
  "Data Center Technician",
  "Data Center Administrator",
  "Storage Administrator",
  "Storage Engineer",
  "Backup Administrator",
  "Backup Engineer",
  "Disaster Recovery Specialist",
  "Business Continuity Engineer",
  "VMware Administrator",
  "Hyper-V Administrator",
  "Container Administrator",
  "Kubernetes Administrator",
  "Endpoint Administrator",
  "Endpoint Engineer",
  "Desktop Engineer",
  "Active Directory Administrator",
  "Directory Services Engineer",
  "Identity Administrator",
  "MDM Administrator",
  "Microsoft 365 Administrator",
  "Collaboration Engineer",
  "Messaging Administrator",
  "Técnico Informático",
  "Técnico en Computación",
  "Computer Technician",
  "PC Technician",
  "IT Technician",
  "IT Support Technician",
  "Help Desk Technician",
  "Service Desk Analyst",
  "Service Desk Technician",
  "Help Desk Analyst",
  "Desktop Support Technician",
  "Desktop Support Engineer",
  "Field Support Technician",
  "Field Service Engineer",
  "Technical Support Specialist",
  "Technical Support Engineer",
  "Application Support Engineer",
  "Production Support Engineer",
  "Software Support Engineer",
  "Hardware Support Engineer",
  "Network Support Engineer",
  "IT Support Engineer",
  "End User Computing Engineer",
  "EUC Engineer",
  "Remote Support Technician",
  "Computer Repair Technician",
  "Laptop Repair Technician",
  "Mobile Device Technician",
  "Electronics Repair Technician",
  "Administración de Bases de Datos",
  "Database Administration",
  "Database Engineering",
  "Database Systems",
  "Database Architecture",
  "Database Administrator",
  "DBA",
  "Database Engineer",
  "Database Developer",
  "Database Architect",
  "Database Analyst",
  "NoSQL Engineer",
  "Graph Database Engineer",
  "Database Reliability Engineer",
  "Database Performance Engineer",
  "Database Security Engineer",
  "Database Migration Engineer",
  "Database Cloud Engineer",
  "In-Memory Database Engineer",
  "Ingeniería de Datos",
  "Data Engineering",
  "Big Data Engineering",
  "Data Infrastructure",
  "Data Engineer",
  "Senior Data Engineer",
  "Big Data Engineer",
  "Data Platform Engineer",
  "Data Infrastructure Engineer",
  "Data Pipeline Engineer",
  "ETL Developer",
  "ETL Engineer",
  "ELT Engineer",
  "Data Integration Engineer",
  "Streaming Data Engineer",
  "Real-Time Data Engineer",
  "DataOps Engineer",
  "Data Reliability Engineer",
  "Data Architect",
  "Enterprise Data Architect",
  "Lakehouse Engineer",
  "Data Lake Engineer",
  "Data Warehouse Engineer",
  "Data Warehouse Developer",
  "Data Warehouse Architect",
  "Análisis de Datos",
  "Data Analytics",
  "Analytics",
  "Business Analytics",
  "Quantitative Analytics",
  "Data Analyst",
  "Senior Data Analyst",
  "Junior Data Analyst",
  "Business Data Analyst",
  "Business Analyst",
  "Analytics Analyst",
  "Digital Analyst",
  "Product Analyst",
  "Operations Analyst",
  "Marketing Data Analyst",
  "Customer Data Analyst",
  "Financial Data Analyst",
  "Risk Data Analyst",
  "Healthcare Data Analyst",
  "Sports Data Analyst",
  "Web Analyst",
  "Statistical Analyst",
  "Quantitative Analyst",
  "Decision Analyst",
  "Decision Scientist",
  "Reporting Analyst",
  "Dashboard Analyst",
  "Ciencia de Datos",
  "Data Science",
  "Computational Data Science",
  "Applied Data Science",
  "Statistical Data Science",
  "Data Scientist",
  "Applied Data Scientist",
  "Research Data Scientist",
  "Principal Data Scientist",
  "Computational Scientist",
  "Statistical Scientist",
  "Quantitative Scientist",
  "Data Science Researcher",
  "Business Intelligence",
  "Inteligencia de Negocios",
  "BI Analyst",
  "BI Developer",
  "BI Engineer",
  "BI Architect",
  "Business Intelligence Consultant",
  "Reporting Developer",
  "Reporting Engineer",
  "Dashboard Developer",
  "Power BI Developer",
  "Power BI Consultant",
  "Tableau Developer",
  "Analytics Engineer",
  "Semantic Model Engineer",
  "OLAP Developer",
  "Decision Intelligence",
  "Decision Intelligence Engineer",
  "Data Governance",
  "Data Management",
  "Master Data Management",
  "Data Quality Management",
  "Data Governance Analyst",
  "Data Governance Specialist",
  "Data Governance Manager",
  "Data Steward",
  "Chief Data Steward",
  "Data Quality Analyst",
  "Data Quality Engineer",
  "Master Data Specialist",
  "MDM Engineer",
  "Metadata Specialist",
  "Metadata Engineer",
  "Data Catalog Engineer",
  "Data Lineage Engineer",
  "Data Compliance Analyst",
  "Data Privacy Engineer",
  "Inteligencia Artificial",
  "Ingeniería en Inteligencia Artificial",
  "Ingeniería de Inteligencia Artificial",
  "Artificial Intelligence Engineering",
  "Artificial Intelligence",
  "Intelligent Systems",
  "Computational Intelligence",
  "Intelligent Computing",
  "Cognitive Computing",
  "Applied Artificial Intelligence",
  "AI Engineer",
  "Artificial Intelligence Engineer",
  "AI Developer",
  "AI Software Engineer",
  "AI Systems Engineer",
  "AI Architect",
  "AI Solutions Architect",
  "AI Platform Engineer",
  "AI Infrastructure Engineer",
  "AI Researcher",
  "AI Scientist",
  "AI Research Scientist",
  "Applied AI Scientist",
  "Applied Scientist",
  "AI Consultant",
  "AI Product Engineer",
  "AI Product Manager",
  "AI Integration Engineer",
  "AI Automation Engineer",
  "AI Reliability Engineer",
  "AI Safety Engineer",
  "AI Security Engineer",
  "Responsible AI Engineer",
  "AI Governance Specialist",
  "AI Risk Specialist",
  "AI Evaluation Engineer",
  "AI Auditor",
  "AI Red Team Researcher",
  "Machine Learning",
  "Aprendizaje Automático",
  "Statistical Learning",
  "Deep Learning",
  "Representation Learning",
  "Machine Learning Engineer",
  "ML Engineer",
  "Machine Learning Scientist",
  "ML Research Scientist",
  "Applied ML Scientist",
  "ML Researcher",
  "Deep Learning Engineer",
  "Deep Learning Researcher",
  "ML Infrastructure Engineer",
  "ML Platform Engineer",
  "ML Systems Engineer",
  "ML Compiler Engineer",
  "ML Performance Engineer",
  "ML Optimization Engineer",
  "MLOps Engineer",
  "Model Deployment Engineer",
  "Model Serving Engineer",
  "Model Evaluation Engineer",
  "Model Validation Engineer",
  "Generative AI",
  "Inteligencia Artificial Generativa",
  "Generative AI Engineer",
  "Generative AI Developer",
  "GenAI Architect",
  "GenAI Researcher",
  "Foundation Model Engineer",
  "Foundation Model Researcher",
  "Large Language Model Engineer",
  "LLM Engineer",
  "LLM Researcher",
  "LLM Infrastructure Engineer",
  "LLMOps Engineer",
  "Language Model Evaluation Engineer",
  "AI Inference Engineer",
  "AI Training Engineer",
  "AI Model Optimization Engineer",
  "AI Model Compression Engineer",
  "AI Alignment Researcher",
  "AI Safety Researcher",
  "Synthetic Data Engineer",
  "AI Data Engineer",
  "Agentic AI",
  "IA Agéntica",
  "AI Agent Engineer",
  "Agentic AI Engineer",
  "Autonomous Agent Developer",
  "Multi-Agent Systems Engineer",
  "Multi-Agent Systems Researcher",
  "Agent Platform Engineer",
  "Agent Infrastructure Engineer",
  "Agent Orchestration Engineer",
  "AI Workflow Engineer",
  "AI Tooling Engineer",
  "AI Agent Security Engineer",
  "Agent Evaluation Engineer",
  "Autonomous Software Agent Researcher",
  "Human-Agent Interaction Researcher",
  "Natural Language Processing",
  "Procesamiento de Lenguaje Natural",
  "NLP",
  "Computational Linguistics",
  "Lingüística Computacional",
  "NLP Engineer",
  "NLP Scientist",
  "Computational Linguist",
  "Language AI Engineer",
  "Speech and Language Engineer",
  "Text Mining Engineer",
  "Information Extraction Engineer",
  "Conversational AI Engineer",
  "Chatbot Developer",
  "Dialogue Systems Engineer",
  "Machine Translation Engineer",
  "Language Model Engineer",
  "Speech Recognition Engineer",
  "Speech AI Engineer",
  "Speech Scientist",
  "Voice AI Engineer",
  "Text-to-Speech Engineer",
  "Automatic Speech Recognition Engineer",
  "ASR Engineer",
  "Audio AI Engineer",
  "Audio Signal Processing Engineer",
  "Computational Audio Researcher",
  "Music Information Retrieval Engineer",
  "Computer Vision",
  "Visión Artificial",
  "Machine Vision",
  "Image Computing",
  "Computer Vision Engineer",
  "Computer Vision Scientist",
  "Vision AI Engineer",
  "Machine Vision Engineer",
  "Image Processing Engineer",
  "Video Analytics Engineer",
  "Visual Recognition Engineer",
  "3D Vision Engineer",
  "Visual SLAM Engineer",
  "Medical Computer Vision Engineer",
  "Remote Sensing AI Engineer",
  "Vision Research Scientist",
  "Ingeniería Robótica",
  "Robotics Engineering",
  "Intelligent Robotics",
  "Autonomous Systems Engineering",
  "Robotics Engineer",
  "Robotics Software Engineer",
  "Robotics Hardware Engineer",
  "Robotics Systems Engineer",
  "Robotics AI Engineer",
  "Robotics Researcher",
  "Robot Programmer",
  "Robot Perception Engineer",
  "Robot Vision Engineer",
  "Robot Control Engineer",
  "Motion Planning Engineer",
  "Localization Engineer",
  "SLAM Engineer",
  "Navigation Engineer",
  "Human-Robot Interaction Engineer",
  "Swarm Robotics Engineer",
  "Industrial Robotics Engineer",
  "Service Robotics Engineer",
  "Humanoid Robotics Engineer",
  "Medical Robotics Engineer",
  "Autonomous Vehicle Engineering",
  "Autonomous Vehicle Engineer",
  "Autonomous Driving Engineer",
  "ADAS Engineer",
  "Autonomous Navigation Engineer",
  "Autonomous Perception Engineer",
  "Sensor Fusion Engineer",
  "Vehicle AI Engineer",
  "Vehicle Software Engineer",
  "Automotive Software Engineer",
  "Automotive Cybersecurity Engineer",
  "Fleet Intelligence Engineer",
  "Autonomous Mobility Engineer",
  "Drone Autonomy Engineer",
  "UAV Engineer",
  "Drone Software Engineer",
  "Drone Systems Engineer",
  "Drone AI Engineer",
  "Drone Network Engineer",
  "Drone Security Engineer",
  "Autonomous Drone Engineer",
  "UAS Engineer",
  "Unmanned Systems Engineer",
  "Swarm Drone Engineer",
  "Ciberseguridad",
  "Cybersecurity",
  "Ingeniería de Ciberseguridad",
  "Cybersecurity Engineering",
  "Seguridad Informática",
  "Seguridad de la Información",
  "Information Security",
  "Cyber Defense",
  "Cyber Operations",
  "Information Assurance",
  "Digital Security",
  "Cybersecurity Analyst",
  "Cybersecurity Engineer",
  "Cybersecurity Architect",
  "Cybersecurity Specialist",
  "Cybersecurity Consultant",
  "Information Security Analyst",
  "Information Security Engineer",
  "Information Security Architect",
  "Security Administrator",
  "Security Engineer",
  "Security Architect",
  "Security Analyst",
  "Security Consultant",
  "Security Researcher",
  "Security Operations Analyst",
  "SOC Analyst",
  "SOC Manager",
  "Cyber Defense Analyst",
  "Cyber Defense Engineer",
  "Cyber Operations Specialist",
  "Threat Analyst",
  "Cyber Threat Analyst",
  "Threat Intelligence Analyst",
  "Cyber Threat Intelligence Analyst",
  "Threat Intelligence Engineer",
  "Threat Hunter",
  "Cyber Threat Hunter",
  "Detection Engineer",
  "Security Detection Engineer",
  "SIEM Engineer",
  "SOAR Engineer",
  "Security Automation Engineer",
  "Incident Responder",
  "Cyber Incident Responder",
  "Incident Response Engineer",
  "Cyber Crisis Specialist",
  "Hacking",
  "Hacking Ético",
  "Ethical Hacking",
  "Ethical Hacker",
  "White-Hat Hacker",
  "Penetration Tester",
  "Pentester",
  "Offensive Security Engineer",
  "Offensive Security Consultant",
  "Offensive Security Researcher",
  "Red Team Operator",
  "Red Team Engineer",
  "Red Team Specialist",
  "Adversary Simulation Engineer",
  "Web Pentester",
  "API Pentester",
  "Network Pentester",
  "Wireless Pentester",
  "Mobile Pentester",
  "Cloud Pentester",
  "IoT Pentester",
  "Embedded Pentester",
  "Hardware Pentester",
  "Automotive Pentester",
  "OT Pentester",
  "ICS Pentester",
  "Vulnerability Researcher",
  "Exploit Researcher",
  "Binary Exploitation Researcher",
  "Bug Bounty Hunter",
  "Security Tool Developer",
  "Blue Team Analyst",
  "Blue Team Engineer",
  "Security Monitoring Analyst",
  "Endpoint Security Engineer",
  "EDR Engineer",
  "XDR Engineer",
  "Firewall Engineer",
  "Email Security Engineer",
  "Application Security Engineer",
  "Purple Team Engineer",
  "Purple Team Analyst",
  "Purple Team Specialist",
  "Security Validation Engineer",
  "Detection Validation Engineer",
  "Attack Simulation Engineer",
  "Breach and Attack Simulation Engineer",
  "Malware Analyst",
  "Malware Researcher",
  "Malware Reverse Engineer",
  "Reverse Engineer",
  "Binary Analyst",
  "Binary Reverse Engineer",
  "Firmware Reverse Engineer",
  "Mobile Reverse Engineer",
  "Threat Researcher",
  "Digital Forensics",
  "Computer Forensics",
  "Cyber Forensics",
  "Digital Investigation",
  "Digital Forensics Analyst",
  "Computer Forensics Analyst",
  "Cyber Forensics Analyst",
  "DFIR Specialist",
  "Digital Evidence Analyst",
  "Digital Evidence Examiner",
  "Computer Crime Investigator",
  "Cybercrime Investigator",
  "Mobile Forensics Analyst",
  "Network Forensics Analyst",
  "Memory Forensics Analyst",
  "Cloud Forensics Analyst",
  "Malware Forensics Analyst",
  "Incident Forensics Specialist",
  "Cryptography",
  "Criptografía",
  "Applied Cryptography",
  "Cryptographic Engineering",
  "Cryptanalysis",
  "Cryptographer",
  "Cryptography Engineer",
  "Cryptographic Engineer",
  "Cryptography Researcher",
  "Cryptanalyst",
  "PKI Engineer",
  "Key Management Engineer",
  "Hardware Cryptography Engineer",
  "Secure Protocol Engineer",
  "Post-Quantum Cryptography Engineer",
  "Post-Quantum Security Engineer",
  "IAM Engineer",
  "IAM Architect",
  "Identity Engineer",
  "Identity Security Engineer",
  "Identity Security Architect",
  "Access Management Engineer",
  "PAM Engineer",
  "Privileged Access Specialist",
  "Authentication Engineer",
  "Authorization Engineer",
  "Federation Engineer",
  "Digital Identity Engineer",
  "Zero Trust Engineer",
  "Zero Trust Architect",
  "Product Security Engineer",
  "Software Security Engineer",
  "Secure Software Engineer",
  "Secure Code Reviewer",
  "Security Code Analyst",
  "Software Supply Chain Security Engineer",
  "Secure SDLC Engineer",
  "API Security Engineer",
  "Mobile Application Security Engineer",
  "Web Application Security Engineer",
  "Firmware Security Engineer",
  "Chip Security Engineer",
  "Silicon Security Engineer",
  "Trusted Computing Engineer",
  "Secure Hardware Architect",
  "Side-Channel Security Researcher",
  "OT Security Engineer",
  "ICS Security Engineer",
  "SCADA Security Engineer",
  "Industrial Cybersecurity Engineer",
  "Critical Infrastructure Security Engineer",
  "Industrial Network Security Engineer",
  "Cyber-Physical Security Engineer",
  "Energy Cybersecurity Engineer",
  "Smart Grid Cybersecurity Engineer",
  "Hacking no ético",
  "Black-Hat Hacker",
  "Malicious Hacker",
  "Cracker",
  "Cybercriminal",
  "Malware Operator",
  "Ransomware Operator",
  "Ransomware Affiliate",
  "Botnet Operator",
  "Credential Thief",
  "Initial Access Broker",
  "Phisher",
  "Spear-Phishing Operator",
  "Carder",
  "Fraud Operator",
  "Account-Takeover Operator",
  "Data Extortionist",
  "DDoS Operator",
  "Illegal Exploit Broker",
  "Cyber Mercenary",
  "Malicious Insider",
  "Cyber Saboteur",
  "Software Cracker",
  "Digital Pirate",
  "Privacy Engineering",
  "Data Privacy",
  "Privacy Computing",
  "Privacy Engineer",
  "Privacy Architect",
  "Privacy Analyst",
  "Privacy Technologist",
  "Data Protection Specialist",
  "Privacy Security Engineer",
  "Privacy-Preserving ML Engineer",
  "Differential Privacy Researcher",
  "PETs Engineer",
  "Software Quality Assurance",
  "Software Testing",
  "Quality Engineering",
  "QA Engineer",
  "QA Analyst",
  "QA Tester",
  "Software Tester",
  "Test Engineer",
  "Test Analyst",
  "Quality Engineer",
  "Software Quality Engineer",
  "Automation Test Engineer",
  "Test Automation Engineer",
  "SDET",
  "Software Development Engineer in Test",
  "Performance Test Engineer",
  "Load Test Engineer",
  "Stress Test Engineer",
  "Security Test Engineer",
  "Web QA Engineer",
  "API Test Engineer",
  "Embedded Test Engineer",
  "Hardware Test Engineer",
  "Reliability Test Engineer",
  "Accessibility Tester",
  "Game QA Tester",
  "Human-Computer Interaction",
  "HCI",
  "Human-Centered Computing",
  "Interaction Design",
  "HCI Researcher",
  "Human Factors Engineer",
  "Interaction Designer",
  "UX Engineer",
  "UX Developer",
  "UX Researcher",
  "UI Engineer",
  "UI Developer",
  "UI Designer",
  "UX Designer",
  "Product Designer",
  "Usability Engineer",
  "Accessibility Engineer",
  "Accessibility Specialist",
  "Human-Centered AI Researcher",
  "Human-AI Interaction Researcher",
  "Virtual Reality",
  "Realidad Virtual",
  "Augmented Reality",
  "Realidad Aumentada",
  "Mixed Reality",
  "Realidad Mixta",
  "Extended Reality",
  "XR",
  "Spatial Computing",
  "Computación Espacial",
  "VR Developer",
  "VR Engineer",
  "AR Developer",
  "AR Engineer",
  "MR Developer",
  "XR Developer",
  "XR Engineer",
  "Spatial Computing Engineer",
  "Spatial Software Engineer",
  "Immersive Systems Engineer",
  "Immersive Experience Developer",
  "3D Interaction Engineer",
  "Virtual Environment Engineer",
  "Metaverse Developer",
  "Metaverse Systems Engineer",
  "Computer Graphics",
  "Gráficos por Computadora",
  "Visual Computing",
  "Computational Graphics",
  "Graphics Engineer",
  "Graphics Programmer",
  "Rendering Engineer",
  "Rendering Programmer",
  "GPU Graphics Engineer",
  "Shader Developer",
  "3D Graphics Engineer",
  "Visualization Engineer",
  "Scientific Visualization Engineer",
  "Visual Computing Researcher",
  "Simulation Graphics Engineer",
  "Game Development",
  "Desarrollo de Videojuegos",
  "Game Programming",
  "Game Engineering",
  "Computer Games Technology",
  "Game Developer",
  "Game Programmer",
  "Game Engineer",
  "Gameplay Programmer",
  "Game Engine Programmer",
  "Engine Developer",
  "Game AI Programmer",
  "Network Gameplay Engineer",
  "Multiplayer Engineer",
  "Physics Programmer",
  "Tools Programmer",
  "Technical Game Designer",
  "Technical Artist",
  "Game Systems Designer",
  "Game Backend Engineer",
  "Game Server Engineer",
  "Game Security Engineer",
  "Anti-Cheat Engineer",
  "Game Analytics Engineer",
  "Game Platform Engineer",
  "Multimedia Computing",
  "Multimedia Engineering",
  "Ingeniería Multimedia",
  "Digital Media Technology",
  "Interactive Media",
  "Multimedia Developer",
  "Multimedia Programmer",
  "Interactive Media Developer",
  "Creative Technologist",
  "Digital Media Engineer",
  "Interactive Systems Engineer",
  "Multimedia Systems Engineer",
  "Computer Simulation",
  "Computational Modeling",
  "Modeling and Simulation Engineering",
  "Simulation Engineer",
  "Simulation Software Engineer",
  "Modeling Engineer",
  "Computational Modeler",
  "Digital Simulation Engineer",
  "Physics Simulation Engineer",
  "Real-Time Simulation Engineer",
  "Virtual Prototyping Engineer",
  "Digital Twin Engineering",
  "Gemelos Digitales",
  "Digital Twin Systems",
  "Digital Twin Engineer",
  "Digital Twin Architect",
  "Digital Twin Developer",
  "Digital Twin Data Engineer",
  "Digital Twin AI Engineer",
  "Digital Twin Network Engineer",
  "Digital Twin Simulation Engineer",
  "Digital Twin Platform Engineer",
  "High Performance Computing",
  "HPC",
  "Supercomputing",
  "Supercomputación",
  "Parallel Computing",
  "HPC Engineer",
  "HPC Systems Engineer",
  "HPC Software Engineer",
  "HPC Administrator",
  "Supercomputing Engineer",
  "Parallel Computing Engineer",
  "GPU Computing Engineer",
  "Scientific Computing Engineer",
  "Performance Optimization Engineer",
  "Cluster Administrator",
  "HPC Security Engineer",
  "Quantum Computing",
  "Computación Cuántica",
  "Quantum Information Science",
  "Quantum Engineering",
  "Quantum Information Engineering",
  "Quantum Software Engineering",
  "Quantum Computing Scientist",
  "Quantum Computing Engineer",
  "Quantum Software Engineer",
  "Quantum Software Developer",
  "Quantum Algorithm Engineer",
  "Quantum Algorithm Researcher",
  "Quantum Information Scientist",
  "Quantum Hardware Engineer",
  "Quantum Control Engineer",
  "Quantum Systems Engineer",
  "Quantum Architecture Researcher",
  "Quantum Error Correction Researcher",
  "Quantum Compiler Engineer",
  "Quantum Cloud Engineer",
  "Quantum Simulation Scientist",
  "Quantum Machine Learning Researcher",
  "Quantum Cryptography Researcher",
  "Blockchain Engineering",
  "Blockchain",
  "Distributed Ledger Technology",
  "DLT",
  "Decentralized Systems",
  "Blockchain Developer",
  "Blockchain Engineer",
  "Blockchain Architect",
  "Blockchain Protocol Engineer",
  "Distributed Ledger Engineer",
  "Smart Contract Developer",
  "Smart Contract Engineer",
  "Smart Contract Auditor",
  "Blockchain Security Engineer",
  "Blockchain Researcher",
  "Decentralized Systems Engineer",
  "Web3 Developer",
  "Web3 Engineer",
  "Web3 Security Engineer",
  "Financial Technology",
  "FinTech",
  "Computational Finance",
  "Financial Engineering",
  "FinTech Engineer",
  "Financial Software Engineer",
  "Financial Systems Developer",
  "Quant Developer",
  "Quantitative Developer",
  "Algorithmic Trading Developer",
  "Trading Systems Engineer",
  "Financial Data Scientist",
  "Risk Technology Engineer",
  "Payment Systems Engineer",
  "Digital Banking Engineer",
  "Bioinformatics",
  "Bioinformática",
  "Computational Biology",
  "Biología Computacional",
  "Biomedical Informatics",
  "Informática Biomédica",
  "Bioinformatics Scientist",
  "Bioinformatics Engineer",
  "Bioinformatics Developer",
  "Bioinformatics Analyst",
  "Bioinformatics Technician",
  "Computational Biologist",
  "Genomics Data Scientist",
  "Genomic Data Engineer",
  "Biomedical Data Scientist",
  "Biological Data Scientist",
  "Computational Genomics Scientist",
  "Proteomics Data Scientist",
  "Health Informatics",
  "Informática de Salud",
  "Medical Informatics",
  "Informática Médica",
  "Clinical Informatics",
  "Nursing Informatics",
  "Public Health Informatics",
  "Health Informatics Specialist",
  "Clinical Informatics Specialist",
  "Medical Informatics Engineer",
  "Healthcare Data Engineer",
  "Healthcare Data Scientist",
  "Clinical Data Analyst",
  "Clinical Data Scientist",
  "Health IT Engineer",
  "Hospital Systems Engineer",
  "Electronic Health Record Specialist",
  "Medical Software Engineer",
  "Medical AI Engineer",
  "Medical Imaging AI Engineer",
  "Digital Health Engineer",
  "Telemedicine Systems Engineer",
  "Neuroinformatics",
  "Neuroinformática",
  "Computational Neuroscience",
  "Neurotechnology",
  "Brain-Computer Interfaces",
  "Neuroinformatics Scientist",
  "Computational Neuroscientist",
  "Neurotechnology Engineer",
  "Brain-Computer Interface Engineer",
  "BCI Engineer",
  "Neural Data Scientist",
  "Neural Signal Processing Engineer",
  "Neural Interface Software Engineer",
  "Neuro-AI Researcher",
  "Cheminformatics",
  "Chemoinformatics",
  "Computational Chemistry",
  "Computational Physics",
  "Computational Materials Science",
  "Materials Informatics",
  "Computational Chemist",
  "Cheminformatics Scientist",
  "Molecular Modeling Scientist",
  "Computational Physicist",
  "Materials Informatics Scientist",
  "Scientific Software Engineer",
  "Geoinformatics",
  "Geoinformática",
  "Geographic Information Science",
  "GIS",
  "Geomatics",
  "Geomática",
  "Remote Sensing",
  "GIS Developer",
  "GIS Analyst",
  "GIS Engineer",
  "Geospatial Data Engineer",
  "Geospatial Data Scientist",
  "Geospatial Software Engineer",
  "Remote Sensing Engineer",
  "Remote Sensing Data Scientist",
  "Spatial Data Scientist",
  "Geospatial AI Engineer",
  "Mapping Software Engineer",
  "Astroinformatics",
  "Computational Astronomy",
  "Computational Astrophysics",
  "Computational Economics",
  "Computational Social Science",
  "Social Computing",
  "Computational Journalism",
  "Computational Archaeology",
  "Computational History",
  "Digital Humanities",
  "Humanities Computing",
  "Computational Law",
  "Legal Informatics",
  "Computational Agriculture",
  "Agricultural Informatics",
  "Precision Agriculture Computing",
  "Environmental Informatics",
  "Environmental Data Science",
  "Climate Informatics",
  "Computational Sustainability",
  "Computational Epidemiology",
  "Computational Pharmacology",
  "Pharmacoinformatics",
  "Drug Discovery Informatics",
  "Computational Design",
  "Computational Architecture",
  "Ingeniería Mecatrónica",
  "Mechatronics Engineering",
  "Robotics and Mechatronics",
  "Intelligent Mechatronics",
  "Automation Engineering",
  "Control Engineering",
  "Intelligent Automation",
  "Mechatronics Software Engineer",
  "Automation Engineer",
  "Control Systems Engineer",
  "Intelligent Control Engineer",
  "Industrial Automation Engineer",
  "PLC Engineer",
  "SCADA Engineer",
  "Robotics Control Engineer",
  "Industrial Software Engineer",
  "Industry 4.0 Engineering",
  "Industria 4.0",
  "Industria 5.0",
  "Smart Manufacturing",
  "Digital Manufacturing",
  "Industrial Informatics",
  "Industry 4.0 Engineer",
  "Smart Factory Engineer",
  "Digital Manufacturing Engineer",
  "Manufacturing Data Engineer",
  "Industrial AI Engineer",
  "Manufacturing Systems Engineer",
  "Industrial Digital Twin Engineer",
  "Manufacturing Software Engineer",
  "Robotic Process Automation",
  "RPA",
  "Business Process Automation",
  "RPA Developer",
  "RPA Engineer",
  "RPA Architect",
  "Business Automation Engineer",
  "Intelligent Automation Engineer",
  "Workflow Automation Engineer",
  "Process Automation Developer",
  "Hyperautomation Engineer",
  "Automation Architect",
  "Low-Code Development",
  "No-Code Development",
  "Low-Code Developer",
  "No-Code Developer",
  "Citizen Developer",
  "Power Platform Developer",
  "Power Apps Developer",
  "Low-Code Architect",
  "Business Application Developer",
  "Automation Platform Developer",
  "Enterprise Systems",
  "Enterprise Computing",
  "ERP Developer",
  "ERP Consultant",
  "ERP Architect",
  "SAP Developer",
  "SAP Consultant",
  "Oracle ERP Developer",
  "CRM Developer",
  "CRM Consultant",
  "Salesforce Developer",
  "Salesforce Architect",
  "Enterprise Systems Engineer",
  "Enterprise Applications Engineer",
  "Enterprise Integration Architect",
  "Enterprise Architecture",
  "Arquitectura Empresarial",
  "IT Architecture",
  "Business Architecture",
  "Enterprise Architect",
  "IT Architect",
  "Technology Architect",
  "Systems Architect",
  "Infrastructure Architect",
  "Integration Architect",
  "IT Management",
  "Gestión de TI",
  "Information Systems Management",
  "Technology Management",
  "IT Manager",
  "IT Operations Manager",
  "Infrastructure Manager",
  "Systems Manager",
  "Development Manager",
  "Data Manager",
  "Network Manager",
  "Cloud Manager",
  "Cybersecurity Manager",
  "IT Service Manager",
  "Technology Manager",
  "IT Governance",
  "Gobierno TI",
  "IT Service Management",
  "ITSM",
  "Technology Governance",
  "Information Systems Audit",
  "Auditoría de Sistemas",
  "Auditoría Informática",
  "IT Governance Specialist",
  "IT Governance Manager",
  "ITSM Specialist",
  "ITSM Consultant",
  "Service Management Analyst",
  "Service Delivery Manager",
  "Incident Manager",
  "Problem Manager",
  "Change Manager",
  "Configuration Manager",
  "CMDB Administrator",
  "IT Asset Manager",
  "IT Auditor",
  "Systems Auditor",
  "Information Systems Auditor",
  "Technology Risk Analyst",
  "IT Risk Manager",
  "IT Compliance Analyst",
  "IT Controls Analyst",
  "GRC Analyst",
  "GRC Engineer",
  "GRC Manager",
  "IT Project Management",
  "Gestión de Proyectos TI",
  "Software Project Management",
  "IT Project Manager",
  "Technical Project Manager",
  "Software Project Manager",
  "Digital Project Manager",
  "Program Manager",
  "Technical Program Manager",
  "PMO Analyst",
  "PMO Manager",
  "Scrum Master",
  "Agile Coach",
  "Delivery Manager",
  "Product Management",
  "Digital Product Management",
  "Product Manager",
  "Technical Product Manager",
  "Data Product Manager",
  "Cybersecurity Product Manager",
  "Cloud Product Manager",
  "Platform Product Manager",
  "Product Owner",
  "Technical Product Owner",
  "Product Operations Manager",
  "Digital Transformation",
  "Transformación Digital",
  "Digital Business",
  "Technology Innovation",
  "Digital Transformation Specialist",
  "Digital Transformation Consultant",
  "Digital Transformation Architect",
  "Digital Strategy Consultant",
  "Technology Transformation Manager",
  "Digital Innovation Manager",
  "Digitalization Engineer",
  "Technology Innovation Specialist",
  "E-Commerce Technology",
  "Digital Commerce",
  "Digital Commerce Specialist",
  "E-Commerce Data Analyst",
  "E-Commerce Platform Engineer",
  "E-Commerce Security Engineer",
  "Information Retrieval",
  "Search Engineering",
  "Recommender Systems",
  "Knowledge Representation",
  "Search Engineer",
  "Search Relevance Engineer",
  "Information Retrieval Engineer",
  "Recommendation Systems Engineer",
  "Recommender Systems Scientist",
  "Personalization Engineer",
  "Knowledge Graph Engineer",
  "Knowledge Engineer",
  "Ontology Engineer",
  "Semantic Web Engineer",
  "Knowledge Management",
  "Information Architecture",
  "Knowledge Management Specialist",
  "Knowledge Architect",
  "Information Architect",
  "Taxonomy Specialist",
  "Ontologist",
  "Semantic Engineer",
  "Digital Libraries",
  "Library Informatics",
  "Digital Preservation",
  "Archival Informatics",
  "Digital Archivist",
  "Digital Preservation Specialist",
  "Digital Library Engineer",
  "Information Systems Librarian",
  "Research Data Manager",
  "Aerospace Software Engineering",
  "Space Systems Computing",
  "Space Informatics",
  "Aerospace Software Engineer",
  "Avionics Software Engineer",
  "Flight Software Engineer",
  "Space Systems Software Engineer",
  "Satellite Software Engineer",
  "Satellite Data Engineer",
  "Mission Software Engineer",
  "Ground Systems Engineer",
  "Space Cybersecurity Engineer",
  "Space Network Engineer",
  "Autonomous Space Systems Engineer",
  "Maritime Informatics",
  "Maritime Digital Systems",
  "Maritime Software Engineer",
  "Maritime Cybersecurity Engineer",
  "Autonomous Ship Systems Engineer",
  "Maritime IoT Engineer",
  "Maritime Data Engineer",
  "Navigation Systems Engineer",
  "Automotive Computing",
  "Automotive Software Engineering",
  "Infotainment Software Engineer",
  "Vehicle Network Engineer",
  "Connected Car Engineer",
  "Vehicle Data Engineer",
  "Computer Science Education",
  "Computing Education",
  "Educational Technology",
  "Profesor de Informática",
  "Profesor de Computación",
  "Profesor de Programación",
  "Computer Science Teacher",
  "Computer Science Professor",
  "Computing Lecturer",
  "IT Instructor",
  "Programming Instructor",
  "Cybersecurity Instructor",
  "Data Science Instructor",
  "AI Instructor",
  "Educational Technology Specialist",
  "Learning Technology Engineer",
  "E-Learning Developer",
  "Instructional Technology Specialist",
  "Computer Scientist",
  "Computing Researcher",
  "Computer Science Researcher",
  "Software Engineering Researcher",
  "Cybersecurity Researcher",
  "Network Researcher",
  "Telecommunications Researcher",
  "Quantum Computing Researcher",
  "Distributed Systems Researcher",
  "Computer Architecture Researcher",
  "Research Software Engineer",
  "Technical Writer",
  "API Technical Writer",
  "Software Documentation Engineer",
  "Documentation Engineer",
  "Developer Documentation Engineer",
  "Technical Communicator",
  "Technology Journalist",
  "Developer Educator",
  "Developer Advocate",
  "Developer Relations Engineer",
  "DevRel Engineer",
  "Technology Evangelist",
  "IT Consultant",
  "Technology Consultant",
  "Software Consultant",
  "Systems Consultant",
  "Infrastructure Consultant",
  "Network Consultant",
  "Data Consultant",
  "Solutions Consultant",
  "Technical Consultant",
  "Sales Engineer",
  "Solutions Engineer",
  "Pre-Sales Engineer",
  "Technical Sales Engineer",
  "Cloud Solutions Engineer",
  "Cybersecurity Solutions Engineer",
  "Network Solutions Engineer",
  "AI Solutions Engineer",
  "Technical Account Manager",
  "Customer Engineer",
  "Customer Success Engineer",
  "Technology Entrepreneur",
  "Software Entrepreneur",
  "SaaS Founder",
  "Startup Founder",
  "Technical Founder",
  "Technology Founder",
  "Indie Hacker",
  "Indie Developer",
  "App Entrepreneur",
  "Game Entrepreneur",
  "AI Startup Founder",
  "Cybersecurity Startup Founder",
  "Chief Information Officer",
  "CIO",
  "Chief Technology Officer",
  "CTO",
  "Chief Information Security Officer",
  "CISO",
  "Chief Data Officer",
  "CDO",
  "Chief Digital Officer",
  "Chief AI Officer",
  "CAIO",
  "Chief Analytics Officer",
  "Chief Software Architect",
  "Chief Security Architect",
  "Chief Privacy Officer",
  "VP Engineering",
  "VP Software Engineering",
  "VP Infrastructure",
  "VP Technology",
  "VP Data",
  "VP AI",
  "VP Cybersecurity",
  "Director of Engineering",
  "Director of IT",
  "Director of Data",
  "Director of AI",
  "Director of Cybersecurity",
  "Computador Humano",
  "Human Computer",
  "Calculista Humano",
  "Mathematical Computer",
  "Numerical Calculator",
  "Telegraph Operator",
  "Operador de Telégrafo",
  "Telephone Switchboard Operator",
  "Operador de Central Telefónica",
  "Radio Telegraph Operator",
  "Teletype Operator",
  "Telex Operator",
  "Tabulating Machine Operator",
  "Tabulator Operator",
  "Punch Card Operator",
  "Punched-Card Operator",
  "Keypunch Operator",
  "Key-Punch Operator",
  "Card Punch Operator",
  "Card Sorter Operator",
  "Data Processing Clerk",
  "Electronic Data Processing Operator",
  "EDP Operator",
  "Mainframe Operator",
  "Computer Operator",
  "Console Operator",
  "Tape Librarian",
  "Magnetic Tape Operator",
  "Data Entry Operator",
  "Computer Room Operator",
  "Batch Processing Operator",
  "Numerical Programmer",
  "Machine-Code Programmer",
  "Mainframe Programmer",
  "Mainframe Systems Programmer",
  "Mainframe Systems Analyst",
  "Telephone Exchange Technician",
  "Telegraph Engineer",
  "Radio Technician",
  "Early Network Operator",
  "Minicomputer Operator",
  "Microcomputer Technician",
  "Bulletin Board System Operator",
  "BBS Sysop",
  "AI-Native Software Engineer",
  "AI-Assisted Software Architect",
  "Autonomous Software Systems Engineer",
  "AI Software Supervisor",
  "Autonomous Coding Systems Engineer",
  "Software Agent Architect",
  "AI Code Verification Engineer",
  "AI-Generated Software Auditor",
  "AI Software Reliability Engineer",
  "Human-AI Software Engineering Specialist",
  "Agentic AI Architect",
  "Autonomous Agent Engineer",
  "AI Orchestration Engineer",
  "Foundation Model Architect",
  "AI Training Infrastructure Engineer",
  "AI Assurance Engineer",
  "AI Governance Engineer",
  "AI Governance Architect",
  "Human-AI Collaboration Engineer",
  "AI Data Curator",
  "Vector Database Engineer",
  "Vector Search Engineer",
  "Retrieval Engineer",
  "RAG Engineer",
  "AI Knowledge Engineer",
  "Data Provenance Engineer",
  "AI Cloud Infrastructure Engineer",
  "AI Cluster Engineer",
  "GPU Infrastructure Engineer",
  "GPU Cluster Engineer",
  "Accelerator Infrastructure Engineer",
  "AI Data Center Engineer",
  "AI Data Center Architect",
  "Sustainable Computing Engineer",
  "Green Cloud Engineer",
  "Carbon-Aware Computing Engineer",
  "LLM Security Engineer",
  "Model Security Engineer",
  "Model Supply Chain Security Engineer",
  "AI Incident Response Specialist",
  "AI Forensics Specialist",
  "Post-Quantum Migration Engineer",
  "Cryptographic Agility Engineer",
  "Cybersecurity Supply Chain Risk Specialist",
  "6G Network Engineer",
  "6G Systems Architect",
  "6G AI Engineer",
  "AI-Native Network Engineer",
  "Semantic Communications Engineer",
  "Integrated Sensing and Communications Engineer",
  "ISAC Engineer",
  "Terahertz Communications Engineer",
  "Reconfigurable Intelligent Surface Engineer",
  "Non-Terrestrial Network Engineer",
  "Satellite Mesh Network Engineer",
  "Space Internet Engineer",
  "Autonomous Network Engineer",
  "Self-Healing Network Engineer",
  "Intent-Based Networking Engineer",
  "Cognitive Network Engineer",
  "Network Digital Twin Engineer",
  "AI-RAN Engineer",
  "Edge Intelligence Engineer",
  "Internet of Everything Engineer",
  "AIoT Engineer",
  "Artificial Intelligence of Things Engineer",
  "Ambient Intelligence Engineer",
  "Ubiquitous Computing Engineer",
  "Pervasive Computing Engineer",
  "Ambient Computing Engineer",
  "Smart Environment Engineer",
  "Autonomous IoT Systems Engineer",
  "IoT Digital Twin Engineer",
  "Intelligent Sensor Engineer",
  "Edge Robotics Engineer",
  "Swarm IoT Engineer",
  "Massive IoT Architect",
  "Smart Infrastructure Engineer",
  "Intelligent Infrastructure Engineer",
  "Embodied AI Engineer",
  "Embodied Intelligence Researcher",
  "Robot Foundation Model Engineer",
  "Autonomous Robot Architect",
  "Multi-Robot Systems Engineer",
  "Robot Swarm Engineer",
  "Cognitive Robotics Engineer",
  "Social Robotics Engineer",
  "Household Robotics Engineer",
  "Human-Robot Collaboration Engineer",
  "Autonomous Factory Engineer",
  "Spatial AI Engineer",
  "Spatial Intelligence Engineer",
  "Immersive Computing Engineer",
  "Holographic Computing Engineer",
  "Digital Reality Engineer",
  "Virtual World Systems Engineer",
  "Persistent Virtual Environment Engineer",
  "Mixed-Reality AI Engineer",
  "Spatial Interface Engineer",
  "Biological Computing",
  "Computación Biológica",
  "Molecular Computing",
  "Computación Molecular",
  "DNA Computing",
  "Computación con ADN",
  "Neuromorphic Computing",
  "Computación Neuromórfica",
  "Bio-Inspired Computing",
  "Biological Computing Scientist",
  "Molecular Computing Engineer",
  "DNA Computing Researcher",
  "Neuromorphic Computing Engineer",
  "Neuromorphic Hardware Engineer",
  "Neuromorphic Software Engineer",
  "Neuromorphic Chip Architect",
  "Spiking Neural Network Engineer",
  "Brain-Inspired Computing Scientist",
  "Event-Based Vision Engineer",
  "Optical Computing",
  "Computación Óptica",
  "Photonic Computing",
  "Computación Fotónica",
  "Photonic Computing Engineer",
  "Optical Computing Engineer",
  "Photonic AI Accelerator Engineer",
  "Silicon Photonics Engineer",
  "Optical Processor Architect",
  "Photonic Systems Engineer",
  "Quantum AI Engineer",
  "Quantum Machine Learning Engineer",
  "Quantum ML Researcher",
  "Quantum-Classical Systems Engineer",
  "Hybrid Quantum Computing Engineer",
  "Quantum AI Infrastructure Engineer",
  "Quantum Data Scientist",
  "Quantum Optimization Scientist",
  "Quantum Security Engineer",
  "Quantum Cryptography Engineer",
  "Quantum Network Security Engineer",
  "Quantum Key Distribution Engineer",
  "QKD Engineer",
  "PQC Migration Architect",
  "Quantum-Safe Security Architect",
  "Quantum Network Engineer",
  "Quantum Network Architect",
  "Quantum Internet Researcher",
  "Quantum Communications Engineer",
  "Quantum Repeater Engineer",
  "Quantum Protocol Engineer",
  "Quantum Network Security Researcher",
  "Autonomous Computing Engineer",
  "Self-Managing Systems Engineer",
  "Autonomous Infrastructure Engineer",
  "Autonomous Cloud Engineer",
  "Self-Healing Infrastructure Engineer",
  "Autonomous Database Engineer",
  "Autonomous Cyber Defense Engineer",
  "Autonomous DevOps Engineer",
  "Autonomous Systems Security Engineer",
  "Robot Security Engineer",
  "Drone Cybersecurity Engineer",
  "Autonomous Vehicle Cybersecurity Engineer",
  "Autonomous Infrastructure Security Engineer",
  "Satellite Cybersecurity Engineer",
  "Space Network Security Engineer",
  "Space Systems Security Architect",
  "Space Threat Intelligence Analyst",
  "Orbital Network Security Engineer",
  "Green Computing",
  "Computación Verde",
  "Sustainable Computing",
  "Sustainable Software Engineering",
  "Green Software Engineer",
  "Sustainable Software Engineer",
  "Energy-Efficient Computing Engineer",
  "Sustainable Data Center Engineer",
  "Sustainable AI Engineer",
  "Green Cloud Architect",
  "Technology Ethics",
  "AI Ethics",
  "Digital Ethics",
  "Responsible Technology",
  "AI Ethics Specialist",
  "Responsible AI Specialist",
  "AI Policy Technologist",
  "Technology Ethics Researcher",
  "Algorithmic Accountability Specialist",
  "Algorithm Auditor",
  "AI Assurance Specialist",
  "Law and Technology",
  "Legal Technology Engineer",
  "Legal Informatics Specialist",
  "LegalTech Developer",
  "LegalTech Engineer",
  "Computational Law Researcher",
  "eDiscovery Specialist",
  "Digital Evidence Specialist",
  "Technology Compliance Specialist",
  "Decentralized Infrastructure Engineer",
  "Decentralized Identity Engineer",
  "Distributed Trust Engineer",
  "Decentralized Storage Engineer",
  "Peer-to-Peer Systems Engineer",
  "Distributed Governance Systems Engineer",
  "Cryptoeconomic Systems Engineer",
  "Smart Cities Engineering",
  "Urban Informatics",
  "Civic Technology",
  "Smart City Engineer",
  "Urban Informatics Specialist",
  "Civic Technology Engineer",
  "Urban Data Scientist",
  "Smart Mobility Engineer",
  "Intelligent Transportation Systems Engineer",
  "Supply Chain Informatics",
  "Digital Logistics",
  "Logistics Software Engineer",
  "Supply Chain Data Scientist",
  "Supply Chain Systems Engineer",
  "Warehouse Automation Engineer",
  "Supply Chain AI Engineer",
  "Digital Supply Chain Architect",
  "AgriTech",
  "Agricultural Data Scientist",
  "AgriTech Software Engineer",
  "Precision Agriculture Engineer",
  "Agricultural IoT Engineer",
  "Agricultural AI Engineer",
  "Farm Robotics Engineer",
  "Climate Data Scientist",
  "Environmental Data Scientist",
  "Climate AI Scientist",
  "Environmental Software Engineer",
  "Computational Sustainability Scientist",
  "Earth Observation Data Scientist",
  "Defense Software Engineer",
  "Defense Systems Engineer",
  "Mission Systems Engineer",
  "Command-and-Control Systems Engineer",
  "C4ISR Systems Engineer",
  "Secure Communications Engineer",
  "Defense Cybersecurity Engineer",
  "Military Networks Engineer",
  "Quantitative Computing",
  "Algorithmic Trading",
  "Financial AI",
  "Quant Researcher",
  "High-Frequency Trading Engineer",
  "Low-Latency Systems Engineer",
  "Financial AI Engineer",
  "Computational Finance Scientist",
  "Storage Engineering",
  "Storage Architect",
  "Cloud Storage Engineer",
  "Object Storage Engineer",
  "Data Protection Engineer",
  "Storage Reliability Engineer",
  "Internet Infrastructure Engineering",
  "Internet Architecture",
  "Internet Infrastructure Engineer",
  "Internet Systems Engineer",
  "DNS Engineer",
  "DNS Security Engineer",
  "CDN Engineer",
  "CDN Architect",
  "Internet Routing Engineer",
  "BGP Engineer",
  "Internet Peering Engineer",
  "Internet Exchange Engineer",
  "Network Interconnection Engineer",
  "AI Hardware Engineer",
  "AI Accelerator Engineer",
  "AI Chip Architect",
  "NPU Engineer",
  "Neural Processing Unit Architect",
  "GPU Architecture Engineer",
  "Machine Learning Hardware Engineer",
  "AI Silicon Engineer",
  "AI Systems Hardware Engineer",
  "AI Memory Systems Engineer",
  "AI Interconnect Engineer",
  "AI Storage Engineer",
  "AI Data Center Network Engineer",
  "AI Infrastructure Reliability Engineer",
  "Artificial General Intelligence Engineer",
  "AGI Systems Engineer",
  "AGI Safety Engineer",
  "AGI Alignment Scientist",
  "General Intelligence Architect",
  "Superintelligence Safety Researcher",
  "Autonomous Intelligence Architect",
  "Machine Consciousness Researcher",
  "Artificial Consciousness Engineer",
  "Cognitive Architecture Engineer",
  "Synthetic Mind Engineer",
  "Digital Mind Engineer",
  "Digital Consciousness Researcher",
  "Artificial Personality Engineer",
  "Machine Agency Engineer",
  "Machine Rights Technologist",
  "Human-AI Symbiosis Engineer",
  "Human-Machine Intelligence Engineer",
  "Collective Intelligence Engineer",
  "Hybrid Intelligence Engineer",
  "Neural-Digital Integration Engineer",
  "Brain-Cloud Interface Engineer",
  "Brain-Computer Network Engineer",
  "Neural Cybersecurity Engineer",
  "Cognitive Security Engineer",
  "Neuroprivacy Engineer",
  "Digital Memory Engineer",
  "Synthetic Memory Systems Engineer",
  "Cognitive Augmentation Engineer",
  "Human Augmentation Software Engineer",
  "Cybernetic Systems Engineer",
  "Cybernetic Intelligence Engineer",
  "Digital Twin of Human Systems Engineer",
  "Personal Digital Twin Engineer",
  "AI Persona Engineer",
  "Autonomous Digital Representative Engineer",
  "Virtual Human Engineer",
  "Synthetic Human Interaction Engineer",
  "Advanced Humanoid Intelligence Engineer",
  "Post-CMOS Computing Engineer",
  "Non-Von-Neumann Computing Engineer",
  "Neuromorphic Architecture Engineer",
  "Memristive Computing Engineer",
  "In-Memory Computing Engineer",
  "Analog AI Computing Engineer",
  "Reversible Computing Researcher",
  "Quantum-Classical Architecture Engineer",
  "Space Internet Architect",
  "Interplanetary Network Engineer",
  "Delay-Tolerant Networking Engineer",
  "Lunar Network Engineer",
  "Mars Communications Engineer",
  "Deep-Space Network Engineer",
  "Interplanetary Cybersecurity Engineer",
  "Planetary IoT Engineer",
  "Space IoT Engineer",
  "Autonomous City Systems Engineer",
  "City AI Architect",
  "Autonomous Transportation Network Engineer",
  "Autonomous Infrastructure Architect",
  "Planetary Infrastructure Data Engineer",
  "Autonomous Energy Network Engineer",
  "Civilization-Scale Systems Engineer"
] as const
