export type FacultyV43 = {
  id: string
  code: string
  title: string
  subtitle: string
  description: string
  topics: string[]
  keywords: string[]
  tone: string
  stageRange: string
}

export type StandardV43 = {
  code: string
  name: string
  year: string
  role: string
  url: string
  level: "A" | "B"
}

export type SourceV43 = {
  name: string
  kind: string
  language: "ES" | "ES/EN" | "EN→ES"
  role: string
  url: string
  tier: "A" | "B" | "C" | "D"
}

export const standardsV43: StandardV43[] = [
  { code: "CS2023", name: "ACM / IEEE-CS / AAAI Computer Science Curricula", year: "2024", role: "17 áreas de conocimiento + competencias + pedagogía", url: "https://csed.acm.org/", level: "A" },
  { code: "CC2020", name: "Computing Curricula 2020", year: "2020", role: "Marco transversal de disciplinas de computing", url: "https://www.acm.org/education/curricula-recommendations", level: "A" },
  { code: "FING25", name: "UdelaR · Ingeniería en Computación · Plan 2025", year: "2025", role: "Referencia universitaria generalista en español · 450 créditos", url: "https://www.iie.fing.edu.uy/index.php/en/carrera/grado/ingenier%C3%ADa-en-computaci%C3%B3n", level: "A" },
  { code: "SWEBOK4", name: "IEEE Computer Society · SWEBOK V4.0a", year: "2025", role: "Cobertura de ingeniería de software · 18 knowledge areas", url: "https://www.computer.org/education/bodies-of-knowledge/software-engineering", level: "A" },
  { code: "SEBoK", name: "Guide to the Systems Engineering Body of Knowledge", year: "2026", role: "Ingeniería de sistemas, ciclo de vida, complejidad y disciplinas relacionadas", url: "https://sebokwiki.org/wiki/Guide_to_the_Systems_Engineering_Body_of_Knowledge_(SEBoK)", level: "A" },
  { code: "NICE", name: "NIST NICE Workforce Framework for Cybersecurity", year: "2025/2026", role: "Tareas, conocimientos, habilidades, competencias y roles de ciberseguridad", url: "https://www.nist.gov/itl/applied-cybersecurity/nice/nice-framework-resource-center/nice-framework-current-versions", level: "A" },
  { code: "CSEC17", name: "Cybersecurity Curricula 2017", year: "2017", role: "Base curricular interdisciplinaria de ciberseguridad", url: "https://cybered.hosting.acm.org/wp/", level: "A" },
  { code: "DS2021", name: "Computing Competencies for Undergraduate Data Science Curricula", year: "2021", role: "Cobertura curricular de ciencia de datos", url: "https://www.acm.org/education/curricula-recommendations", level: "A" },
]

export const facultiesV43: FacultyV43[] = [
  { id: "theory", code: "F01", title: "Matemática, teoría y algoritmos", subtitle: "La base que no caduca", description: "Matemática discreta y continua, probabilidad, lógica, computabilidad, complejidad, algoritmos, optimización, métodos numéricos y métodos formales.", topics: ["demostraciones", "algoritmos", "complejidad", "lógica", "autómatas", "optimización", "métodos formales"], keywords: ["theoretical", "teoría", "algorithm", "algorit", "formal", "logic", "lógica", "computability", "complexity", "matem", "proof", "theorem", "numerical"], tone: "lime", stageRange: "S0–S19" },
  { id: "software", code: "F02", title: "Software, web, móvil y plataformas", subtitle: "De código a sistemas mantenibles", description: "Programación, lenguajes, arquitectura, requisitos, calidad, frontend, backend, móvil, APIs, runtimes, compiladores, plataformas y evolución de software.", topics: ["programación", "arquitectura", "web", "móvil", "APIs", "testing", "compiladores"], keywords: ["software", "developer", "programmer", "programador", "frontend", "backend", "full stack", "web", "mobile", "android", "ios", "react", "angular", "vue", "svelte", "compiler", "language runtime", "application"], tone: "pink", stageRange: "S0–S19 + especialización" },
  { id: "systems", code: "F03", title: "Sistemas, SO y computación distribuida", subtitle: "Del proceso al datacenter", description: "Sistemas operativos, concurrencia, memoria, almacenamiento, virtualización, sistemas distribuidos, consenso, rendimiento y confiabilidad.", topics: ["SO", "kernel", "concurrencia", "storage", "distribuidos", "virtualización", "rendimiento"], keywords: ["operating system", "kernel", "runtime", "distributed", "concurrent", "storage", "filesystem", "virtualization", "hypervisor", "reliability", "performance"], tone: "blue", stageRange: "S3–S19" },
  { id: "hardware", code: "F04", title: "Hardware, arquitectura y semiconductores", subtitle: "Bits, circuitos y aceleradores", description: "Arquitectura de computadores, digital, microprocesadores, FPGA/ASIC, SoC, GPU/NPU, memoria, EDA, firmware y sistemas embebidos.", topics: ["arquitectura", "digital", "FPGA", "ASIC", "SoC", "GPU/NPU", "firmware"], keywords: ["hardware", "computer engineering", "computer architecture", "microprocessor", "fpga", "asic", "rtl", "vlsi", "chip", "semiconductor", "silicon", "pcb", "firmware", "bios", "uefi"], tone: "sand", stageRange: "S0–S19 + frontera" },
  { id: "networks", code: "F05", title: "Internet, redes y telecomunicaciones", subtitle: "De Ethernet a 6G y espacio", description: "Protocolos, routing, switching, DNS/BGP, inalámbrico, radio, óptica, 5G/6G, satélite, SDN/NFV, CDN y redes autónomas.", topics: ["TCP/IP", "BGP", "DNS", "wireless", "5G/6G", "óptica", "satélite"], keywords: ["network", "redes", "telecom", "wireless", "radio", "rf ", "antenna", "5g", "6g", "ran", "voip", "fiber", "optical", "satellite", "dns", "bgp", "cdn", "internet infrastructure"], tone: "cyan", stageRange: "S4–S19 + frontera" },
  { id: "cloud", code: "F06", title: "Cloud, DevOps, SRE y operaciones", subtitle: "Construir y operar producción", description: "Linux, contenedores, Kubernetes, CI/CD, IaC, observabilidad, SRE, plataforma, datacenter, resiliencia, DR y automatización de infraestructura.", topics: ["cloud", "containers", "Kubernetes", "CI/CD", "IaC", "SRE", "observabilidad"], keywords: ["cloud", "devops", "sre", "site reliability", "platform engineer", "kubernetes", "container", "infrastructure", "sysadmin", "administrator", "data center", "observability", "monitoring", "release engineer"], tone: "green", stageRange: "S5–S19 + especialización" },
  { id: "data", code: "F07", title: "Bases de datos, ingeniería de datos y BI", subtitle: "Datos confiables a escala", description: "Modelado, DBMS, SQL/NoSQL, transacciones, data engineering, streaming, warehouse/lakehouse, BI, semántica, gobierno, calidad y lineage.", topics: ["DBMS", "SQL", "NoSQL", "pipelines", "streaming", "BI", "gobierno"], keywords: ["database", "dba", "data engineer", "data platform", "etl", "elt", "warehouse", "lakehouse", "business intelligence", "power bi", "analytics engineer", "data governance", "data quality", "metadata"], tone: "orange", stageRange: "S4–S19 + especialización" },
  { id: "science", code: "F08", title: "Ciencia de datos, estadística y HPC", subtitle: "Modelar, inferir y computar", description: "Estadística, inferencia, experimentación, ciencia de datos, simulación, computación científica, paralela, GPU y supercomputación.", topics: ["estadística", "data science", "experimentos", "simulación", "HPC", "paralelismo", "GPU"], keywords: ["data scientist", "data science", "statistical", "statistic", "quantitative", "computational scientist", "scientific computing", "hpc", "supercomput", "parallel computing", "cuda", "simulation"], tone: "violet", stageRange: "S2–S19 + especialización" },
  { id: "ai", code: "F09", title: "IA, ML y sistemas inteligentes", subtitle: "De aprendizaje automático a agentes", description: "ML, deep learning, IA generativa, modelos fundacionales, LLM, agentes, NLP, visión, voz, evaluación, MLOps, seguridad y gobernanza de IA.", topics: ["ML", "deep learning", "LLM", "agentes", "NLP", "visión", "MLOps"], keywords: ["artificial intelligence", "inteligencia artificial", "ai ", "machine learning", "deep learning", "llm", "foundation model", "generative", "agentic", "agent engineer", "nlp", "language model", "computer vision", "vision ai", "speech", "mlops"], tone: "violet", stageRange: "S7–S19 + frontera" },
  { id: "security", code: "F10", title: "Ciberseguridad, DFIR, criptografía y privacidad", subtitle: "Defender, verificar y responder", description: "Seguridad de sistemas, AppSec, cloud, redes, identidad, DFIR, reversing, criptografía, privacidad y seguridad ofensiva únicamente ética y autorizada.", topics: ["defensa", "AppSec", "DFIR", "crypto", "IAM", "privacy", "pentest ético"], keywords: ["security", "cyber", "ciber", "pentest", "hacker", "forensic", "dfir", "malware", "reverse engineer", "crypt", "privacy", "iam", "identity", "appsec", "soc", "threat", "red team", "blue team"], tone: "orange", stageRange: "S4–S19 + especialización" },
  { id: "human", code: "F11", title: "HCI, UX, gráficos, XR y juegos", subtitle: "Computación para personas", description: "Interacción humano-computador, accesibilidad, UX/UI, visualización, gráficos, rendering, multimedia, juegos, AR/VR/MR y computación espacial.", topics: ["HCI", "UX/UI", "accesibilidad", "gráficos", "XR", "games", "spatial"], keywords: ["hci", "human-computer", "ux", "ui ", "accessibility", "graphics", "render", "shader", "game", "videojuego", "vr ", "ar ", "xr", "spatial", "multimedia", "interaction designer"], tone: "pink", stageRange: "S6–S19 + frontera" },
  { id: "robotics", code: "F12", title: "Robótica, IoT, control y sistemas autónomos", subtitle: "Software que actúa en el mundo", description: "Control, mecatrónica, IoT/CPS, sensores, embedded, percepción, SLAM, navegación, autonomía, drones, vehículos y robótica inteligente.", topics: ["control", "IoT", "embedded", "SLAM", "autonomía", "drones", "robótica"], keywords: ["robot", "robotics", "mecatron", "mechatron", "iot", "embedded", "cyber-physical", "control engineer", "autonomous", "drone", "uav", "slam", "navigation", "adas", "vehicle"], tone: "cyan", stageRange: "S4–S19 + frontera" },
  { id: "enterprise", code: "F13", title: "Sistemas de información, empresa y gobierno TI", subtitle: "Tecnología que mueve organizaciones", description: "IS/IT, arquitectura empresarial, ERP/CRM, ITSM, auditoría, riesgo, gobierno, proyectos, producto, procesos, transformación digital y liderazgo técnico.", topics: ["IS/IT", "ERP/CRM", "ITSM", "gobierno", "auditoría", "producto", "proyectos"], keywords: ["information systems", "sistemas de información", "business informatics", "mis ", "erp", "crm", "sap", "salesforce", "enterprise", "itsm", "service manager", "it governance", "auditor", "project manager", "product manager", "cio", "cto", "ciso", "director", "vp "], tone: "sand", stageRange: "S0–S19 + gestión" },
  { id: "biohealth", code: "F14", title: "Bioinformática, salud y neurocomputación", subtitle: "Computación aplicada a la vida", description: "Bioinformática, genómica, biología computacional, informática médica, salud digital, imágenes médicas, neuroinformática y BCI.", topics: ["bioinformática", "genómica", "health IT", "medical AI", "neuro", "BCI"], keywords: ["bioinform", "computational biology", "genom", "proteom", "health inform", "medical", "clinical", "healthcare", "neuro", "brain-computer", "bci", "drug discovery", "cheminformat", "pharmaco"], tone: "green", stageRange: "S8–S19 + frontera" },
  { id: "earth", code: "F15", title: "Geo, clima, ambiente y agricultura", subtitle: "Computación para el planeta", description: "GIS, geoinformática, remote sensing, clima, sostenibilidad, agricultura de precisión, ciudades inteligentes y ciencia ambiental de datos.", topics: ["GIS", "geospatial", "remote sensing", "climate", "AgriTech", "sustainability"], keywords: ["gis", "geoinformat", "geospatial", "remote sensing", "climate", "environment", "sustainab", "agri", "agricult", "earth observation", "smart city", "urban informatics"], tone: "green", stageRange: "S8–S19 + frontera" },
  { id: "finance", code: "F16", title: "FinTech, blockchain y sistemas económicos", subtitle: "Computación de alta exigencia económica", description: "Sistemas financieros, pagos, quant, baja latencia, trading algorítmico, blockchain, DLT, smart contracts y seguridad financiera.", topics: ["FinTech", "quant", "low latency", "payments", "blockchain", "smart contracts"], keywords: ["fintech", "financial", "quant ", "trading", "payment", "blockchain", "web3", "smart contract", "cryptoeco", "digital banking"], tone: "orange", stageRange: "S8–S19 + especialización" },
  { id: "mission", code: "F17", title: "Sistemas críticos: espacio, industria, transporte y misión", subtitle: "Donde fallar cuesta mucho", description: "Aeroespacio, space systems, automoción, marítimo, industria 4/5, sistemas de misión, tiempo real, safety, confiabilidad y comunicaciones críticas.", topics: ["aeroespacio", "automotive", "maritime", "industry", "real-time", "mission systems"], keywords: ["aerospace", "space ", "satellite software", "mission", "avionics", "automotive", "maritime", "industrial", "industry 4", "manufacturing", "real-time", "defense systems", "c4isr"], tone: "blue", stageRange: "S6–S19 + frontera" },
  { id: "frontier", code: "F18", title: "Frontera: cuántica, neuromórfica, fotónica y futuro", subtitle: "Aprender a investigar lo que todavía cambia", description: "Computación cuántica, post-CMOS, neuromórfica, fotónica, in-memory/analog AI, quantum networks, AGI safety, green computing y arquitecturas futuras.", topics: ["quantum", "neuromorphic", "photonics", "post-CMOS", "AI hardware", "future networks"], keywords: ["quantum", "neuromorph", "photonic", "optical computing", "post-cmos", "non-von-neumann", "memrist", "analog ai", "agi", "superintelligence", "quantum network", "interplanetary", "civilization-scale", "future"], tone: "lime", stageRange: "S15–S19 + investigación permanente" },
]

export const computingErasV43 = [
  { code: "E00", period: "Antes de 1945", title: "Cálculo humano y telecomunicación temprana", text: "Calculistas humanos, lógica matemática, tabulación, tarjetas perforadas, telégrafo, telefonía y raíces de la teoría de la computación.", focus: ["historia", "lógica", "cálculo", "comunicaciones"] },
  { code: "E01", period: "1945–1969", title: "Mainframes, transistores y lenguajes", text: "Arquitecturas almacenadas, ensamblador, FORTRAN/COBOL/Lisp, compiladores, sistemas batch, circuitos digitales y teoría formal.", focus: ["arquitectura", "lenguajes", "compiladores", "mainframe"] },
  { code: "E02", period: "1970–1989", title: "Unix, bases de datos, redes y microcomputación", text: "C/Unix, modelo relacional, Ethernet/TCP-IP, microprocesadores, GUI, ingeniería de software, computación personal y sistemas distribuidos tempranos.", focus: ["Unix", "SQL", "TCP/IP", "microprocesadores"] },
  { code: "E03", period: "1990–2006", title: "Web, móvil, open source y sistemas globales", text: "World Wide Web, Linux, Java/JavaScript, motores de búsqueda, comercio electrónico, Wi-Fi, virtualización y primeras plataformas a escala Internet.", focus: ["web", "Linux", "JavaScript", "virtualización"] },
  { code: "E04", period: "2007–2016", title: "Cloud, smartphones, big data y deep learning", text: "Cloud público, iOS/Android, DevOps, contenedores, Hadoop/Spark, GPU computing, redes sociales a escala y resurgimiento del aprendizaje profundo.", focus: ["cloud", "mobile", "big data", "deep learning"] },
  { code: "E05", period: "2017–2026", title: "Cloud-native, IA fundacional y sistemas agénticos", text: "Kubernetes, platform engineering, MLOps, transformers, modelos fundacionales, RAG, agentes, edge AI, privacidad, supply-chain security y aceleradores especializados.", focus: ["Kubernetes", "LLM", "agentes", "MLOps", "AI hardware"] },
  { code: "E06", period: "2026–2035+", title: "Frontera plausible", text: "IA multimodal/agéntica más verificable, robótica fundacional, 6G/NTN, post-quantum migration, digital twins, chips heterogéneos, computación neuromórfica/fotónica y quantum híbrida.", focus: ["6G", "PQC", "robótica", "neuromórfica", "cuántica"] },
  { code: "E07", period: "Futuro abierto", title: "Lo que aún no tiene nombre", text: "La ruta no declara como hechos tecnologías especulativas. Enseña fundamentos, investigación, evaluación de evidencia y actualización continua para incorporar nuevas disciplinas cuando maduren.", focus: ["investigación", "ética", "evidencia", "adaptación"] },
]

export const evidenceGatesV43 = [
  { code: "G1", title: "Comprensión", text: "Explicar sin apuntes, derivar ideas y responder preguntas de transferencia, no solo repetir definiciones." },
  { code: "G2", title: "Problemas", text: "Resolver conjuntos nuevos con tiempo limitado, justificar complejidad, supuestos, error y límites." },
  { code: "G3", title: "Laboratorio reproducible", text: "Recrear el entorno desde cero, medir, documentar y permitir que otra persona reproduzca el resultado." },
  { code: "G4", title: "Construcción", text: "Crear software, hardware, modelo o sistema funcional con pruebas, observabilidad, seguridad y documentación." },
  { code: "G5", title: "Auditoría", text: "Revisar código/diseño ajeno: calidad, rendimiento, seguridad, accesibilidad, confiabilidad y trade-offs." },
  { code: "G6", title: "Defensa", text: "Defender decisiones técnicas, alternativas y fallos en una presentación oral grabada o ante pares." },
  { code: "G7", title: "Investigación", text: "Leer papers, replicar un resultado, diseñar un experimento, analizar evidencia y escribir un informe técnico." },
  { code: "G8", title: "Contribución", text: "Corregir documentación, tests o código en un proyecto abierto o publicar un artefacto reutilizable propio." },
]

export const grandChallengesV43 = [
  { code: "X01", title: "Construye un computador y su toolchain", text: "Circuitos → ISA → ensamblador → VM → compilador mínimo → programas de usuario.", faculties: ["F01", "F03", "F04"] },
  { code: "X02", title: "Construye un sistema operativo experimental", text: "Boot, memoria, procesos, scheduling, IPC, archivos, red y pruebas de fallos.", faculties: ["F03", "F04", "F10"] },
  { code: "X03", title: "Construye una plataforma distribuida", text: "Replicación, consenso, particiones, observabilidad, pruebas de caos y recuperación.", faculties: ["F03", "F06", "F07"] },
  { code: "X04", title: "Producto full-stack de producción", text: "Web/móvil, API, datos, seguridad, accesibilidad, CI/CD, SLO y operación realista.", faculties: ["F02", "F06", "F10", "F11"] },
  { code: "X05", title: "Plataforma de datos + ML reproducible", text: "Ingesta, calidad, lake/warehouse, feature pipeline, modelo, evaluación, serving y monitoring.", faculties: ["F07", "F08", "F09"] },
  { code: "X06", title: "Sistema ciberfísico autónomo", text: "Sensores, firmware, control, comunicaciones, percepción, seguridad y simulación antes de hardware.", faculties: ["F04", "F05", "F10", "F12"] },
  { code: "X07", title: "Red global simulada", text: "DNS, routing, BGP, CDN, wireless/5G conceptual, fallos, capacidad, seguridad y telemetría.", faculties: ["F05", "F06", "F10"] },
  { code: "X08", title: "Verificación formal de un componente crítico", text: "Especifica propiedades, demuestra invariantes y contrasta prueba formal con testing/fuzzing.", faculties: ["F01", "F02", "F10", "F17"] },
  { code: "X09", title: "Replica un paper", text: "Reproduce datos, método, métricas y resultados; explica discrepancias y publica artefactos reproducibles.", faculties: ["F08", "F09", "F14", "F15", "F18"] },
  { code: "X10", title: "Capstone Omniversity", text: "Un sistema original que cruce al menos seis facultades, con memoria técnica, evaluación, defensa y roadmap de investigación.", faculties: ["F01", "F02", "F03", "F06", "F09", "F10", "F18"] },
]

export const sourcePillarsV43: SourceV43[] = [
  { name: "CS2023", kind: "Estándar curricular", language: "ES", role: "Auditoría del tronco de Ciencias de la Computación", url: "https://csed.acm.org/", tier: "A" },
  { name: "FING UdelaR · Plan 2025", kind: "Plan universitario", language: "ES", role: "Estructura generalista, créditos y formación analítica", url: "https://www.iie.fing.edu.uy/index.php/en/carrera/grado/ingenier%C3%ADa-en-computaci%C3%B3n", tier: "A" },
  { name: "FAMAF · LCC Plan 2026", kind: "Plan universitario", language: "ES", role: "Teoría, algoritmos, sistemas, compiladores y rigor", url: "https://famaf.unc.edu.ar/academica/grado/licenciatura-en-ciencias-de-la-computaci%C3%B3n/", tier: "A" },
  { name: "UNLP · Licenciatura en Informática", kind: "Plan universitario", language: "ES", role: "Algoritmos, arquitectura, distribuidos, software e investigación", url: "https://www.info.unlp.edu.ar/licenciatura-en-informatica-plan-2021/", tier: "A" },
  { name: "SWEBOK V4.0a", kind: "Body of Knowledge", language: "EN→ES", role: "Auditoría de ingeniería de software", url: "https://www.computer.org/education/bodies-of-knowledge/software-engineering", tier: "A" },
  { name: "SEBoK 2.14", kind: "Body of Knowledge", language: "EN→ES", role: "Ingeniería de sistemas y ciclo de vida", url: "https://sebokwiki.org/wiki/Guide_to_the_Systems_Engineering_Body_of_Knowledge_(SEBoK)", tier: "A" },
  { name: "NIST NICE", kind: "Framework profesional", language: "ES", role: "Competencias y roles de ciberseguridad", url: "https://www.nist.gov/itl/applied-cybersecurity/nice/nice-framework-resource-center/nice-framework-current-versions", tier: "A" },
  { name: "OpenFING", kind: "Clases universitarias abiertas", language: "ES", role: "Teoría, clases y ejercicios por materias", url: "https://open.fing.edu.uy/courses/", tier: "B" },
  { name: "FAMAF Resources", kind: "Repositorio académico", language: "ES", role: "Apuntes, guías, parciales y exámenes de LCC", url: "https://github.com/FAMAF-resources/Welcome", tier: "B" },
  { name: "UNLP · archivo teórico-práctico", kind: "Repositorio académico", language: "ES", role: "Material de materias de Licenciatura en Informática", url: "https://gitlab.com/menduinajuan/Licenciatura_en_Informatica_UNLP", tier: "B" },
  { name: "UBA · archivo de CC", kind: "Repositorio académico", language: "ES", role: "Material cursado de Ciencias de la Computación", url: "https://gitlab.com/valn/uba", tier: "B" },
  { name: "UTN FRBA · Ingeniería en Sistemas", kind: "Repositorio académico", language: "ES", role: "Resúmenes y materiales de materias", url: "https://gitlab.com/briancol07/utn", tier: "B" },
  { name: "FIUBA Posgrado IA", kind: "Colección universitaria", language: "ES", role: "IA avanzada, ML, DL, NLP y visión", url: "https://github.com/FIUBA-Posgrado-Inteligencia-Artificial", tier: "B" },
  { name: "OSSU Computer Science", kind: "Currículo abierto", language: "EN→ES", role: "Auditor secundario global de profundidad CS", url: "https://github.com/ossu/computer-science", tier: "C" },
  { name: "OSSU Math", kind: "Currículo abierto", language: "EN→ES", role: "Matemática de respaldo para especializaciones", url: "https://github.com/ossu/math", tier: "C" },
  { name: "OSSU Data Science", kind: "Currículo abierto", language: "EN→ES", role: "Cobertura adicional de ciencia de datos", url: "https://github.com/ossu/data-science", tier: "C" },
  { name: "Full Stack Open", kind: "Práctica universitaria", language: "ES", role: "Full-stack moderno de producción", url: "https://fullstackopen.com/es/", tier: "C" },
  { name: "The Odin Project", kind: "Currículo práctico", language: "EN→ES", role: "Práctica intensiva de desarrollo web", url: "https://www.theodinproject.com/", tier: "C" },
  { name: "freeCodeCamp", kind: "Laboratorios", language: "ES/EN", role: "Práctica interactiva suplementaria", url: "https://www.freecodecamp.org/learn/", tier: "C" },
  { name: "Microsoft Learn", kind: "Documentación + laboratorios", language: "ES", role: "Cloud, datos, IA, seguridad, desarrollo y administración", url: "https://learn.microsoft.com/es-es/training/browse/", tier: "C" },
  { name: "Cisco Networking Academy", kind: "Formación técnica", language: "ES", role: "Redes, Linux, hardware y ciberseguridad", url: "https://www.netacad.com/", tier: "C" },
  { name: "roadmap.sh", kind: "Checklist visual", language: "EN→ES", role: "Auditoría de herramientas y huecos, no fuente académica principal", url: "https://roadmap.sh/", tier: "C" },
  { name: "UOC Ingeniería Informática", kind: "Banco de prácticas", language: "ES", role: "PEC, ejercicios, prácticas y exámenes; complemento", url: "https://github.com/HenestrosaDev/uoc-ingenieria-informatica", tier: "D" },
  { name: "Data Science Research Perú", kind: "Roadmap comunitario", language: "ES", role: "Matemática, datos, Python, ML y recursos de apoyo", url: "https://github.com/DataScienceResearchPeru/OpenSource-RoadMap-DataScience", tier: "D" },
  { name: "Ingeniería de Datos · Caro Acosta", kind: "Ruta práctica", language: "ES", role: "SQL, Python, calidad, pipelines y proyectos modernos", url: "https://github.com/caroacostatovany/ingenieria-de-datos", tier: "D" },
  { name: "Data Engineering Roadmap · Nataya", kind: "Roadmap comunitario", language: "ES/EN", role: "Complemento de herramientas y práctica", url: "https://github.com/natayadev/dataengineering-roadmap", tier: "D" },
  { name: "Plan curricular CS · Jhamil17", kind: "Roadmap comunitario", language: "ES", role: "Contraste de estructura curricular", url: "https://github.com/Jhamil17/plan-curricular-cs", tier: "D" },
  { name: "Roadmap Ingeniero IA · AndresF", kind: "Roadmap comunitario", language: "ES", role: "Contraste de ingeniería de IA", url: "https://github.com/AndresF-GaleanoT/roadmap-ingeniero-ia-spanish", tier: "D" },
  { name: "Plan Ingeniería de Software · PabloRioseco", kind: "Roadmap comunitario", language: "ES", role: "ITSM, observabilidad, software y transición profesional", url: "https://github.com/PabloRioseco/plan-estudio-ingenieria-software", tier: "D" },
  { name: "Autodidactas Devs Path", kind: "Roadmap comunitario", language: "ES", role: "Contraste de ruta de desarrollo", url: "https://github.com/MedinaLeonel/autodidactasdevspath", tier: "D" },
]
