export type ProfessorGuide = {
  level: string
  title: string
  what: string
  why: string
  mentalModel: string
  steps: Array<{ title: string; detail: string; example?: string }>
  vocabulary: Array<{ term: string; meaning: string }>
  checkpoint: string
  practice: string
  commonMistakes: string[]
}

export type GameLessonV47 = {
  id: string
  title: string
  concept: string
  level: string
  summary: string
  why: string
  code: string
  goal: { x: number; y: number }
  start: { x: number; y: number }
  width: number
  height: number
  walls: Array<{ x: number; y: number }>
  gems: Array<{ x: number; y: number }>
  needGems: number
  teacherSteps: Array<{
    title: string
    explanation: string
    action: string
    snippet?: string
  }>
  hints: string[]
}

export const professorGuides: ProfessorGuide[] = [
  {
    level: "L00",
    title: "Cómo piensa un programa",
    what: "Un programa es una secuencia de instrucciones que transforma datos. Antes de aprender sintaxis necesitas reconocer entradas, estados, decisiones, repeticiones y salidas.",
    why: "Si entiendes el proceso antes del lenguaje, puedes cambiar de Python a JavaScript, C, Java o Rust sin volver a aprender a pensar desde cero.",
    mentalModel: "Piensa en una receta: datos de entrada → pasos exactos → decisiones/repeticiones → resultado. La computadora no adivina intenciones; ejecuta instrucciones precisas.",
    steps: [
      { title: "1. Entrada", detail: "Identifica qué información recibe el problema.", example: "precio = 20, cantidad = 3" },
      { title: "2. Estado", detail: "Representa la información que puede cambiar durante la ejecución.", example: "total = 0" },
      { title: "3. Proceso", detail: "Escribe los pasos en orden y prueba mentalmente cada cambio.", example: "total = precio * cantidad" },
      { title: "4. Salida", detail: "Define exactamente qué debe producir el programa.", example: "mostrar total" },
    ],
    vocabulary: [
      { term: "algoritmo", meaning: "secuencia finita de pasos para resolver un problema" },
      { term: "estado", meaning: "conjunto de valores que describen el programa en un momento" },
      { term: "instrucción", meaning: "acción que la computadora puede ejecutar" },
      { term: "traza", meaning: "seguimiento paso a paso de cómo cambian los valores" },
    ],
    checkpoint: "Dado un problema cotidiano, identifica entrada, estado, pasos y salida sin escribir código.",
    practice: "Describe un algoritmo para calcular el costo de una compra con descuento y trázalo con dos ejemplos.",
    commonMistakes: ["empezar a escribir código sin entender la salida", "usar pasos ambiguos como 'haz lo necesario'", "no comprobar el algoritmo con ejemplos"],
  },
  {
    level: "L01",
    title: "Python desde cero",
    what: "Python permite expresar variables, decisiones, bucles, funciones y colecciones con una sintaxis legible. Aquí aprendes las piezas que aparecen en casi todos los lenguajes.",
    why: "Dominar tipos, control de flujo y funciones te permite resolver problemas pequeños sin depender de copiar código.",
    mentalModel: "Una variable es una etiqueta que apunta a un valor; una condición elige un camino; un bucle repite; una función empaqueta una tarea reutilizable.",
    steps: [
      { title: "Valores y tipos", detail: "Distingue texto, números, booleanos y colecciones.", example: "nombre = 'Ada' · edad = 20 · activo = True" },
      { title: "Decisiones", detail: "Usa if/elif/else cuando el programa deba escoger entre caminos.", example: "if edad >= 18: ..." },
      { title: "Repeticiones", detail: "Usa for para recorrer colecciones y while cuando la repetición dependa de una condición." },
      { title: "Funciones", detail: "Usa def para darle nombre a una tarea, recibir parámetros y devolver resultados.", example: "def sumar(a, b): return a + b" },
    ],
    vocabulary: [
      { term: "variable", meaning: "nombre asociado a un valor" },
      { term: "tipo", meaning: "clase de dato y operaciones válidas" },
      { term: "parámetro", meaning: "dato que una función recibe" },
      { term: "return", meaning: "valor que una función entrega al código que la llamó" },
    ],
    checkpoint: "Resuelve un problema nuevo con variables, una decisión, un bucle y una función, y explica cada línea.",
    practice: "Crea un pequeño registro de notas que calcule promedio, estado aprobado/desaprobado y mejor nota.",
    commonMistakes: ["confundir = con comparación", "mala indentación", "crear funciones que dependen de variables globales sin necesidad"],
  },
  {
    level: "L02",
    title: "Pensamiento algorítmico y depuración",
    what: "Programar no es escribir sintaxis: es convertir un problema en subproblemas, formular casos, construir una solución y demostrar que funciona.",
    why: "Esta habilidad determina si puedes resolver problemas nuevos cuando el tutorial ya no existe.",
    mentalModel: "Hipótesis → ejemplo → algoritmo → prueba → fallo → diagnóstico → corrección. Un bug es información sobre una suposición que no se cumplió.",
    steps: [
      { title: "Descompón", detail: "Separa entrada, validación, transformación y salida." },
      { title: "Escribe casos", detail: "Incluye caso normal, vacío, mínimo, máximo y valores inesperados." },
      { title: "Traza", detail: "Sigue variables línea por línea antes de ejecutar." },
      { title: "Prueba y depura", detail: "Aísla el primer punto donde resultado real y esperado se separan." },
    ],
    vocabulary: [
      { term: "caso límite", meaning: "entrada en los extremos o condiciones especiales" },
      { term: "invariante", meaning: "propiedad que debe mantenerse verdadera durante un proceso" },
      { term: "test", meaning: "comprobación reproducible de comportamiento" },
      { term: "debug", meaning: "proceso sistemático de localizar y corregir causas de errores" },
    ],
    checkpoint: "Corrige un programa con varios bugs sin reescribirlo al azar y documenta la causa de cada fallo.",
    practice: "Implementa y prueba un validador de contraseñas con al menos seis casos de prueba.",
    commonMistakes: ["cambiar muchas cosas a la vez", "probar solo el caso feliz", "confundir síntoma con causa"],
  },
  {
    level: "L03",
    title: "JavaScript y modelo de ejecución",
    what: "JavaScript combina funciones, objetos, closures, módulos, eventos y asincronía. Entender su modelo de ejecución evita errores difíciles en aplicaciones web y backend.",
    why: "No basta conocer React o Node: debes entender scope, closures, promesas y event loop para depurar correctamente.",
    mentalModel: "El código síncrono usa una pila de llamadas; las tareas asíncronas esperan fuera y sus callbacks/promesas vuelven cuando la pila queda disponible.",
    steps: [
      { title: "Scope", detail: "Aprende dónde existe una variable y cuánto tiempo vive." },
      { title: "Funciones y closures", detail: "Una función puede recordar variables del entorno donde fue creada." },
      { title: "Promesas", detail: "Representan un resultado futuro: pendiente, cumplido o rechazado." },
      { title: "Event loop", detail: "Comprende por qué el orden de ejecución no siempre coincide con el orden visual del archivo." },
    ],
    vocabulary: [
      { term: "closure", meaning: "función junto al entorno léxico que conserva" },
      { term: "promise", meaning: "representación de un resultado asíncrono" },
      { term: "event loop", meaning: "mecanismo que coordina pila y colas de tareas" },
      { term: "module", meaning: "unidad explícita de código con importaciones y exportaciones" },
    ],
    checkpoint: "Predice el orden de logs en un ejemplo con funciones, Promise y setTimeout y explica por qué.",
    practice: "Construye un pequeño cliente de datos que maneje carga, éxito, error y cancelación.",
    commonMistakes: ["olvidar await", "capturar errores demasiado tarde", "crear estado compartido innecesario"],
  },
  {
    level: "L04",
    title: "Estructuras de datos I",
    what: "Las estructuras organizan datos para que determinadas operaciones sean eficientes: acceso, inserción, búsqueda, eliminación o recorrido.",
    why: "Elegir la estructura incorrecta puede convertir una solución correcta en una solución demasiado lenta o difícil de mantener.",
    mentalModel: "Pregunta primero qué operaciones serán frecuentes y qué garantías necesitas; después elige array, lista, pila, cola, hash map o set.",
    steps: [
      { title: "Array/lista", detail: "Excelente para recorrido y acceso por índice." },
      { title: "Pila/cola", detail: "Modelan LIFO y FIFO para historial, parsing, BFS y sistemas de tareas." },
      { title: "Hash map/set", detail: "Priorizan búsqueda por clave o pertenencia promedio O(1)." },
      { title: "Compara costes", detail: "Anota tiempo y memoria de las operaciones antes de elegir." },
    ],
    vocabulary: [
      { term: "Big-O", meaning: "notación para describir crecimiento asintótico" },
      { term: "LIFO", meaning: "último en entrar, primero en salir" },
      { term: "FIFO", meaning: "primero en entrar, primero en salir" },
      { term: "hash", meaning: "función que transforma una clave en una ubicación" },
    ],
    checkpoint: "Para cinco problemas, elige estructura y justifica coste temporal y espacial.",
    practice: "Implementa historial de navegación, cola de tareas y contador de frecuencias.",
    commonMistakes: ["usar arrays para toda necesidad", "ignorar colisiones/hash", "optimizar antes de medir"],
  },
  {
    level: "L05",
    title: "Algoritmos I",
    what: "Búsqueda, ordenamiento, dos punteros, ventana deslizante, divide y vencerás y greedy son patrones reutilizables para resolver familias completas de problemas.",
    why: "Aprender patrones reduce el problema de 'inventar desde cero' y mejora tu capacidad de analizar alternativas.",
    mentalModel: "Reconoce la forma del problema: orden, rango, parejas, subarray, división o elección local. Luego demuestra por qué el patrón aplica.",
    steps: [
      { title: "Busca restricciones", detail: "El tamaño de entrada sugiere qué complejidad es aceptable." },
      { title: "Reconoce patrón", detail: "Relaciona el problema con estructuras y algoritmos conocidos." },
      { title: "Demuestra", detail: "Explica por qué no se pierden soluciones válidas." },
      { title: "Mide", detail: "Compara implementación, tiempo y memoria con datos reales." },
    ],
    vocabulary: [
      { term: "greedy", meaning: "estrategia que toma decisiones locales buscando una solución global" },
      { term: "divide y vencerás", meaning: "divide en subproblemas, resuelve y combina" },
      { term: "two pointers", meaning: "dos índices coordinados para recorrer una estructura" },
      { term: "sliding window", meaning: "ventana que se expande/contrae manteniendo información incremental" },
    ],
    checkpoint: "Resuelve un problema con dos soluciones y compara complejidad y medición real.",
    practice: "Implementa búsqueda binaria, merge sort y una ventana deslizante, con tests y benchmark.",
    commonMistakes: ["aplicar un patrón sin demostrarlo", "ignorar desbordes/casos vacíos", "confundir complejidad promedio y peor caso"],
  },
  {
    level: "L06",
    title: "Árboles, grafos y algoritmos II",
    what: "Árboles y grafos representan jerarquías y redes. BFS, DFS, Dijkstra, topological sort y programación dinámica permiten navegar y optimizar esas relaciones.",
    why: "Aparecen en rutas, dependencias, compiladores, redes, motores de recomendación, planificación y sistemas distribuidos.",
    mentalModel: "Define nodos, aristas, dirección, peso y objetivo. Después decide cómo explorar o acumular subresultados.",
    steps: [
      { title: "Modela el grafo", detail: "Aclara qué representa cada nodo y cada arista." },
      { title: "Elige recorrido", detail: "BFS para capas/camino no ponderado; DFS para exploración/dependencias." },
      { title: "Pesos", detail: "Usa algoritmos adecuados cuando cada arista tiene coste." },
      { title: "DP", detail: "Memoriza subproblemas superpuestos cuando existe estructura óptima." },
    ],
    vocabulary: [
      { term: "BFS", meaning: "recorrido por amplitud" },
      { term: "DFS", meaning: "recorrido por profundidad" },
      { term: "Dijkstra", meaning: "camino mínimo con pesos no negativos" },
      { term: "DP", meaning: "programación dinámica mediante subproblemas y reutilización" },
    ],
    checkpoint: "Modela un problema real como grafo y justifica algoritmo, complejidad y condiciones.",
    practice: "Construye un planificador de rutas que compare BFS y Dijkstra.",
    commonMistakes: ["marcar visitados en el momento incorrecto", "usar Dijkstra con pesos negativos", "DP sin definir estado y transición"],
  },
  {
    level: "L07",
    title: "Paradigmas y diseño de software",
    what: "Diseñar software consiste en controlar dependencias y responsabilidades. POO, funcional, composición, SOLID y patrones son herramientas, no dogmas.",
    why: "El código de producción cambia. Un diseño útil permite cambiar una parte sin romper las demás.",
    mentalModel: "Agrupa lo que cambia por la misma razón, depende de abstracciones estables y conserva las reglas del dominio separadas de infraestructura.",
    steps: [
      { title: "Responsabilidades", detail: "Cada módulo debe tener una razón clara para cambiar." },
      { title: "Dependencias", detail: "Haz explícitas las relaciones y evita acoplamiento oculto." },
      { title: "Composición", detail: "Prefiere combinar piezas pequeñas antes que jerarquías profundas." },
      { title: "Refactor", detail: "Mejora estructura sin cambiar comportamiento, respaldado por pruebas." },
    ],
    vocabulary: [
      { term: "cohesión", meaning: "grado en que un módulo reúne responsabilidades relacionadas" },
      { term: "acoplamiento", meaning: "dependencia entre componentes" },
      { term: "SOLID", meaning: "principios para diseño orientado a objetos mantenible" },
      { term: "patrón", meaning: "solución reutilizable a un problema recurrente de diseño" },
    ],
    checkpoint: "Refactoriza un sistema pequeño, explica trade-offs y demuestra que las pruebas siguen pasando.",
    practice: "Separa dominio, aplicación e infraestructura en un sistema de pedidos.",
    commonMistakes: ["usar patrones sin problema real", "crear demasiadas capas", "confundir abstracción con complejidad"],
  },
  {
    level: "L08",
    title: "Web desde los fundamentos",
    what: "La web combina protocolo HTTP, documentos HTML, presentación CSS y comportamiento JavaScript sobre un modelo de accesibilidad y seguridad del navegador.",
    why: "Entender la plataforma evita depender totalmente de frameworks y mejora performance, accesibilidad y debugging.",
    mentalModel: "Servidor responde recursos; navegador parsea HTML/CSS, construye árboles, ejecuta JS y responde a eventos del usuario.",
    steps: [
      { title: "HTTP", detail: "Comprende método, URL, headers, status y body." },
      { title: "HTML semántico", detail: "Describe significado antes de apariencia." },
      { title: "CSS", detail: "Domina cascada, box model, layout y responsive." },
      { title: "DOM/eventos", detail: "Conecta estado, interacción y actualización de interfaz." },
    ],
    vocabulary: [
      { term: "DOM", meaning: "representación programable del documento" },
      { term: "semántica", meaning: "significado estructural de los elementos" },
      { term: "HTTP", meaning: "protocolo de aplicación basado en solicitudes y respuestas" },
      { term: "a11y", meaning: "accesibilidad para personas con diversas capacidades y dispositivos" },
    ],
    checkpoint: "Construye una página sin framework que funcione con teclado, móvil y red lenta.",
    practice: "Crea una aplicación con formulario, fetch, estados de carga/error y almacenamiento local.",
    commonMistakes: ["div para todo", "ignorar foco/teclado", "mezclar estado, DOM y red sin estructura"],
  },
  {
    level: "L09",
    title: "TypeScript y frontend moderno",
    what: "TypeScript añade un sistema de tipos estático sobre JavaScript; los frameworks de UI organizan componentes, estado y efectos para interfaces complejas.",
    why: "Los tipos y pruebas reducen errores al crecer el producto y facilitan refactors grandes.",
    mentalModel: "Datos tienen formas explícitas; componentes reciben entradas, producen UI y coordinan estado/efectos de manera predecible.",
    steps: [
      { title: "Modela tipos", detail: "Haz ilegales los estados imposibles cuando sea razonable." },
      { title: "Componentes", detail: "Separa presentación, estado y lógica reutilizable." },
      { title: "Efectos", detail: "Sincroniza con mundo externo de forma controlada." },
      { title: "Mide", detail: "Perfila render, red y bundle antes de optimizar." },
    ],
    vocabulary: [
      { term: "type narrowing", meaning: "refinar un tipo según comprobaciones" },
      { term: "state", meaning: "datos que cambian y afectan la UI" },
      { term: "effect", meaning: "sincronización con algo externo al render puro" },
      { term: "bundle", meaning: "código y recursos enviados al navegador" },
    ],
    checkpoint: "Entrega una SPA tipada, accesible, probada y medida.",
    practice: "Construye un dashboard con formularios, rutas, caché de datos y pruebas de componentes.",
    commonMistakes: ["usar any como salida fácil", "duplicar estado derivable", "optimizar renders sin perfilar"],
  },
  {
    level: "L10",
    title: "Backend, APIs y autenticación",
    what: "Un backend valida solicitudes, aplica reglas, persiste datos, coordina servicios y expone contratos seguros mediante APIs.",
    why: "La confiabilidad y seguridad del producto dependen de que el servidor no confíe ciegamente en el cliente.",
    mentalModel: "request → autenticación → autorización → validación → caso de uso → persistencia/eventos → response + observabilidad.",
    steps: [
      { title: "Contrato", detail: "Define inputs, outputs, errores y versionado." },
      { title: "AuthN/AuthZ", detail: "Distingue quién eres de qué puedes hacer." },
      { title: "Validación", detail: "Rechaza datos inválidos en fronteras." },
      { title: "Observabilidad", detail: "Registra métricas, logs y trazas para diagnosticar producción." },
    ],
    vocabulary: [
      { term: "REST", meaning: "estilo de diseño de APIs basado en recursos y semántica HTTP" },
      { term: "OAuth", meaning: "marco para autorización delegada" },
      { term: "idempotencia", meaning: "repetir una operación produce el mismo efecto final" },
      { term: "rate limit", meaning: "control de frecuencia de solicitudes" },
    ],
    checkpoint: "Diseña y prueba una API con permisos, validación, errores, límites y documentación.",
    practice: "Construye una API de tickets con roles, auditoría, paginación e integración tests.",
    commonMistakes: ["confiar validación al frontend", "guardar secretos en código", "respuestas y errores inconsistentes"],
  },
  {
    level: "L11",
    title: "SQL, modelado y persistencia",
    what: "Persistir datos requiere modelar invariantes, relaciones, transacciones, índices y patrones de acceso; la base no es solo almacenamiento.",
    why: "Un buen modelo evita inconsistencias y mantiene consultas predecibles cuando crece el sistema.",
    mentalModel: "Modelo lógico → restricciones → transacciones → consultas → índices → medición del plan.",
    steps: [
      { title: "Modela entidades", detail: "Identifica claves, relaciones y restricciones." },
      { title: "Normaliza", detail: "Reduce duplicación que cause anomalías de actualización." },
      { title: "Transacciones", detail: "Agrupa cambios que deben tener éxito o fallar juntos." },
      { title: "Índices", detail: "Acelera patrones medidos aceptando coste en escritura/espacio." },
    ],
    vocabulary: [
      { term: "ACID", meaning: "propiedades clásicas de transacciones" },
      { term: "índice", meaning: "estructura adicional para acelerar acceso" },
      { term: "normalización", meaning: "organización para reducir redundancia problemática" },
      { term: "query plan", meaning: "estrategia elegida por el motor para ejecutar una consulta" },
    ],
    checkpoint: "Explica por qué un esquema preserva integridad y demuestra consultas con plan medido.",
    practice: "Modela inventario y ventas con transacciones e índices justificados.",
    commonMistakes: ["indexar todo", "ignorar constraints", "N+1 queries", "usar NoSQL sin necesidad concreta"],
  },
  {
    level: "L12",
    title: "Git, Linux y herramientas del desarrollador",
    what: "El oficio incluye terminal, procesos, permisos, control de versiones, debugging, profiling, CI y documentación reproducible.",
    why: "El código profesional vive en equipos y entornos de producción; no basta con que funcione en tu editor.",
    mentalModel: "Cambio pequeño → commit claro → revisión → pruebas automáticas → artefacto reproducible → observación en ejecución.",
    steps: [
      { title: "Shell", detail: "Navega, combina comandos y comprende procesos/permisos." },
      { title: "Git", detail: "Piensa en commits y referencias, no solo en botones de una GUI." },
      { title: "Debug/profiling", detail: "Observa antes de adivinar." },
      { title: "CI", detail: "Automatiza validaciones que deben repetirse en cada cambio." },
    ],
    vocabulary: [
      { term: "commit", meaning: "snapshot identificado del historial" },
      { term: "branch", meaning: "referencia móvil a una línea de commits" },
      { term: "process", meaning: "instancia en ejecución de un programa" },
      { term: "CI", meaning: "integración continua con validaciones automáticas" },
    ],
    checkpoint: "Resuelve un conflicto Git, depura un fallo y deja un pipeline reproducible.",
    practice: "Trabaja un repositorio con ramas, PR, tests, lint, release y changelog.",
    commonMistakes: ["commits gigantes", "force push sin entender", "scripts que solo funcionan en una máquina"],
  },
  {
    level: "L13",
    title: "C, memoria y sistemas operativos",
    what: "En bajo nivel trabajas con representación, direcciones, memoria, procesos, hilos, archivos, sockets y traducción de código a ejecutable.",
    why: "Comprender estas capas explica rendimiento, fallos de memoria, concurrencia, seguridad y comportamiento de runtimes superiores.",
    mentalModel: "Código fuente → compilación/enlazado → proceso → memoria virtual → syscalls → kernel → hardware.",
    steps: [
      { title: "Representación", detail: "Bits, enteros, floats, bytes y endianness." },
      { title: "Memoria", detail: "Stack, heap, punteros, ownership/lifetimes según lenguaje." },
      { title: "Procesos/hilos", detail: "Aislamiento, scheduling y sincronización." },
      { title: "I/O", detail: "Archivos y sockets como interfaces del sistema." },
    ],
    vocabulary: [
      { term: "pointer", meaning: "valor que referencia una dirección de memoria" },
      { term: "syscall", meaning: "entrada controlada desde proceso a servicios del kernel" },
      { term: "race condition", meaning: "resultado dependiente del interleaving de concurrencia" },
      { term: "undefined behavior", meaning: "situación donde el estándar no impone resultado" },
    ],
    checkpoint: "Explica memoria de un programa, detecta una race y perfila un servidor pequeño.",
    practice: "Implementa un servidor TCP concurrente y compara versiones C/Rust.",
    commonMistakes: ["usar punteros sin ownership claro", "ignorar retorno de syscalls", "confundir concurrencia con paralelismo"],
  },
  {
    level: "L14",
    title: "Redes, concurrencia y sistemas distribuidos",
    what: "Los sistemas distribuidos coordinan procesos conectados por redes donde existen latencia, fallos parciales y ausencia de un reloj global perfecto.",
    why: "Cloud, bases distribuidas y servicios modernos exigen razonar sobre consistencia, replicación y recuperación.",
    mentalModel: "Mensajes pueden retrasarse o perderse; nodos pueden fallar de forma independiente; cada garantía tiene un coste.",
    steps: [
      { title: "Red", detail: "Comprende TCP, timeouts y fronteras de proceso." },
      { title: "Concurrencia", detail: "Protege invariantes sin bloquear de más." },
      { title: "Replicación", detail: "Decide qué consistencia necesitas y cómo recuperas." },
      { title: "Fallas", detail: "Diseña retries, idempotencia, backoff y observabilidad." },
    ],
    vocabulary: [
      { term: "consistencia", meaning: "reglas sobre qué valores pueden observar distintos clientes" },
      { term: "replicación", meaning: "mantener copias de datos/servicio en varios nodos" },
      { term: "consenso", meaning: "acuerdo entre nodos bajo un modelo de fallos" },
      { term: "backoff", meaning: "espera creciente entre reintentos" },
    ],
    checkpoint: "Defiende las garantías de un servicio replicado bajo caída de nodos y partición de red.",
    practice: "Construye un servicio replicado pequeño con fallos simulados y métricas.",
    commonMistakes: ["asumir red confiable", "retries sin idempotencia", "locks distribuidos sin modelo claro"],
  },
  {
    level: "L15",
    title: "Java/Kotlin y .NET a escala",
    what: "Los ecosistemas empresariales añaden runtimes maduros, DI, mensajería, contratos, frameworks de pruebas y herramientas para bases de código grandes.",
    why: "Aprendes a evolucionar software durante años, con equipos múltiples y compatibilidad entre servicios.",
    mentalModel: "Dominio estable + contratos versionados + infraestructura reemplazable + pruebas en varios niveles.",
    steps: [
      { title: "Runtime", detail: "Comprende JVM/CLR, GC y modelos de tipos." },
      { title: "DI", detail: "Inyecta dependencias en fronteras explícitas." },
      { title: "Mensajería", detail: "Usa eventos/colas cuando el acoplamiento temporal deba reducirse." },
      { title: "Contratos", detail: "Versiona APIs y eventos sin romper consumidores." },
    ],
    vocabulary: [
      { term: "DI", meaning: "inyección explícita de dependencias" },
      { term: "GC", meaning: "recolección automática de memoria no alcanzable" },
      { term: "contract test", meaning: "prueba que valida acuerdo entre productor y consumidor" },
      { term: "message broker", meaning: "infraestructura que intermedia mensajes" },
    ],
    checkpoint: "Evoluciona un contrato sin romper consumidores y demuestra pruebas contractuales.",
    practice: "Construye un servicio modular con persistencia, eventos y tests de contrato.",
    commonMistakes: ["framework como arquitectura", "DI container usado como service locator", "eventos sin versionado"],
  },
  {
    level: "L16",
    title: "Móvil y multiplataforma",
    what: "Las apps móviles viven bajo ciclos de vida, recursos limitados, redes intermitentes, permisos, sensores y políticas de plataforma.",
    why: "Una app móvil robusta debe funcionar con suspensión, rotación, offline y variación de tamaño/dispositivo.",
    mentalModel: "UI reactiva + estado persistente + sincronización tolerante a fallos + ciclo de vida controlado.",
    steps: [
      { title: "Ciclo de vida", detail: "Asume que el sistema puede pausar o terminar tu proceso." },
      { title: "Estado", detail: "Separa estado temporal, persistente y servidor." },
      { title: "Offline", detail: "Diseña caché, cola de cambios y reconciliación." },
      { title: "Dispositivo", detail: "Permisos, sensores, energía y tamaños variados." },
    ],
    vocabulary: [
      { term: "offline-first", meaning: "diseño donde el flujo principal tolera ausencia de red" },
      { term: "lifecycle", meaning: "estados por los que atraviesa una app/componente" },
      { term: "deep link", meaning: "URL que abre una ubicación específica de la app" },
      { term: "reconciliación", meaning: "resolver diferencias entre estado local y remoto" },
    ],
    checkpoint: "Demuestra un flujo completo con pérdida de red y restauración de proceso.",
    practice: "Construye cliente móvil offline-first conectado a tu propia API.",
    commonMistakes: ["asumir red permanente", "guardar secretos en almacenamiento inseguro", "ignorar accesibilidad/tamaños"],
  },
  {
    level: "L17",
    title: "Cloud, DevOps, SRE y AppSec",
    what: "Producción exige automatizar build, infraestructura, despliegue, observabilidad, respuesta a fallos y controles de seguridad.",
    why: "Un programa que solo funciona localmente todavía no es un servicio operable.",
    mentalModel: "commit → pipeline → artefacto inmutable → infraestructura declarativa → despliegue → SLO/telemetría → respuesta y aprendizaje.",
    steps: [
      { title: "Contenedores", detail: "Empaqueta runtime y dependencias de forma reproducible." },
      { title: "CI/CD", detail: "Automatiza tests, seguridad y despliegue." },
      { title: "SRE", detail: "Define SLI/SLO y opera según riesgo medible." },
      { title: "AppSec", detail: "Integra secretos, dependencias, permisos y threat modeling desde el ciclo de desarrollo." },
    ],
    vocabulary: [
      { term: "SLO", meaning: "objetivo cuantitativo de confiabilidad" },
      { term: "IaC", meaning: "infraestructura definida y versionada como código" },
      { term: "observabilidad", meaning: "capacidad de inferir estado interno mediante señales" },
      { term: "supply chain", meaning: "cadena de herramientas, dependencias y artefactos del software" },
    ],
    checkpoint: "Opera un despliegue con SLO, alerta, rollback, runbook y prueba de fallo.",
    practice: "Despliega una app con pipeline, IaC, métricas y ejercicio de recuperación.",
    commonMistakes: ["Kubernetes antes de necesitarlo", "alertar por síntomas irrelevantes", "secretos en repositorio"],
  },
  {
    level: "L18",
    title: "Compiladores, runtimes y lenguajes",
    what: "Un lenguaje pasa por análisis léxico/sintáctico, representación intermedia, comprobaciones semánticas y ejecución interpretada, compilada o JIT.",
    why: "Construir un lenguaje pequeño conecta teoría, estructuras, sistemas, optimización y diseño de APIs.",
    mentalModel: "texto → tokens → AST → análisis → IR/bytecode/código máquina → runtime.",
    steps: [
      { title: "Lexer", detail: "Convierte caracteres en tokens con significado léxico." },
      { title: "Parser", detail: "Construye estructura según una gramática." },
      { title: "Semántica", detail: "Resuelve nombres, tipos y reglas del lenguaje." },
      { title: "Runtime", detail: "Ejecuta valores, llamadas, memoria y errores." },
    ],
    vocabulary: [
      { term: "AST", meaning: "árbol sintáctico abstracto" },
      { term: "IR", meaning: "representación intermedia para análisis/transformación" },
      { term: "JIT", meaning: "compilación durante la ejecución" },
      { term: "GC", meaning: "gestión automática de memoria no alcanzable" },
    ],
    checkpoint: "Explica y demuestra cada fase de un lenguaje pequeño.",
    practice: "Implementa lexer, parser e intérprete de expresiones y variables.",
    commonMistakes: ["mezclar parsing con evaluación", "gramática ambigua", "errores sin ubicación/contexto"],
  },
  {
    level: "L19",
    title: "Arquitectura, rendimiento y capstone",
    what: "El dominio avanzado consiste en tomar decisiones con evidencia: arquitectura, seguridad, performance, operación y colaboración open source.",
    why: "El objetivo final no es memorizar tecnologías, sino resolver restricciones reales y defender trade-offs.",
    mentalModel: "requisitos/constraints → alternativas → ADR → prototipo → tests/benchmark → threat model → operación → revisión externa.",
    steps: [
      { title: "Arquitectura", detail: "Decide límites y contratos según fuerzas reales." },
      { title: "Performance", detail: "Mide perfiles y benchmarks reproducibles." },
      { title: "Seguridad", detail: "Modela activos, amenazas y controles." },
      { title: "OSS/capstone", detail: "Entrega código revisable, documentación y contribución real." },
    ],
    vocabulary: [
      { term: "ADR", meaning: "registro de una decisión arquitectónica y su contexto" },
      { term: "benchmark", meaning: "medición controlada y reproducible" },
      { term: "threat model", meaning: "modelo de activos, atacantes, superficies y mitigaciones" },
      { term: "trade-off", meaning: "ganancia en una dimensión a cambio de coste en otra" },
    ],
    checkpoint: "Defiende el capstone ante revisión técnica con evidencia y responde objeciones.",
    practice: "Producto completo con pruebas, telemetría, seguridad, ADRs, benchmark y contribución open source.",
    commonMistakes: ["arquitectura por moda", "benchmarks irreproducibles", "documentación posterior y desconectada"],
  },
]

export const gameLessonsV47: GameLessonV47[] = [
  {
    id: "q0",
    title: "Una instrucción es una orden exacta",
    concept: "secuencia",
    level: "Cero absoluto",
    summary: "Aprende qué significa ejecutar una línea antes de escribir estructuras más complejas.",
    why: "La computadora sigue el orden de las instrucciones. Si el orden cambia, el resultado puede cambiar.",
    code: `hero.moveRight(2);\nhero.moveUp(1);`,
    start: { x: 0, y: 3 }, goal: { x: 2, y: 2 }, width: 5, height: 4,
    walls: [], gems: [{ x: 1, y: 3 }], needGems: 1,
    teacherSteps: [
      { title: "Mira el mapa", explanation: "CM empieza abajo a la izquierda. La meta está dos casillas a la derecha y una arriba.", action: "Antes de escribir, describe el camino con palabras." },
      { title: "Primera línea", explanation: "hero es el personaje. El punto . accede a una acción. moveRight significa mover a la derecha y (2) indica dos pasos.", action: "Escribe la primera instrucción exactamente.", snippet: "hero.moveRight(2);" },
      { title: "Segunda línea", explanation: "Ahora subimos una casilla. Las instrucciones se ejecutan de arriba hacia abajo.", action: "Añade la segunda línea.", snippet: "hero.moveUp(1);" },
      { title: "Ejecuta", explanation: "Pulsa Ejecutar. Observa cada movimiento y compara con lo que predijiste.", action: "Si falla, lee el mensaje y corrige solo la línea responsable." },
    ],
    hints: ["No necesitas variables todavía.", "Primero derecha 2; después arriba 1.", "Cada instrucción termina con ; en JavaScript."],
  },
  {
    id: "q1",
    title: "Variables: poner nombre a un valor",
    concept: "variables",
    level: "Fundamentos",
    summary: "Guarda un número en una variable y reutilízalo en una instrucción.",
    why: "Las variables evitan repetir valores y permiten que el programa cambie según datos.",
    code: `const pasos = 3;\nhero.moveRight(pasos);\nhero.moveUp(2);`,
    start: { x: 0, y: 4 }, goal: { x: 3, y: 2 }, width: 6, height: 5,
    walls: [{ x: 2, y: 3 }], gems: [{ x: 1, y: 4 }, { x: 3, y: 3 }], needGems: 1,
    teacherSteps: [
      { title: "Crea el dato", explanation: "const crea una variable cuyo enlace no se reasigna. pasos es el nombre y 3 es el valor.", action: "Escribe la declaración.", snippet: "const pasos = 3;" },
      { title: "Usa el nombre", explanation: "En lugar de escribir 3 otra vez, pasa la variable a moveRight.", action: "Añade el movimiento.", snippet: "hero.moveRight(pasos);" },
      { title: "Completa la ruta", explanation: "La meta está dos casillas arriba desde la columna 3.", action: "Añade el último movimiento.", snippet: "hero.moveUp(2);" },
      { title: "Experimenta", explanation: "Cambia pasos a 2 o 4 y observa cómo cambia el comportamiento.", action: "Predice antes de ejecutar." },
    ],
    hints: ["Una variable tiene nombre y valor.", "Usa el mismo nombre pasos dentro de los paréntesis.", "Cambia un valor por vez para entender el efecto."],
  },
  {
    id: "q2",
    title: "Condiciones: elegir un camino",
    concept: "if/else",
    level: "Fundamentos",
    summary: "Haz que el programa tome una decisión según una condición booleana.",
    why: "Sin condiciones todos los programas harían siempre exactamente lo mismo.",
    code: `const puertaAbierta = true;\nif (puertaAbierta) {\n  hero.moveRight(2);\n}\nhero.moveUp(2);`,
    start: { x: 0, y: 4 }, goal: { x: 2, y: 2 }, width: 5, height: 5,
    walls: [{ x: 1, y: 3 }], gems: [{ x: 2, y: 4 }], needGems: 1,
    teacherSteps: [
      { title: "Booleano", explanation: "true y false representan dos estados lógicos. Aquí puertaAbierta vale true.", action: "Declara la variable.", snippet: "const puertaAbierta = true;" },
      { title: "Pregunta", explanation: "if evalúa la expresión entre paréntesis. Solo ejecuta el bloque { ... } si es verdadera.", action: "Abre el if.", snippet: "if (puertaAbierta) {" },
      { title: "Acción condicional", explanation: "Este movimiento solo ocurre cuando la condición es verdadera.", action: "Escribe el movimiento y cierra }.", snippet: "  hero.moveRight(2);\n}" },
      { title: "Después del if", explanation: "La última línea está fuera del bloque y se ejecuta siempre.", action: "Añade hero.moveUp(2); y ejecuta." },
    ],
    hints: ["Los bloques se delimitan con { y }.", "Dentro del if la indentación ayuda a leer la estructura.", "Prueba cambiar true por false después de superar la misión."],
  },
  {
    id: "q3",
    title: "Bucles: repetir sin copiar líneas",
    concept: "for",
    level: "Fundamentos",
    summary: "Usa un bucle para repetir una acción varias veces.",
    why: "Los bucles permiten procesar colecciones y repetir tareas sin duplicar código.",
    code: `for (let i = 0; i < 4; i += 1) {\n  hero.moveRight(1);\n}\nhero.moveUp(1);`,
    start: { x: 0, y: 3 }, goal: { x: 4, y: 2 }, width: 6, height: 4,
    walls: [], gems: [{ x: 1, y: 3 }, { x: 3, y: 3 }], needGems: 2,
    teacherSteps: [
      { title: "Contador", explanation: "let i = 0 crea un contador que empieza en cero.", action: "Localiza esa parte en el for." },
      { title: "Condición", explanation: "i < 4 significa: repite mientras i sea menor que 4.", action: "Predice cuántas repeticiones habrá." },
      { title: "Actualización", explanation: "i += 1 aumenta el contador al final de cada vuelta.", action: "Comprueba mentalmente i = 0,1,2,3." },
      { title: "Cuerpo", explanation: "La instrucción dentro de { } se ejecuta en cada repetición.", action: "Ejecuta y mira cuatro movimientos separados." },
    ],
    hints: ["El bucle hace cuatro movimientos de una casilla.", "Después del bucle debes subir una vez.", "Evita i <= 4 porque haría cinco repeticiones."],
  },
  {
    id: "q4",
    title: "Funciones: darle nombre a una estrategia",
    concept: "funciones",
    level: "Fundamentos",
    summary: "Encapsula varios movimientos en una función y reutilízala.",
    why: "Una función permite expresar intención, reutilizar lógica y probar unidades pequeñas.",
    code: `function avanzarEsquina() {\n  hero.moveRight(2);\n  hero.moveUp(1);\n}\n\navanzarEsquina();\navanzarEsquina();`,
    start: { x: 0, y: 4 }, goal: { x: 4, y: 2 }, width: 6, height: 5,
    walls: [], gems: [{ x: 2, y: 3 }, { x: 4, y: 2 }], needGems: 2,
    teacherSteps: [
      { title: "Define", explanation: "function crea una función. avanzarEsquina es el nombre que describe la tarea.", action: "Lee la cabecera antes del bloque." },
      { title: "Cuerpo", explanation: "Las líneas dentro de { } no se ejecutan al definir la función; quedan preparadas.", action: "Identifica las dos instrucciones." },
      { title: "Llama", explanation: "avanzarEsquina(); ejecuta ahora el cuerpo completo.", action: "Observa qué ocurre con una llamada." },
      { title: "Reutiliza", explanation: "La segunda llamada repite la estrategia sin copiar sus líneas internas.", action: "Ejecuta y verifica las dos gemas." },
    ],
    hints: ["Definir no es lo mismo que llamar.", "La función termina al cerrar }.", "Puedes cambiar la función una vez y afectar todas sus llamadas."],
  },
  {
    id: "q5",
    title: "Depuración: encontrar la primera causa",
    concept: "debugging",
    level: "Pensamiento algorítmico",
    summary: "El programa contiene una ruta equivocada. Diagnostica antes de editar.",
    why: "Depurar bien significa localizar la primera diferencia entre lo esperado y lo observado.",
    code: `hero.moveRight(2);\nhero.moveDown(1); // BUG: observa el mapa\nhero.moveRight(2);`,
    start: { x: 0, y: 3 }, goal: { x: 4, y: 2 }, width: 6, height: 5,
    walls: [{ x: 2, y: 4 }], gems: [{ x: 2, y: 3 }, { x: 4, y: 2 }], needGems: 2,
    teacherSteps: [
      { title: "Predice", explanation: "Antes de ejecutar, sigue las coordenadas de cada instrucción en el mapa.", action: "¿Dónde terminaría la segunda línea?" },
      { title: "Ejecuta una vez", explanation: "No cambies nada todavía. Observa en qué paso ocurre el primer comportamiento incorrecto.", action: "Pulsa Ejecutar." },
      { title: "Aísla", explanation: "La primera línea es correcta. La segunda mueve hacia abajo, justo al obstáculo.", action: "Cambia solo moveDown por moveUp." },
      { title: "Verifica", explanation: "Ejecuta de nuevo. Después explica la causa, no solo la corrección.", action: "Describe: esperado, observado, causa, cambio." },
    ],
    hints: ["No reescribas todas las líneas.", "El problema está en la dirección de la segunda instrucción.", "Un buen informe de bug incluye causa y evidencia."],
  },
]
