export type SourceAuthorityV51 = "marco oficial" | "universidad" | "libro abierto" | "documentación oficial" | "currículo abierto" | "repositorio académico" | "biblioteca" | "referencia comercial"
export type SourceUseV51 = "base" | "refuerzo" | "consulta" | "referencia"

export type ProgrammingSourceV51 = {
  id: string
  title: string
  author: string
  authority: SourceAuthorityV51
  language: string
  url: string
  access: string
  license: string
  use: SourceUseV51
  note: string
  tags: string[]
}

export const programmingSourcesV51: ProgrammingSourceV51[] = [
  {
    id: "fing-plan-2025",
    title: "Plan de Estudios de Ingeniería en Computación 2025",
    author: "Facultad de Ingeniería · Universidad de la República (Uruguay)",
    authority: "marco oficial",
    language: "ES",
    url: "https://eva.fing.edu.uy/pluginfile.php/79029/mod_resource/content/4/PlanEstudios_IngComp-2025.pdf",
    access: "PDF público",
    license: "Consulta académica; no redistribuir fuera de sus términos.",
    use: "base",
    note: "Marco para fundamentos, sistemas, ingeniería de software, datos, actividades integradoras y formación de largo plazo.",
    tags: ["fundamentos", "sistemas", "software", "datos", "proyectos"],
  },
  {
    id: "openfing",
    title: "OpenFING",
    author: "Facultad de Ingeniería · Universidad de la República",
    authority: "universidad",
    language: "ES",
    url: "https://open.fing.edu.uy/",
    access: "Clases y materiales públicos",
    license: "Contenido OpenFING publicado con licencias abiertas según cada material.",
    use: "base",
    note: "Clases universitarias de programación, arquitectura, sistemas operativos, redes, bases de datos, ingeniería de software, seguridad y más.",
    tags: ["programación", "algoritmos", "sistemas", "redes", "bases de datos", "software"],
  },
  {
    id: "cs2023",
    title: "Computer Science Curricula 2023",
    author: "ACM · IEEE Computer Society · AAAI",
    authority: "marco oficial",
    language: "EN / versión ES disponible",
    url: "https://csed.acm.org/",
    access: "Informe público",
    license: "Usar como marco de cobertura; no copiar texto protegido.",
    use: "base",
    note: "Cobertura de fundamentos de desarrollo, algoritmos, lenguajes, arquitectura, sistemas, redes, paralelismo, seguridad, ingeniería de software y otras áreas.",
    tags: ["currículo", "programación", "algoritmos", "lenguajes", "sistemas"],
  },
  {
    id: "swebok",
    title: "SWEBOK Guide",
    author: "IEEE Computer Society",
    authority: "marco oficial",
    language: "EN",
    url: "https://www.computer.org/education/bodies-of-knowledge/software-engineering",
    access: "Consulta oficial",
    license: "Usar como marco de conocimiento; no copiar contenido protegido.",
    use: "base",
    note: "Requisitos, diseño, construcción, pruebas, mantenimiento, configuración, calidad, arquitectura, operaciones y seguridad de software.",
    tags: ["ingeniería de software", "testing", "arquitectura", "calidad", "seguridad"],
  },
  {
    id: "ossu-cs",
    title: "OSSU Computer Science",
    author: "Open Source Society University",
    authority: "currículo abierto",
    language: "EN (traducible)",
    url: "https://github.com/ossu/computer-science",
    access: "Repositorio abierto",
    license: "Los cursos enlazados poseen licencias diversas.",
    use: "base",
    note: "Ruta completa de ciencias de la computación: introducción, programación, matemáticas, herramientas, sistemas, teoría, seguridad, aplicaciones, ética, avanzado y proyecto final.",
    tags: ["currículo", "programación", "matemáticas", "sistemas", "teoría"],
  },
  {
    id: "ossu-precollege",
    title: "OSSU Precollege Math",
    author: "Open Source Society University",
    authority: "currículo abierto",
    language: "EN (traducible)",
    url: "https://github.com/ossu/precollege-math",
    access: "Repositorio abierto",
    license: "Recursos enlazados con licencias diversas.",
    use: "refuerzo",
    note: "Base matemática previa cuando un estudiante necesita reconstruir aritmética, álgebra, geometría o precálculo.",
    tags: ["matemáticas", "prerrequisitos"],
  },
  {
    id: "ossu-math",
    title: "OSSU Math",
    author: "Open Source Society University",
    authority: "currículo abierto",
    language: "EN (traducible)",
    url: "https://github.com/ossu/math",
    access: "Repositorio abierto",
    license: "Recursos enlazados con licencias diversas.",
    use: "refuerzo",
    note: "Matemáticas para profundizar demostraciones, discreta, probabilidad, álgebra y madurez matemática.",
    tags: ["matemáticas", "algoritmos", "teoría"],
  },
  {
    id: "ossu-data",
    title: "OSSU Data Science",
    author: "Open Source Society University",
    authority: "currículo abierto",
    language: "EN (traducible)",
    url: "https://github.com/ossu/data-science",
    access: "Repositorio abierto",
    license: "Recursos enlazados con licencias diversas.",
    use: "refuerzo",
    note: "Complemento para programación orientada a datos, estadística, manipulación, análisis y ciencia de datos.",
    tags: ["datos", "python", "estadística"],
  },
  {
    id: "famaf-lcc",
    title: "Licenciatura en Ciencias de la Computación",
    author: "FAMAF · Universidad Nacional de Córdoba",
    authority: "universidad",
    language: "ES",
    url: "https://famaf.unc.edu.ar/academica/grado/licenciatura-en-ciencias-de-la-computaci%C3%B3n/",
    access: "Plan y materias públicos",
    license: "Consulta académica.",
    use: "base",
    note: "Referencia universitaria en español para algoritmos y estructuras, paradigmas, sistemas operativos, redes, teoría y computación.",
    tags: ["algoritmos", "paradigmas", "sistemas", "redes", "teoría"],
  },
  {
    id: "unlp-gitlab",
    title: "Licenciatura en Informática UNLP · materiales",
    author: "Repositorio comunitario de materiales UNLP",
    authority: "repositorio académico",
    language: "ES",
    url: "https://gitlab.com/menduinajuan/Licenciatura_en_Informatica_UNLP",
    access: "Repositorio público",
    license: "Revisar licencia de cada archivo; usar como apoyo, no como autoridad normativa.",
    use: "refuerzo",
    note: "Contenido teórico-práctico organizado por asignaturas de la Licenciatura en Informática.",
    tags: ["universidad", "ejercicios", "apuntes"],
  },
  {
    id: "utn-gitlab",
    title: "Ingeniería en Sistemas UTN · apuntes",
    author: "Repositorio comunitario UTN",
    authority: "repositorio académico",
    language: "ES",
    url: "https://gitlab.com/briancol07/utn",
    access: "Repositorio público",
    license: "Revisar licencia de cada material.",
    use: "refuerzo",
    note: "Apuntes y materiales de algoritmos, arquitectura, sistemas, software, seguridad, lenguajes y materias afines.",
    tags: ["sistemas", "software", "arquitectura", "seguridad"],
  },
  {
    id: "uba-gitlab",
    title: "Ciencias de la Computación UBA · materiales",
    author: "Repositorio comunitario UBA",
    authority: "repositorio académico",
    language: "ES",
    url: "https://gitlab.com/valn/uba",
    access: "Repositorio público",
    license: "Revisar licencia; los apuntes pueden contener errores.",
    use: "refuerzo",
    note: "Materiales de introducción a programación, algoritmos, arquitectura, complejidad, lenguajes formales, paradigmas, sistemas, seguridad e ingeniería de software.",
    tags: ["algoritmos", "teoría", "paradigmas", "sistemas"],
  },
  {
    id: "lcc-gitlab",
    title: "LCC · materiales por año",
    author: "Repositorio comunitario",
    authority: "repositorio académico",
    language: "ES",
    url: "https://gitlab.com/damianarielm/lcc/-/tree/master/1%20Ano?ref_type=heads",
    access: "Repositorio público",
    license: "Revisar licencia de cada archivo.",
    use: "refuerzo",
    note: "Material universitario ordenado por año para contrastar progresión y práctica.",
    tags: ["universidad", "apuntes", "ejercicios"],
  },
  {
    id: "etsiit-gitlab",
    title: "Ingeniería Informática ETSIIT · materiales",
    author: "Repositorio comunitario",
    authority: "repositorio académico",
    language: "ES",
    url: "https://gitlab.com/juanka1995/ingenieria_informatica_etsiit",
    access: "Repositorio público",
    license: "Revisar licencia de cada archivo.",
    use: "refuerzo",
    note: "Materiales de una carrera de Ingeniería Informática para contrastar secuencia y ejercicios.",
    tags: ["universidad", "ingeniería informática"],
  },
  {
    id: "uoc-repo",
    title: "UOC Ingeniería Informática · repositorio de materiales",
    author: "HenestrosaDev",
    authority: "repositorio académico",
    language: "ES",
    url: "https://github.com/HenestrosaDev/uoc-ingenieria-informatica",
    access: "Repositorio público",
    license: "Revisar licencia y derechos de cada archivo antes de reutilizar.",
    use: "refuerzo",
    note: "Repositorio amplio para contrastar materias, práctica y profundidad de una ingeniería informática.",
    tags: ["ingeniería informática", "apuntes", "prácticas"],
  },
  {
    id: "mit-60001",
    title: "6.0001 Introduction to Computer Science and Programming in Python",
    author: "MIT OpenCourseWare",
    authority: "universidad",
    language: "EN (traducible)",
    url: "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/",
    access: "OCW público",
    license: "MIT OCW; respetar atribución y términos.",
    use: "base",
    note: "Introducción desde programación y pensamiento computacional con clases, notas y problemas.",
    tags: ["cero", "python", "programación"],
  },
  {
    id: "mit-6006",
    title: "6.006 Introduction to Algorithms",
    author: "MIT OpenCourseWare",
    authority: "universidad",
    language: "EN (traducible)",
    url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/",
    access: "OCW público",
    license: "MIT OCW; respetar atribución y términos.",
    use: "base",
    note: "Algoritmos, estructuras de datos, análisis y resolución rigurosa de problemas.",
    tags: ["algoritmos", "estructuras", "complejidad"],
  },
  {
    id: "mit-6005",
    title: "Software Construction",
    author: "MIT",
    authority: "universidad",
    language: "EN (traducible)",
    url: "https://web.mit.edu/6.031/www/sp21/",
    access: "Material público",
    license: "Material educativo MIT; enlazar y redactar contenido propio.",
    use: "base",
    note: "Tipos, testing, especificaciones, ADTs, abstracción, concurrencia, networking y construcción robusta.",
    tags: ["software", "testing", "especificaciones", "concurrencia"],
  },
  {
    id: "mit-performance",
    title: "Performance Engineering of Software Systems",
    author: "MIT OpenCourseWare",
    authority: "universidad",
    language: "EN (traducible)",
    url: "https://ocw.mit.edu/courses/6-172-performance-engineering-of-software-systems-fall-2018/",
    access: "OCW público",
    license: "MIT OCW; respetar atribución y términos.",
    use: "base",
    note: "Rendimiento, caché, paralelismo, medición y optimización basada en evidencia.",
    tags: ["performance", "c", "paralelismo"],
  },
  {
    id: "py4e",
    title: "Python para Todos / Python for Everybody",
    author: "Charles R. Severance",
    authority: "libro abierto",
    language: "ES",
    url: "https://www.py4e.com/book.php",
    access: "HTML/PDF/EPUB gratuitos",
    license: "Creative Commons Attribution 4.0 para la edición indicada por el autor.",
    use: "base",
    note: "Introducción accesible a programación con Python y resolución de problemas de información/datos.",
    tags: ["python", "cero", "datos", "ejercicios"],
  },
  {
    id: "think-python",
    title: "Think Python, 3rd edition",
    author: "Allen B. Downey",
    authority: "libro abierto",
    language: "EN (traducible; ediciones previas con traducciones)",
    url: "https://greenteapress.com/wp/think-python-3rd-edition/",
    access: "Versión online gratuita + notebooks",
    license: "CC BY-NC-SA 4.0; enlazar y no incorporar en uso comercial incompatible.",
    use: "base",
    note: "Define términos al introducirlos, progresa por pasos pequeños e incluye ejercicios, testing y notebooks ejecutables.",
    tags: ["python", "pedagogía", "ejercicios", "testing"],
  },
  {
    id: "eloquent-js",
    title: "Eloquent JavaScript, 4th edition",
    author: "Marijn Haverbeke",
    authority: "libro abierto",
    language: "ES disponible",
    url: "https://eloquentjavascript.net/",
    access: "Lectura web gratuita",
    license: "CC BY-NC para texto; código bajo licencia indicada por el autor.",
    use: "base",
    note: "Lenguaje JavaScript, estructuras, funciones, objetos, asincronía, navegador, Node y proyectos.",
    tags: ["javascript", "web", "proyectos"],
  },
  {
    id: "htdp",
    title: "How to Design Programs",
    author: "Felleisen, Findler, Flatt, Krishnamurthi",
    authority: "libro abierto",
    language: "EN (traducible)",
    url: "https://htdp.org/",
    access: "Lectura web",
    license: "La edición web actual indica CC BY-NC-ND; enlazar, no adaptar/copiar dentro del producto.",
    use: "base",
    note: "Referencia pedagógica para diseño sistemático de programas, datos, funciones, pruebas y resolución estructurada.",
    tags: ["diseño de programas", "testing", "funciones", "datos"],
  },
  {
    id: "sicp",
    title: "Structure and Interpretation of Computer Programs",
    author: "Abelson, Sussman et al.",
    authority: "libro abierto",
    language: "EN (traducible)",
    url: "https://mitpress.mit.edu/9780262367622/structure-and-interpretation-of-computer-programs/",
    access: "Edición open access disponible",
    license: "Consultar la licencia de la edición abierta antes de reutilizar.",
    use: "base",
    note: "Abstracción, procedimientos, datos, estado, intérpretes y modelos profundos de computación.",
    tags: ["abstracción", "lenguajes", "paradigmas"],
  },
  {
    id: "ods",
    title: "Open Data Structures",
    author: "Pat Morin",
    authority: "libro abierto",
    language: "EN (traducible)",
    url: "https://opendatastructures.org/",
    access: "Libro y código abiertos",
    license: "CC BY.",
    use: "base",
    note: "Listas, colas, diccionarios, árboles, heaps, sorting, grafos y análisis con implementaciones.",
    tags: ["estructuras", "algoritmos", "complejidad"],
  },
  {
    id: "ostep",
    title: "Operating Systems: Three Easy Pieces",
    author: "Remzi H. Arpaci-Dusseau · Andrea C. Arpaci-Dusseau",
    authority: "libro abierto",
    language: "EN (traducible)",
    url: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
    access: "Capítulos gratuitos online",
    license: "Usar lectura pública y tareas según términos del sitio; no redistribuir indiscriminadamente.",
    use: "base",
    note: "Virtualización, concurrencia, persistencia y seguridad con simuladores, homework y proyectos.",
    tags: ["sistemas operativos", "concurrencia", "memoria", "persistencia"],
  },
  {
    id: "crafting",
    title: "Crafting Interpreters",
    author: "Robert Nystrom",
    authority: "libro abierto",
    language: "EN (traducible)",
    url: "https://craftinginterpreters.com/",
    access: "Libro completo en web",
    license: "Lectura web gratuita; respetar copyright y no copiar extensamente.",
    use: "base",
    note: "Construcción de lenguaje, scanner, parser, AST, resolución, bytecode, máquina virtual y garbage collection.",
    tags: ["compiladores", "intérpretes", "vm", "gc"],
  },
  {
    id: "pro-git",
    title: "Pro Git, 2nd edition",
    author: "Scott Chacon · Ben Straub",
    authority: "libro abierto",
    language: "ES",
    url: "https://git-scm.com/book/es/v2",
    access: "HTML y descargas gratuitas",
    license: "CC BY-NC-SA 3.0.",
    use: "base",
    note: "Git desde fundamentos hasta branching, colaboración, depuración, internals y administración.",
    tags: ["git", "herramientas", "colaboración"],
  },
  {
    id: "mdn",
    title: "MDN Learn Web Development",
    author: "Mozilla / MDN contributors",
    authority: "documentación oficial",
    language: "ES",
    url: "https://developer.mozilla.org/es/docs/Learn_web_development",
    access: "Documentación pública",
    license: "Contenido MDN bajo licencias indicadas por MDN.",
    use: "base",
    note: "Ruta para principiantes con entorno, archivos, línea de comandos, HTML, CSS, JavaScript, web y herramientas.",
    tags: ["web", "html", "css", "javascript", "principiantes"],
  },
  {
    id: "python-docs",
    title: "Tutorial oficial de Python",
    author: "Python Software Foundation",
    authority: "documentación oficial",
    language: "ES",
    url: "https://docs.python.org/es/3/tutorial/",
    access: "Documentación pública",
    license: "PSF Documentation License / términos del proyecto.",
    use: "base",
    note: "Fuente normativa para sintaxis, estructuras, módulos, errores, clases y biblioteca estándar de Python.",
    tags: ["python", "referencia", "sintaxis"],
  },
  {
    id: "rust-book",
    title: "The Rust Programming Language",
    author: "Rust Project",
    authority: "documentación oficial",
    language: "EN + traducciones comunitarias",
    url: "https://doc.rust-lang.org/book/",
    access: "Libro oficial online",
    license: "Licencias del proyecto Rust.",
    use: "base",
    note: "Ownership, tipos, errores, traits, testing, concurrencia, macros, unsafe y proyectos.",
    tags: ["rust", "sistemas", "tipos", "concurrencia"],
  },
  {
    id: "comprehensive-rust",
    title: "Comprehensive Rust",
    author: "Google Android team",
    authority: "currículo abierto",
    language: "ES",
    url: "https://google.github.io/comprehensive-rust/es/",
    access: "Curso y PDF gratuitos",
    license: "Consultar licencia del repositorio/documentación.",
    use: "refuerzo",
    note: "Rust desde sintaxis básica hasta genéricos, errores y temas avanzados; útil después de dominar fundamentos de programación.",
    tags: ["rust", "sistemas", "ejercicios"],
  },
  {
    id: "missing-semester",
    title: "The Missing Semester of Your CS Education",
    author: "MIT",
    authority: "universidad",
    language: "EN (traducible)",
    url: "https://missing.csail.mit.edu/",
    access: "Notas y videos públicos",
    license: "Material educativo público; revisar licencia de cada recurso.",
    use: "base",
    note: "Shell, editores, depuración, profiling, Git, automatización, packaging y herramientas de trabajo real.",
    tags: ["terminal", "git", "debug", "tooling"],
  },
  {
    id: "nand2tetris",
    title: "Nand to Tetris",
    author: "Noam Nisan · Shimon Schocken",
    authority: "currículo abierto",
    language: "EN (traducible)",
    url: "https://www.nand2tetris.org/",
    access: "Materiales y proyectos públicos",
    license: "Uso educativo según términos del proyecto; no publicar soluciones.",
    use: "base",
    note: "Proyectos para construir hardware, ensamblador, VM, compilador y sistema operativo desde primeros principios.",
    tags: ["arquitectura", "vm", "compiladores", "sistemas"],
  },
  {
    id: "fullstackopen",
    title: "Full Stack Open",
    author: "University of Helsinki",
    authority: "universidad",
    language: "ES",
    url: "https://fullstackopen.com/es/",
    access: "Curso gratuito",
    license: "CC BY-NC-SA según el curso.",
    use: "base",
    note: "React, Node, testing, TypeScript, GraphQL, CI/CD, contenedores y bases de datos; se usa después de fundamentos.",
    tags: ["web", "typescript", "backend", "testing", "devops"],
  },
  {
    id: "odin",
    title: "The Odin Project",
    author: "The Odin Project",
    authority: "currículo abierto",
    language: "EN (traducible)",
    url: "https://www.theodinproject.com/",
    access: "Currículo gratuito",
    license: "Currículo con licencia abierta/no comercial según repositorio; enlazar y respetar términos.",
    use: "refuerzo",
    note: "Fundamentos y rutas full-stack con lecciones y proyectos, útil para secuenciar práctica web real.",
    tags: ["web", "javascript", "git", "proyectos"],
  },
  {
    id: "freecodecamp",
    title: "freeCodeCamp",
    author: "freeCodeCamp",
    authority: "currículo abierto",
    language: "ES parcial / EN",
    url: "https://www.freecodecamp.org/",
    access: "Currículo gratuito",
    license: "Código y contenido bajo licencias indicadas por el proyecto.",
    use: "refuerzo",
    note: "Práctica extensa de programación, web, JavaScript, Python, bases de datos y proyectos.",
    tags: ["práctica", "web", "python", "javascript"],
  },
  {
    id: "roadmap",
    title: "roadmap.sh",
    author: "roadmap.sh community",
    authority: "currículo abierto",
    language: "EN (traducible)",
    url: "https://roadmap.sh/",
    access: "Roadmaps públicos",
    license: "Consultar términos/licencia del proyecto.",
    use: "consulta",
    note: "Mapas de Computer Science, Python, C, C++, Rust, Go, frontend, backend, DevOps, seguridad, datos, system design y más.",
    tags: ["mapas", "especialización", "software"],
  },
  {
    id: "microsoft-learn",
    title: "Microsoft Learn",
    author: "Microsoft",
    authority: "documentación oficial",
    language: "ES",
    url: "https://learn.microsoft.com/es-es/training/browse/",
    access: "Rutas y módulos gratuitos",
    license: "Consulta y aprendizaje según términos de Microsoft Learn.",
    use: "refuerzo",
    note: "C#, .NET, Git/GitHub, Azure, DevOps, datos y desarrollo profesional con módulos guiados.",
    tags: ["csharp", "dotnet", "git", "cloud", "devops"],
  },
  {
    id: "netacad",
    title: "Cisco Networking Academy",
    author: "Cisco",
    authority: "currículo abierto",
    language: "ES / varios",
    url: "https://www.netacad.com/",
    access: "Cursos gratuitos y de acceso educativo según oferta",
    license: "Material propietario para aprendizaje; enlazar, no copiar.",
    use: "refuerzo",
    note: "Programación, redes, ciberseguridad, IA y datos; especialmente útil para networking y automatización.",
    tags: ["redes", "seguridad", "python"],
  },
  {
    id: "uned",
    title: "UNED Abierta",
    author: "Universidad Nacional de Educación a Distancia",
    authority: "universidad",
    language: "ES",
    url: "https://unedabierta.uned.es/",
    access: "MOOC y recursos abiertos",
    license: "Según cada recurso.",
    use: "refuerzo",
    note: "Repositorio universitario abierto para complementar fundamentos y áreas tecnológicas.",
    tags: ["universidad", "mooc", "español"],
  },
  {
    id: "midudev-books",
    title: "librosgratis.dev / libros-programacion-gratis",
    author: "midudev y comunidad",
    authority: "biblioteca",
    language: "ES",
    url: "https://github.com/midudev/libros-programacion-gratis",
    access: "Índice de recursos gratuitos",
    license: "Cada recurso conserva su propia licencia; verificar antes de reutilizar.",
    use: "consulta",
    note: "Biblioteca viva de fundamentos, algoritmos, lenguajes, web, Git, Linux, bases de datos, sistemas y metodologías.",
    tags: ["libros", "pdf", "español"],
  },
  {
    id: "free-books",
    title: "Free Programming Books · Español",
    author: "EbookFoundation",
    authority: "biblioteca",
    language: "ES",
    url: "https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-es.md",
    access: "Índice abierto",
    license: "Cada recurso enlazado tiene su propia licencia.",
    use: "consulta",
    note: "Índice curado de libros/recursos gratuitos sobre algoritmos, bases de datos, teoría, IA, software, sistemas y numerosos lenguajes.",
    tags: ["libros", "pdf", "lenguajes", "español"],
  },
  {
    id: "openlibro",
    title: "OpenLibro",
    author: "OpenLibro",
    authority: "biblioteca",
    language: "ES",
    url: "https://openlibro.com/",
    access: "Biblioteca de libros abiertos/gratuitos",
    license: "Verificar licencia de cada libro antes de reutilizar.",
    use: "consulta",
    note: "Fuente para localizar textos técnicos disponibles legalmente de forma gratuita.",
    tags: ["libros", "pdf", "español"],
  },
  {
    id: "data-roadmap-peru",
    title: "OpenSource RoadMap Data Science",
    author: "Data Science Research Perú",
    authority: "currículo abierto",
    language: "ES",
    url: "https://github.com/DataScienceResearchPeru/OpenSource-RoadMap-DataScience",
    access: "Repositorio público",
    license: "Revisar licencia del repositorio y recursos enlazados.",
    use: "refuerzo",
    note: "Complemento en español para programación aplicada a datos y ciencia de datos.",
    tags: ["datos", "python", "roadmap"],
  },
  {
    id: "uoc-autodidacta",
    title: "Autodidactas Devs Path",
    author: "MedinaLeonel",
    authority: "currículo abierto",
    language: "ES",
    url: "https://github.com/MedinaLeonel/autodidactasdevspath",
    access: "Repositorio público",
    license: "Revisar licencia del repositorio y recursos enlazados.",
    use: "consulta",
    note: "Mapa autodidacta comunitario para contrastar secuencia y recursos.",
    tags: ["roadmap", "autodidacta"],
  },
  {
    id: "plan-cs-es",
    title: "Plan curricular CS",
    author: "Jhamil17",
    authority: "currículo abierto",
    language: "ES",
    url: "https://github.com/Jhamil17/plan-curricular-cs",
    access: "Repositorio público",
    license: "Revisar licencia del repositorio y recursos enlazados.",
    use: "consulta",
    note: "Propuesta curricular comunitaria en español para contrastar cobertura de Computer Science.",
    tags: ["currículo", "computer science"],
  },
  {
    id: "ia-roadmap-es",
    title: "Roadmap Ingeniero IA Spanish",
    author: "AndresF-GaleanoT",
    authority: "currículo abierto",
    language: "ES",
    url: "https://github.com/AndresF-GaleanoT/roadmap-ingeniero-ia-spanish",
    access: "Repositorio público",
    license: "Revisar licencia del repositorio y recursos enlazados.",
    use: "consulta",
    note: "Complemento para la frontera de programación aplicada a IA; no sustituye los fundamentos.",
    tags: ["ia", "ml", "roadmap"],
  },
  {
    id: "software-plan-es",
    title: "Plan de estudio Ingeniería de Software",
    author: "PabloRioseco",
    authority: "currículo abierto",
    language: "ES",
    url: "https://github.com/PabloRioseco/plan-estudio-ingenieria-software",
    access: "Repositorio público",
    license: "Revisar licencia del repositorio y recursos enlazados.",
    use: "consulta",
    note: "Contraste comunitario para requisitos, diseño, construcción, calidad, arquitectura y práctica profesional.",
    tags: ["software", "arquitectura", "testing"],
  },
  {
    id: "data-eng-roadmap",
    title: "Data Engineering Roadmap",
    author: "natayadev",
    authority: "currículo abierto",
    language: "ES / EN",
    url: "https://github.com/natayadev/dataengineering-roadmap",
    access: "Repositorio público",
    license: "Revisar licencia del repositorio y recursos enlazados.",
    use: "consulta",
    note: "Complemento para ingeniería de datos, pipelines, almacenamiento, procesamiento y plataforma.",
    tags: ["data engineering", "pipelines", "cloud"],
  },
  {
    id: "data-eng-es",
    title: "Ingeniería de Datos",
    author: "caroacostatovany",
    authority: "currículo abierto",
    language: "ES",
    url: "https://github.com/caroacostatovany/ingenieria-de-datos",
    access: "Repositorio público",
    license: "Revisar licencia del repositorio y recursos enlazados.",
    use: "consulta",
    note: "Material comunitario en español para complementar la rama de datos.",
    tags: ["data engineering", "español"],
  },
  {
    id: "google-eng-practices",
    title: "Google Engineering Practices",
    author: "Google",
    authority: "documentación oficial",
    language: "EN (traducible)",
    url: "https://google.github.io/eng-practices/",
    access: "Documentación pública",
    license: "CC BY 3.0.",
    use: "base",
    note: "Prácticas públicas de revisión de código, cambios pequeños, calidad, diseño y colaboración.",
    tags: ["code review", "calidad", "colaboración"],
  },
]

export const commercialReferencesV51 = [
  "Code — Charles Petzold, 2.ª ed.",
  "Programming: Principles and Practice Using C++ — Bjarne Stroustrup, 3.ª ed.",
  "Introduction to Algorithms — Cormen, Leiserson, Rivest & Stein, 4.ª ed.",
  "Computer Systems: A Programmer's Perspective — Bryant & O'Hallaron, 3.ª ed.",
  "Concepts, Techniques, and Models of Computer Programming — Van Roy & Haridi",
  "Code Complete — Steve McConnell, 2.ª ed.",
  "The Pragmatic Programmer — Hunt & Thomas",
  "Refactoring — Martin Fowler, 2.ª ed.",
  "A Philosophy of Software Design — John Ousterhout, 2.ª ed.",
  "Test-Driven Development: By Example — Kent Beck",
  "Software Engineering at Google — Winters, Manshreck & Wright",
  "Fundamentals of Software Architecture — Richards & Ford",
  "Designing Data-Intensive Applications — Martin Kleppmann",
  "AI Engineering — Chip Huyen",
] as const

export const sourceByIdV51 = (id: string) => programmingSourcesV51.find((source) => source.id === id)
