export type LanguageItem = {
  name: string
  slug: string
  family: string
  status: "principal" | "complementario" | "histórico" | "especializado"
}

export type AcademyLevel = {
  code: string
  phase: string
  title: string
  summary: string
  languages: string[]
  topics: string[]
  project: string
  gate: string
}

export type PracticeResource = {
  name: string
  kind: string
  scope: string
  url: string
  note: string
}

export const languageCatalog: LanguageItem[] = [
  { name: "Python", slug: "python", family: "General · IA · datos", status: "principal" },
  { name: "JavaScript", slug: "javascript", family: "Web · general", status: "principal" },
  { name: "TypeScript", slug: "typescript", family: "Web · aplicaciones", status: "principal" },
  { name: "Java", slug: "openjdk", family: "Empresa · backend", status: "principal" },
  { name: "C", slug: "c", family: "Sistemas · embebidos", status: "principal" },
  { name: "C++", slug: "cplusplus", family: "Sistemas · juegos · HPC", status: "principal" },
  { name: "C#", slug: "dotnet", family: "Empresa · juegos · apps", status: "principal" },
  { name: "Go", slug: "go", family: "Cloud · backend", status: "principal" },
  { name: "Rust", slug: "rust", family: "Sistemas · seguridad", status: "principal" },
  { name: "PHP", slug: "php", family: "Web · backend", status: "principal" },
  { name: "Ruby", slug: "ruby", family: "Web · scripting", status: "principal" },
  { name: "Swift", slug: "swift", family: "Apple · móvil", status: "principal" },
  { name: "Kotlin", slug: "kotlin", family: "Android · JVM", status: "principal" },
  { name: "Dart", slug: "dart", family: "Flutter · móvil", status: "principal" },
  { name: "R", slug: "r", family: "Estadística · datos", status: "principal" },
  { name: "Julia", slug: "julia", family: "Ciencia · numérico", status: "principal" },
  { name: "Scala", slug: "scala", family: "JVM · datos", status: "complementario" },
  { name: "Haskell", slug: "haskell", family: "Funcional · teoría", status: "complementario" },
  { name: "Elixir", slug: "elixir", family: "Concurrente · backend", status: "complementario" },
  { name: "Erlang", slug: "erlang", family: "Concurrente · telecom", status: "complementario" },
  { name: "Clojure", slug: "clojure", family: "Funcional · JVM", status: "complementario" },
  { name: "F#", slug: "fsharp", family: "Funcional · .NET", status: "complementario" },
  { name: "OCaml", slug: "ocaml", family: "Funcional · compiladores", status: "complementario" },
  { name: "Lua", slug: "lua", family: "Scripting · juegos", status: "complementario" },
  { name: "Perl", slug: "perl", family: "Scripting · texto", status: "histórico" },
  { name: "Bash", slug: "gnubash", family: "Shell · DevOps", status: "principal" },
  { name: "PowerShell", slug: "powershell", family: "Windows · automatización", status: "principal" },
  { name: "Zig", slug: "zig", family: "Sistemas · emergente", status: "especializado" },
  { name: "Nim", slug: "nim", family: "Sistemas · general", status: "especializado" },
  { name: "Crystal", slug: "crystal", family: "General · backend", status: "especializado" },
  { name: "Groovy", slug: "apachegroovy", family: "JVM · automatización", status: "complementario" },
  { name: "Solidity", slug: "solidity", family: "Smart contracts", status: "especializado" },
  { name: "V", slug: "v", family: "Sistemas · emergente", status: "especializado" },
  { name: "Assembly", slug: "assemblyscript", family: "Bajo nivel", status: "especializado" },
  { name: "Fortran", slug: "fortran", family: "Ciencia · HPC", status: "histórico" },
  { name: "COBOL", slug: "ibm", family: "Mainframe · legado", status: "histórico" },
  { name: "Ada", slug: "ada", family: "Crítico · aeroespacial", status: "especializado" },
  { name: "Pascal", slug: "delphi", family: "Fundamentos · legado", status: "histórico" },
  { name: "Delphi/Object Pascal", slug: "delphi", family: "Desktop · legado", status: "histórico" },
  { name: "Objective-C", slug: "apple", family: "Apple · legado", status: "histórico" },
  { name: "Visual Basic", slug: "dotnet", family: ".NET · empresa", status: "histórico" },
  { name: "MATLAB", slug: "mathworks", family: "Ingeniería · numérico", status: "especializado" },
  { name: "GNU Octave", slug: "octave", family: "Numérico · ciencia", status: "especializado" },
  { name: "SAS", slug: "sas", family: "Estadística · empresa", status: "especializado" },
  { name: "SQL", slug: "postgresql", family: "Datos · consultas", status: "principal" },
  { name: "PL/SQL", slug: "oracle", family: "Oracle · datos", status: "especializado" },
  { name: "T-SQL", slug: "microsoftsqlserver", family: "SQL Server · datos", status: "especializado" },
  { name: "GraphQL", slug: "graphql", family: "APIs · consultas", status: "complementario" },
  { name: "HTML", slug: "html5", family: "Web · marcado", status: "principal" },
  { name: "CSS", slug: "css", family: "Web · estilos", status: "principal" },
  { name: "Sass", slug: "sass", family: "Web · estilos", status: "complementario" },
  { name: "WebAssembly", slug: "webassembly", family: "Web · bajo nivel", status: "especializado" },
  { name: "Racket", slug: "racket", family: "Educación · lenguajes", status: "complementario" },
  { name: "Scheme", slug: "scheme", family: "Funcional · teoría", status: "histórico" },
  { name: "Common Lisp", slug: "commonlisp", family: "Funcional · IA histórica", status: "histórico" },
  { name: "Prolog", slug: "prolog", family: "Lógica · IA", status: "especializado" },
  { name: "Smalltalk", slug: "smalltalk", family: "POO · historia", status: "histórico" },
  { name: "Scratch", slug: "scratch", family: "Bloques · inicio", status: "complementario" },
  { name: "Blockly", slug: "blockly", family: "Bloques · lógica", status: "complementario" },
  { name: "Arduino", slug: "arduino", family: "Embebidos · C/C++", status: "complementario" },
  { name: "VHDL", slug: "vhdl", family: "Hardware · HDL", status: "especializado" },
  { name: "Verilog", slug: "verilog", family: "Hardware · HDL", status: "especializado" },
  { name: "SystemVerilog", slug: "verilog", family: "Hardware · verificación", status: "especializado" },
  { name: "GDScript", slug: "godotengine", family: "Godot · juegos", status: "complementario" },
  { name: "Shader / GLSL", slug: "opengl", family: "Gráficos · GPU", status: "especializado" },
  { name: "CUDA", slug: "nvidia", family: "GPU · HPC", status: "especializado" },
  { name: "OpenCL", slug: "opencl", family: "GPU · paralelo", status: "especializado" },
  { name: "Apex", slug: "salesforce", family: "Salesforce", status: "especializado" },
  { name: "ABAP", slug: "sap", family: "SAP · empresa", status: "especializado" },
  { name: "Hack", slug: "hackthebox", family: "Web · Meta", status: "especializado" },
  { name: "Cairo", slug: "starknet", family: "Blockchain · pruebas", status: "especializado" },
  { name: "Move", slug: "sui", family: "Blockchain", status: "especializado" },
  { name: "Q#", slug: "microsoftazure", family: "Computación cuántica", status: "especializado" },
  { name: "Wolfram Language", slug: "wolframlanguage", family: "Simbólico · ciencia", status: "especializado" },
  { name: "LabVIEW", slug: "labview", family: "Instrumentación", status: "especializado" },
]

export const academyLevels: AcademyLevel[] = [
  { code: "L00", phase: "Cero absoluto", title: "Cómo piensa un programa", summary: "Computadora, instrucciones, datos, estados, entrada/salida, algoritmos cotidianos y trazado manual.", languages: ["Pseudocódigo", "Blockly", "Python"], topics: ["secuencias", "variables", "booleanos", "diagramas", "trazas", "errores"], project: "Simulador visual de instrucciones y decisiones.", gate: "Explicar un algoritmo sin código y predecir su salida." },
  { code: "L01", phase: "Fundamentos", title: "Python desde cero", summary: "Sintaxis básica, tipos, operadores, condicionales, bucles, funciones y colecciones.", languages: ["Python"], topics: ["tipos", "if", "for/while", "funciones", "listas", "diccionarios"], project: "Juego de texto con inventario y decisiones.", gate: "Resolver ejercicios nuevos sin copiar." },
  { code: "L02", phase: "Fundamentos", title: "Pensamiento algorítmico", summary: "Descomposición, invariantes, casos límite, depuración, pruebas y razonamiento paso a paso.", languages: ["Python", "JavaScript"], topics: ["trazas", "debug", "tests", "edge cases", "recursión", "complejidad inicial"], project: "Motor de retos con casos de prueba.", gate: "Detectar y corregir errores deliberados." },
  { code: "L03", phase: "Lenguaje", title: "JavaScript y el modelo de ejecución", summary: "Funciones, objetos, arrays, closures, módulos, asincronía y eventos.", languages: ["JavaScript"], topics: ["scope", "closures", "promises", "async/await", "módulos", "event loop"], project: "Aplicación interactiva sin framework.", gate: "Explicar sincronía vs asincronía y depurar una carrera simple." },
  { code: "L04", phase: "CS núcleo", title: "Estructuras de datos I", summary: "Arrays, listas, pilas, colas, hash maps, sets y análisis de operaciones.", languages: ["Python", "JavaScript", "C++"], topics: ["arrays", "linked lists", "stack", "queue", "hash", "Big-O"], project: "Biblioteca de estructuras con tests y benchmarks.", gate: "Elegir estructura por coste y justificarla." },
  { code: "L05", phase: "CS núcleo", title: "Algoritmos I", summary: "Búsqueda, ordenamiento, dos punteros, sliding window, divide y vencerás y greedy.", languages: ["Python", "C++"], topics: ["binary search", "sorting", "two pointers", "window", "divide & conquer", "greedy"], project: "Visualizador de algoritmos y comparador de rendimiento.", gate: "Resolver problemas con análisis temporal/espacial." },
  { code: "L06", phase: "CS núcleo", title: "Árboles, grafos y algoritmos II", summary: "BST, heaps, tries, BFS/DFS, caminos mínimos, MST, topological sort y programación dinámica.", languages: ["Python", "C++", "Java"], topics: ["trees", "heaps", "graphs", "BFS/DFS", "Dijkstra", "DP"], project: "Motor de rutas con múltiples algoritmos.", gate: "Comparar algoritmos y probar correctitud." },
  { code: "L07", phase: "Diseño", title: "Paradigmas y diseño de software", summary: "POO, funcional, composición, inmutabilidad, SOLID, patrones y refactor.", languages: ["Java", "C#", "TypeScript", "Python"], topics: ["OOP", "FP", "SOLID", "patterns", "DDD básico", "refactor"], project: "Sistema modular con adaptadores intercambiables.", gate: "Defender decisiones de diseño con trade-offs." },
  { code: "L08", phase: "Web", title: "Web desde los fundamentos", summary: "HTTP, HTML semántico, CSS, accesibilidad, DOM, formularios, fetch y responsive.", languages: ["HTML", "CSS", "JavaScript"], topics: ["HTTP", "semantic HTML", "CSS", "DOM", "a11y", "responsive"], project: "Aplicación web accesible sin framework.", gate: "Navegación por teclado y validación de red." },
  { code: "L09", phase: "Frontend", title: "TypeScript y frontend moderno", summary: "Tipos, componentes, estado, rutas, formularios, testing, performance y diseño de sistemas.", languages: ["TypeScript", "React"], topics: ["types", "components", "state", "testing", "performance", "design systems"], project: "SPA compleja con pruebas y accesibilidad.", gate: "Auditoría de bundle, UX y pruebas." },
  { code: "L10", phase: "Backend", title: "Backend, APIs y autenticación", summary: "REST, GraphQL, auth, permisos, validación, colas, eventos y observabilidad.", languages: ["Node.js", "Python", "Go"], topics: ["REST", "GraphQL", "auth", "queues", "events", "observability"], project: "API segura documentada con OpenAPI.", gate: "Pruebas de integración y threat model básico." },
  { code: "L11", phase: "Datos", title: "SQL, modelado y persistencia", summary: "Modelo relacional, SQL, índices, transacciones, NoSQL, caché, migraciones y consistencia.", languages: ["SQL", "Python", "TypeScript"], topics: ["normalization", "SQL", "indexes", "transactions", "NoSQL", "cache"], project: "Backend con consultas medibles y auditoría.", gate: "Explicar plan de consulta e integridad." },
  { code: "L12", phase: "Oficio", title: "Git, Linux y herramientas", summary: "Shell, procesos, permisos, Git, branches, PRs, debugging, profiling, linters, documentación y CI.", languages: ["Bash", "PowerShell", "Git"], topics: ["shell", "processes", "git", "debugging", "profiling", "CI"], project: "Repositorio colaborativo con pipeline y release.", gate: "Historial reproducible y revisión por otra persona." },
  { code: "L13", phase: "Sistemas", title: "C, memoria y sistemas operativos", summary: "Representación binaria, punteros, memoria, procesos, hilos, archivos, sockets y compilación.", languages: ["C", "C++", "Rust"], topics: ["memory", "pointers", "processes", "threads", "filesystems", "sockets"], project: "Servidor concurrente y herramienta de profiling.", gate: "Explicar memoria y condiciones de carrera." },
  { code: "L14", phase: "Concurrencia", title: "Redes, concurrencia y distribuidos", summary: "TCP/IP, HTTP interno, sincronización, consenso básico, cachés, particiones y tolerancia a fallos.", languages: ["Go", "Rust", "Java"], topics: ["TCP", "concurrency", "locks", "consistency", "replication", "fault tolerance"], project: "Servicio distribuido pequeño con fallos simulados.", gate: "Defender garantías y límites del sistema." },
  { code: "L15", phase: "Empresa", title: "Java/Kotlin y .NET a escala", summary: "DI, capas, contratos, mensajería, testing, persistencia y evolución de bases de código grandes.", languages: ["Java", "Kotlin", "C#"], topics: ["DI", "layers", "contracts", "messaging", "testing", "maintainability"], project: "Servicio empresarial modular con eventos.", gate: "Versionado y pruebas contractuales." },
  { code: "L16", phase: "Clientes", title: "Móvil y multiplataforma", summary: "Android, iOS, Flutter/React Native, ciclo de vida, estado, red, almacenamiento, sensores y publicación.", languages: ["Kotlin", "Swift", "Dart", "TypeScript"], topics: ["Android", "iOS", "Flutter", "offline", "sensors", "mobile testing"], project: "Cliente móvil offline-first conectado a API propia.", gate: "Pruebas en varios tamaños y pérdida de red." },
  { code: "L17", phase: "Producción", title: "Cloud, DevOps, SRE y AppSec", summary: "Contenedores, CI/CD, IaC, Kubernetes, SLO, observabilidad, secretos, supply chain y seguridad.", languages: ["Docker", "YAML", "Terraform", "Bash"], topics: ["containers", "CI/CD", "IaC", "SRE", "observability", "AppSec"], project: "Despliegue reproducible con alertas y recuperación.", gate: "SLO, runbook y prueba de fallo." },
  { code: "L18", phase: "Lenguajes", title: "Compiladores, runtimes y lenguajes", summary: "Lexing, parsing, AST, intérpretes, bytecode, tipos, runtimes, GC y JIT.", languages: ["Rust", "C++", "TypeScript"], topics: ["lexer", "parser", "AST", "types", "bytecode", "runtime"], project: "Lenguaje pequeño con intérprete y tests.", gate: "Explicar cada fase del pipeline." },
  { code: "L19", phase: "Dominio", title: "Arquitectura, rendimiento y capstone", summary: "Arquitecturas distribuidas, profiling, seguridad, OSS, ADRs, benchmarks, revisión y defensa técnica.", languages: ["Rust", "Go", "C++", "TypeScript", "Python"], topics: ["architecture", "performance", "security", "OSS", "ADRs", "benchmarks"], project: "Producto completo y contribución open source.", gate: "Defensa técnica con evidencia medible y revisión externa." },
]

export const practiceResources: PracticeResource[] = [
  { name: "freeCodeCamp", kind: "Currículo abierto", scope: "Fundamentos, web, JavaScript, frontend, backend, datos", url: "https://www.freecodecamp.org/espanol/learn/", note: "Complemento amplio y gratuito; úsalo como práctica paralela." },
  { name: "Exercism", kind: "Práctica multi-lenguaje", scope: "Decenas de lenguajes, ejercicios, análisis y mentoría", url: "https://exercism.org/", note: "Especialmente útil para ganar fluidez idiomática en cada lenguaje." },
  { name: "The Odin Project", kind: "Ruta de proyectos", scope: "Foundations y full stack", url: "https://www.theodinproject.com/paths", note: "Se enlaza como recurso externo; no se copia su currículo." },
  { name: "Full Stack Open", kind: "Profundización", scope: "React, Node, GraphQL, TypeScript y web moderna", url: "https://fullstackopen.com/es/", note: "Profundización universitaria; se usa como referencia externa." },
  { name: "CodeCombat", kind: "Juego de código", scope: "Práctica escribiendo código en un entorno de juego", url: "https://codecombat.com/", note: "Sirve de inspiración mecánica; no se copian sus niveles." },
  { name: "CheckiO", kind: "Misiones gamificadas", scope: "Python y TypeScript", url: "https://checkio.org/", note: "Buen refuerzo para práctica breve y resolución de retos." },
  { name: "Algorithm Visualizer", kind: "Visualización", scope: "Algoritmos y estructuras", url: "https://algorithm-visualizer.org/", note: "Excelente para observar algoritmos en acción." },
  { name: "Learn Git Branching", kind: "Simulador interactivo", scope: "Git y branching", url: "https://learngitbranching.js.org/", note: "Práctica visual de ramas y movimientos de Git." },
  { name: "Project Euler", kind: "Problemas", scope: "Matemática computacional y algoritmos", url: "https://projecteuler.net/", note: "Para profundizar razonamiento y eficiencia." },
  { name: "Advent of Code", kind: "Puzzles", scope: "Resolución de problemas en cualquier lenguaje", url: "https://adventofcode.com/", note: "Ideal para práctica periódica y parsing." },
  { name: "roadmap.sh", kind: "Mapas de especialización", scope: "Roles y tecnologías profesionales", url: "https://roadmap.sh/", note: "Útil al elegir especializaciones después del núcleo." },
]

export const missionTemplates = [
  {
    id: "m0",
    title: "Primer programa",
    level: "L00",
    language: "python" as const,
    objective: "Ejecuta una instrucción y cambia el mensaje.",
    instructions: ["Ejecuta el código", "Cambia el texto", "Vuelve a ejecutar y comprueba la salida"],
    starter: `print("Hola Campus Maestro")`,
    expected: "Hola Campus Maestro",
  },
  {
    id: "m1",
    title: "Variables y estado",
    level: "L01",
    language: "python" as const,
    objective: "Guarda datos en variables y construye una salida con ellos.",
    instructions: ["Cambia nombre y puntos", "Usa una f-string", "Comprueba la salida"],
    starter: `nombre = "Ada"\npuntos = 120\nprint(f"{nombre} tiene {puntos} puntos")`,
    expected: "Ada tiene 120 puntos",
  },
  {
    id: "m2",
    title: "Decisiones",
    level: "L01",
    language: "python" as const,
    objective: "Toma una decisión con if/else.",
    instructions: ["Cambia energia", "Predice el resultado", "Ejecuta y confirma"],
    starter: `energia = 70\nif energia >= 50:\n    print("Avanza")\nelse:\n    print("Descansa")`,
    expected: "Avanza",
  },
  {
    id: "m3",
    title: "Bucles y colecciones",
    level: "L01",
    language: "javascript" as const,
    objective: "Recorre una lista y acumula un total.",
    instructions: ["Recorre monedas", "Acumula cada valor", "Muestra el total"],
    starter: `const monedas = [5, 8, 3, 10, 7];\nlet total = 0;\nfor (const moneda of monedas) total += moneda;\nconsole.log("Total:", total);`,
    expected: "Total: 33",
  },
  {
    id: "m4",
    title: "Funciones",
    level: "L02",
    language: "javascript" as const,
    objective: "Encapsula una solución en una función reutilizable.",
    instructions: ["Completa la función", "Devuelve el promedio", "Prueba con otra lista"],
    starter: `function promedio(valores) {\n  return valores.reduce((a, b) => a + b, 0) / valores.length;\n}\nconsole.log(promedio([10, 15, 20]));`,
    expected: "15",
  },
  {
    id: "m5",
    title: "DOM y eventos",
    level: "L08",
    language: "web" as const,
    objective: "Conecta un botón con el DOM y actualiza la interfaz.",
    instructions: ["Pulsa el botón", "Modifica el incremento", "Añade un botón de reinicio"],
    starter: `<!doctype html>\n<html lang="es"><head><meta charset="utf-8"><style>body{font-family:system-ui;padding:28px}.card{padding:22px;border:1px solid #ddd;border-radius:18px;max-width:360px}button{padding:10px 14px}</style></head><body><main class="card"><h1>Contador</h1><p id="out">0</p><button id="btn">Sumar</button></main><script>let n=0;const out=document.querySelector('#out');document.querySelector('#btn').onclick=()=>{n+=1;out.textContent=String(n)};</script></body></html>`,
    expected: "Contador interactivo",
  },
  {
    id: "m6", title: "Pila y cola", level: "L04", language: "javascript" as const,
    objective: "Compara LIFO y FIFO implementando operaciones básicas.",
    instructions: ["Usa push/pop para la pila", "Usa push/shift para la cola", "Explica por qué el orden de salida cambia"],
    starter: `const pila = [];\npila.push("A", "B", "C");\nconsole.log("Pila:", pila.pop());\n\nconst cola = [];\ncola.push("A", "B", "C");\nconsole.log("Cola:", cola.shift());`,
    expected: "Pila: C",
  },
  {
    id: "m7", title: "Búsqueda binaria", level: "L05", language: "python" as const,
    objective: "Reduce el espacio de búsqueda a la mitad en cada paso.",
    instructions: ["Mantén izquierda y derecha", "Calcula el medio", "Descarta la mitad imposible"],
    starter: `def buscar(datos, objetivo):\n    izquierda, derecha = 0, len(datos) - 1\n    while izquierda <= derecha:\n        medio = (izquierda + derecha) // 2\n        if datos[medio] == objetivo:\n            return medio\n        if datos[medio] < objetivo:\n            izquierda = medio + 1\n        else:\n            derecha = medio - 1\n    return -1\n\nprint(buscar([2, 5, 8, 11, 16, 23, 38], 16))`,
    expected: "4",
  },
  {
    id: "m8", title: "BFS en un grafo", level: "L06", language: "python" as const,
    objective: "Recorre un grafo por capas usando una cola.",
    instructions: ["Inicializa visitados", "Extrae de la izquierda", "Añade vecinos no visitados"],
    starter: `from collections import deque\n\ngrafo = {"A": ["B", "C"], "B": ["D"], "C": ["E"], "D": [], "E": []}\ncola = deque(["A"])\nvisitados = set(["A"])\norden = []\nwhile cola:\n    nodo = cola.popleft()\n    orden.append(nodo)\n    for vecino in grafo[nodo]:\n        if vecino not in visitados:\n            visitados.add(vecino)\n            cola.append(vecino)\nprint(orden)`,
    expected: "['A', 'B', 'C', 'D', 'E']",
  },
  {
    id: "m9", title: "Composición y dependencias", level: "L07", language: "javascript" as const,
    objective: "Separa una regla de negocio de la forma de guardar datos.",
    instructions: ["Crea un repositorio simple", "Inyéctalo en el servicio", "Comprueba que el servicio no conoce detalles de almacenamiento"],
    starter: `function crearServicio(repo) {\n  return { registrar(nombre) { repo.guardar({ nombre }); return "registrado"; } };\n}\nconst memoria = { datos: [], guardar(item) { this.datos.push(item); } };\nconst servicio = crearServicio(memoria);\nconsole.log(servicio.registrar("Ada"), memoria.datos.length);`,
    expected: "registrado 1",
  },
  {
    id: "m10", title: "Estado derivado en frontend", level: "L09", language: "javascript" as const,
    objective: "Evita duplicar estado que puede calcularse a partir de otros datos.",
    instructions: ["Define precio y cantidad", "Calcula total como dato derivado", "Cambia cantidad y vuelve a calcular"],
    starter: `const precio = 25;\nlet cantidad = 3;\nconst total = () => precio * cantidad;\nconsole.log("Total:", total());\ncantidad = 4;\nconsole.log("Nuevo:", total());`,
    expected: "Total: 75",
  },
  {
    id: "m11", title: "Validación de API", level: "L10", language: "javascript" as const,
    objective: "Valida datos en la frontera antes de ejecutar reglas de negocio.",
    instructions: ["Comprueba tipo de email", "Rechaza cadenas sin @", "Devuelve un resultado explícito"],
    starter: `function registrar(body) {\n  if (!body || typeof body.email !== "string") return { ok: false, error: "email requerido" };\n  if (!body.email.includes("@")) return { ok: false, error: "email inválido" };\n  return { ok: true, email: body.email };\n}\nconsole.log(registrar({ email: "ada@example.com" }));`,
    expected: "\"ok\": true",
  },
  {
    id: "m12", title: "Transacción mental", level: "L11", language: "python" as const,
    objective: "Comprende que varios cambios relacionados deben confirmarse juntos.",
    instructions: ["Copia el estado inicial", "Aplica ambos cambios", "Restaura si ocurre una excepción"],
    starter: `cuentas = {"A": 100, "B": 50}\nrespaldo = cuentas.copy()\ntry:\n    monto = 30\n    cuentas["A"] -= monto\n    cuentas["B"] += monto\nexcept Exception:\n    cuentas = respaldo\nprint(cuentas)`,
    expected: "{'A': 70, 'B': 80}",
  },
  {
    id: "m13", title: "Historial Git como grafo", level: "L12", language: "javascript" as const,
    objective: "Entiende un commit como nodo que referencia a su padre.",
    instructions: ["Crea commits encadenados", "Mueve una rama al último commit", "Imprime la referencia actual"],
    starter: `const commits = { c1: { parent: null }, c2: { parent: "c1" }, c3: { parent: "c2" } };\nconst ramas = { main: "c3" };\nconsole.log("main ->", ramas.main, "padre ->", commits[ramas.main].parent);`,
    expected: "main -> c3 padre -> c2",
  },
  {
    id: "m14", title: "Bytes y memoria", level: "L13", language: "javascript" as const,
    objective: "Observa una misma región de memoria mediante una vista tipada.",
    instructions: ["Crea un ArrayBuffer", "Escribe bytes con Uint8Array", "Imprime el contenido"],
    starter: `const memoria = new ArrayBuffer(4);\nconst bytes = new Uint8Array(memoria);\nbytes[0] = 65; bytes[1] = 66; bytes[2] = 67; bytes[3] = 68;\nconsole.log(Array.from(bytes));`,
    expected: "[65,66,67,68]",
  },
  {
    id: "m15", title: "Retry con backoff", level: "L14", language: "javascript" as const,
    objective: "Modela reintentos limitados sin asumir que la red siempre funciona.",
    instructions: ["Limita intentos", "Aumenta la espera lógica", "Detente al obtener éxito"],
    starter: `const resultados = [false, false, true];\nlet espera = 100;\nfor (let intento = 0; intento < resultados.length; intento += 1) {\n  console.log("intento", intento + 1, "espera", espera);\n  if (resultados[intento]) { console.log("éxito"); break; }\n  espera *= 2;\n}`,
    expected: "éxito",
  },
  {
    id: "m16", title: "Contrato versionado", level: "L15", language: "javascript" as const,
    objective: "Evoluciona un objeto de respuesta sin romper a un consumidor antiguo.",
    instructions: ["Conserva el campo existente", "Añade un campo nuevo", "Simula un consumidor que solo usa v1"],
    starter: `const respuestaV2 = { nombre: "Ada", activo: true, version: 2 };\nfunction consumidorV1(data) { return data.nombre; }\nconsole.log(consumidorV1(respuestaV2));`,
    expected: "Ada",
  },
  {
    id: "m17", title: "Cola offline-first", level: "L16", language: "javascript" as const,
    objective: "Guarda cambios localmente cuando no hay red y sincronízalos después.",
    instructions: ["Encola dos cambios", "Simula recuperación de red", "Vacía la cola en orden"],
    starter: `const pendientes = [];\npendientes.push({ id: 1, cambio: "crear" });\npendientes.push({ id: 2, cambio: "editar" });\nwhile (pendientes.length) {\n  const cambio = pendientes.shift();\n  console.log("sincronizado", cambio.id);\n}`,
    expected: "sincronizado 1",
  },
  {
    id: "m18", title: "SLO y presupuesto de error", level: "L17", language: "python" as const,
    objective: "Convierte una meta de disponibilidad en un presupuesto medible.",
    instructions: ["Define total de solicitudes", "Calcula máximo de fallos para 99.9%", "Interpreta el resultado"],
    starter: `solicitudes = 100000\nslo = 0.999\nfallos_permitidos = int(solicitudes * (1 - slo))\nprint("fallos permitidos:", fallos_permitidos)`,
    expected: "fallos permitidos: 100",
  },
  {
    id: "m19", title: "Lexer mínimo", level: "L18", language: "javascript" as const,
    objective: "Convierte texto fuente en una secuencia simple de tokens.",
    instructions: ["Separa por espacios", "Clasifica números y símbolos", "Observa la salida tokenizada"],
    starter: `const fuente = "x = 12 + 3";\nconst tokens = fuente.split(/\\s+/).map(valor => ({\n  tipo: /^\\d+$/.test(valor) ? "NUM" : /^[a-z]+$/i.test(valor) ? "ID" : "SYM",\n  valor\n}));\nconsole.log(tokens);`,
    expected: "\"tipo\":\"ID\"",
  },
  {
    id: "m20", title: "Benchmark reproducible", level: "L19", language: "python" as const,
    objective: "Compara dos estrategias con una entrada fija y una medición repetible.",
    instructions: ["Usa la misma entrada", "Mide varias repeticiones", "No confundas una sola medición con una conclusión"],
    starter: `import time\n\ndatos = list(range(20000))\ninicio = time.perf_counter()\nfor _ in range(50):\n    objetivo = 19999 in datos\nfin = time.perf_counter()\nprint("encontrado:", objetivo, "segundos:", round(fin - inicio, 6))`,
    expected: "encontrado: True",
  },
]
