import { expandedSpanishResources } from "./resources-expanded-es"

export type ResourceCategory =
  | "Bibliotecas y currículos"
  | "Fundamentos"
  | "Programación"
  | "Programación y software"
  | "Web y móvil"
  | "Datos e IA"
  | "Ciberseguridad"
  | "Redes y telecom"
  | "Cloud, DevOps y sistemas"
  | "Hardware, IoT y robótica"
  | "Matemáticas e investigación"
  | "Cuántica y frontera"
  | "Gestión y arquitectura"

export type ResourceType =
  | "Libro / PDF"
  | "Apuntes"
  | "Curso"
  | "Video"
  | "Documentación"
  | "Roadmap"
  | "Práctica"
  | "Repositorio"
  | "Paper"
  | "Dataset"
  | "Simulador"
  | "Estándar"

export type ResourceLanguage = "ES" | "EN" | "ES/EN"
export type ResourceLevel = "Inicial" | "Intermedio" | "Avanzado" | "Todos"

export type ResourceItem = {
  coverImage?: string
  id: string
  title: string
  provider: string
  description: string
  category: ResourceCategory
  type: ResourceType
  language: ResourceLanguage
  level: ResourceLevel
  license: string
  url: string
  downloadUrl?: string
  embedUrl?: string
  tags: string[]
  featured?: boolean
  verified?: boolean
}

export const resourceCategories: ResourceCategory[] = [
  "Bibliotecas y currículos",
  "Fundamentos",
  "Programación",
  "Programación y software",
  "Web y móvil",
  "Datos e IA",
  "Ciberseguridad",
  "Redes y telecom",
  "Cloud, DevOps y sistemas",
  "Hardware, IoT y robótica",
  "Matemáticas e investigación",
  "Cuántica y frontera",
  "Gestión y arquitectura",
]

export const resourceTypes: ResourceType[] = [
  "Libro / PDF",
  "Apuntes",
  "Curso",
  "Video",
  "Documentación",
  "Roadmap",
  "Práctica",
  "Repositorio",
  "Paper",
  "Dataset",
  "Simulador",
  "Estándar",
]

const baseResources: ResourceItem[] = [
  {
    id: "free-programming-books",
    title: "Free Programming Books",
    provider: "Free Ebook Foundation · GitHub",
    description: "Uno de los mayores índices curados de libros, cursos y recursos de programación gratuitos, con colecciones en español y muchos otros idiomas.",
    category: "Bibliotecas y currículos",
    type: "Repositorio",
    language: "ES/EN",
    level: "Todos",
    license: "CC BY 4.0 (lista); cada recurso conserva su propia licencia",
    url: "https://github.com/EbookFoundation/free-programming-books",
    tags: ["libros", "pdf", "programación", "git", "español", "biblioteca"],
    featured: true,
    verified: true,
  },
  {
    id: "free-programming-books-search",
    title: "Free Programming Books Search",
    provider: "Free Ebook Foundation",
    description: "Buscador web del catálogo de Free Programming Books para encontrar libros y cursos por lenguaje o tema sin recorrer manualmente el repositorio.",
    category: "Bibliotecas y currículos",
    type: "Libro / PDF",
    language: "ES/EN",
    level: "Todos",
    license: "Enlaces a recursos gratuitos; verificar licencia individual",
    url: "https://ebookfoundation.github.io/free-programming-books-search/",
    tags: ["buscador", "libros", "cursos", "programación"],
    featured: true,
    verified: true,
  },
  {
    id: "awesome",
    title: "Awesome",
    provider: "Sindre Sorhus · GitHub",
    description: "El índice de listas Awesome: cientos de colecciones especializadas en lenguajes, IA, seguridad, sistemas, bases de datos, hardware y prácticamente cualquier tecnología.",
    category: "Bibliotecas y currículos",
    type: "Repositorio",
    language: "EN",
    level: "Todos",
    license: "CC0 / licencias de cada lista",
    url: "https://github.com/sindresorhus/awesome",
    tags: ["awesome", "listas", "recursos", "herramientas", "github"],
    featured: true,
    verified: true,
  },
  {
    id: "ossu-cs",
    title: "OSSU Computer Science",
    provider: "Open Source Society University · GitHub",
    description: "Currículo autodidacta completo de Ciencias de la Computación basado en materiales universitarios gratuitos, organizado desde fundamentos hasta temas avanzados.",
    category: "Bibliotecas y currículos",
    type: "Roadmap",
    language: "EN",
    level: "Todos",
    license: "MIT (currículo); cursos externos con sus propias licencias",
    url: "https://github.com/ossu/computer-science",
    tags: ["computer science", "currículo", "universidad", "autodidacta", "roadmap"],
    featured: true,
    verified: true,
  },
  {
    id: "mit-ocw",
    title: "MIT OpenCourseWare",
    provider: "MIT",
    description: "Material abierto de miles de cursos del MIT: apuntes, problemas, exámenes, lecturas, videos y libros de texto abiertos.",
    category: "Bibliotecas y currículos",
    type: "Curso",
    language: "EN",
    level: "Todos",
    license: "Creative Commons según el curso",
    url: "https://ocw.mit.edu/",
    tags: ["universidad", "mit", "apuntes", "exámenes", "videos", "pdf"],
    featured: true,
    verified: true,
  },
  {
    id: "mit-open-textbooks",
    title: "MIT Open Textbooks",
    provider: "MIT OpenCourseWare",
    description: "Colección de libros de texto abiertos publicados por MIT OpenCourseWare, útiles para matemáticas, computación, ingeniería y ciencia.",
    category: "Bibliotecas y currículos",
    type: "Libro / PDF",
    language: "EN",
    level: "Todos",
    license: "Creative Commons según el libro",
    url: "https://ocw.mit.edu/resource_collections/open-textbooks/",
    tags: ["libros", "mit", "pdf", "open textbook"],
    featured: true,
    verified: true,
  },
  {
    id: "openstax-cs",
    title: "OpenStax Computer Science",
    provider: "OpenStax · Rice University",
    description: "Libros universitarios gratuitos de Foundations of Computer Science, Information Systems, Data Science y Python Programming.",
    category: "Bibliotecas y currículos",
    type: "Libro / PDF",
    language: "EN",
    level: "Inicial",
    license: "Licencia abierta indicada por cada libro",
    url: "https://openstax.org/subjects/computer-science",
    tags: ["libros", "universidad", "python", "data science", "information systems"],
    featured: true,
    verified: true,
  },
  {
    id: "open-textbook-library",
    title: "Open Textbook Library",
    provider: "University of Minnesota",
    description: "Biblioteca académica de libros de texto abiertos revisados y publicados con licencias que permiten uso educativo y reutilización.",
    category: "Bibliotecas y currículos",
    type: "Libro / PDF",
    language: "EN",
    level: "Todos",
    license: "Open licenses según cada libro",
    url: "https://open.umn.edu/opentextbooks",
    tags: ["libros", "oer", "open access", "universidad"],
    verified: true,
  },
  {
    id: "libretexts-cs",
    title: "LibreTexts Computer Science",
    provider: "LibreTexts",
    description: "Colecciones abiertas de programación, sistemas, redes, matemáticas discretas, datos y otros contenidos universitarios.",
    category: "Bibliotecas y currículos",
    type: "Libro / PDF",
    language: "EN",
    level: "Todos",
    license: "OER / licencias indicadas por cada texto",
    url: "https://eng.libretexts.org/Bookshelves/Computer_Science",
    tags: ["libros", "apuntes", "oer", "computer science"],
    verified: true,
  },
  {
    id: "gitlab-oer-cs",
    title: "GitLab OER · Computer Science",
    provider: "GitLab · Open Educational Resources",
    description: "Grupo de recursos educativos abiertos sobre programación, sistemas operativos, bases de datos y sistemas distribuidos alojados en GitLab.",
    category: "Bibliotecas y currículos",
    type: "Repositorio",
    language: "EN",
    level: "Todos",
    license: "OER según subproyecto",
    url: "https://gitlab.com/oer/cs",
    tags: ["gitlab", "oer", "programación", "sistemas", "datos"],
    verified: true,
  },
  {
    id: "openfing",
    title: "OpenFING",
    provider: "Facultad de Ingeniería · Udelar",
    description: "Cursos y clases universitarias abiertas de ingeniería y computación en español, con fuerte valor para una ruta universitaria autodidacta.",
    category: "Bibliotecas y currículos",
    type: "Curso",
    language: "ES",
    level: "Todos",
    license: "Acceso abierto según material",
    url: "https://open.fing.edu.uy/courses/",
    tags: ["español", "universidad", "ingeniería", "computación", "clases"],
    featured: true,
  },
  {
    id: "upv-ocw",
    title: "UPV OpenCourseWare",
    provider: "Universitat Politècnica de València",
    description: "Material docente universitario abierto en español de ingeniería, programación, redes, matemáticas y tecnologías de información.",
    category: "Bibliotecas y currículos",
    type: "Curso",
    language: "ES",
    level: "Todos",
    license: "OpenCourseWare / licencia indicada por asignatura",
    url: "https://ocw.upv.es/",
    tags: ["español", "universidad", "ocw", "ingeniería"],
  },
  {
    id: "uoc-open",
    title: "UOC Open Access",
    provider: "Universitat Oberta de Catalunya",
    description: "Repositorio institucional con materiales docentes, trabajos académicos y publicaciones abiertas vinculadas a informática y tecnología.",
    category: "Bibliotecas y currículos",
    type: "Apuntes",
    language: "ES",
    level: "Todos",
    license: "Open access / licencia por documento",
    url: "https://openaccess.uoc.edu/",
    tags: ["español", "universidad", "apuntes", "investigación"],
  },

  {
    id: "cs50x",
    title: "CS50x · Introduction to Computer Science",
    provider: "Harvard University",
    description: "Curso introductorio riguroso de ciencias de la computación con problemas, proyectos, algoritmos, C, Python, SQL, web y fundamentos.",
    category: "Fundamentos",
    type: "Curso",
    language: "ES/EN",
    level: "Inicial",
    license: "Acceso gratuito al curso; materiales bajo términos de Harvard",
    url: "https://cs50.harvard.edu/x/",
    tags: ["cs50", "algoritmos", "c", "python", "sql", "harvard"],
    featured: true,
    verified: true,
  },
  {
    id: "teach-yourself-cs",
    title: "Teach Yourself Computer Science",
    provider: "Teach Yourself CS",
    description: "Guía compacta para estudiar las áreas fundamentales de CS: programación, arquitectura, algoritmos, matemáticas, sistemas, redes, bases de datos y lenguajes.",
    category: "Fundamentos",
    type: "Roadmap",
    language: "EN",
    level: "Intermedio",
    license: "Sitio abierto; recursos enlazados con licencias propias",
    url: "https://teachyourselfcs.com/",
    tags: ["roadmap", "computer science", "autodidacta", "fundamentos"],
    featured: true,
  },
  {
    id: "missing-semester",
    title: "The Missing Semester of Your CS Education",
    provider: "MIT CSAIL",
    description: "Apuntes y videos sobre shell, editores, data wrangling, Git, debugging, profiling, metaprogramming y herramientas que suelen quedar fuera del currículo.",
    category: "Fundamentos",
    type: "Apuntes",
    language: "EN",
    level: "Inicial",
    license: "Material del curso según MIT",
    url: "https://missing.csail.mit.edu/",
    tags: ["shell", "git", "debugging", "herramientas", "mit"],
    featured: true,
  },
  {
    id: "nand2tetris",
    title: "Nand2Tetris",
    provider: "Hebrew University / Nand2Tetris",
    description: "Construye un computador desde puertas lógicas hasta CPU, VM, compilador, sistema operativo y un programa final.",
    category: "Fundamentos",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "Material educativo gratuito según el proyecto",
    url: "https://www.nand2tetris.org/",
    tags: ["hardware", "arquitectura", "compiladores", "sistemas", "proyecto"],
    featured: true,
  },
  {
    id: "mit-6006",
    title: "MIT 6.006 · Introduction to Algorithms",
    provider: "MIT OpenCourseWare",
    description: "Curso universitario de algoritmos y estructuras de datos con clases, problemas y materiales oficiales del MIT.",
    category: "Fundamentos",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "Creative Commons / MIT OCW",
    url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/",
    tags: ["algoritmos", "estructuras de datos", "mit", "cs"],
  },
  {
    id: "math-cs-mit-pdf",
    title: "Mathematics for Computer Science",
    provider: "MIT",
    description: "Texto de matemáticas discretas para CS: lógica, inducción, grafos, conteo, probabilidad y fundamentos matemáticos.",
    category: "Fundamentos",
    type: "Libro / PDF",
    language: "EN",
    level: "Intermedio",
    license: "Material académico abierto del curso",
    url: "https://courses.csail.mit.edu/6.042/spring18/mcs.pdf",
    downloadUrl: "https://courses.csail.mit.edu/6.042/spring18/mcs.pdf",
    tags: ["matemática discreta", "lógica", "grafos", "probabilidad", "pdf"],
    featured: true,
  },
  {
    id: "cs-video-courses",
    title: "Computer Science Video Courses",
    provider: "Developer-Y · GitHub",
    description: "Índice curado de cursos universitarios en video de CS, organizado por área: sistemas, teoría, IA, seguridad, gráficos y más.",
    category: "Fundamentos",
    type: "Video",
    language: "EN",
    level: "Todos",
    license: "Lista abierta; videos con términos de cada universidad",
    url: "https://github.com/Developer-Y/cs-video-courses",
    tags: ["videos", "universidad", "computer science", "github"],
  },
  {
    id: "coding-interview-university",
    title: "Coding Interview University",
    provider: "jwasham · GitHub",
    description: "Plan de estudio intensivo sobre estructuras de datos, algoritmos, diseño de sistemas y fundamentos usados en entrevistas técnicas.",
    category: "Fundamentos",
    type: "Roadmap",
    language: "ES/EN",
    level: "Intermedio",
    license: "CC BY-SA 4.0",
    url: "https://github.com/jwasham/coding-interview-university",
    tags: ["algoritmos", "entrevistas", "estructuras de datos", "roadmap"],
  },

  {
    id: "build-your-own-x",
    title: "Build Your Own X",
    provider: "CodeCrafters · GitHub",
    description: "Tutoriales para recrear tecnologías desde cero: bases de datos, Git, Docker, compiladores, redes, motores, sistemas operativos y más.",
    category: "Programación y software",
    type: "Repositorio",
    language: "EN",
    level: "Intermedio",
    license: "MIT (repositorio); tutoriales externos con licencias propias",
    url: "https://github.com/codecrafters-io/build-your-own-x",
    tags: ["proyectos", "desde cero", "sistemas", "compiladores", "base de datos"],
    featured: true,
    verified: true,
  },
  {
    id: "project-based-learning",
    title: "Project Based Learning",
    provider: "practical-tutorials · GitHub",
    description: "Tutoriales prácticos organizados por lenguaje para aprender construyendo aplicaciones, herramientas y proyectos reales.",
    category: "Programación y software",
    type: "Repositorio",
    language: "EN",
    level: "Todos",
    license: "MIT (repositorio); recursos externos con licencias propias",
    url: "https://github.com/practical-tutorials/project-based-learning",
    tags: ["proyectos", "programación", "tutoriales", "github"],
    featured: true,
  },
  {
    id: "system-design-primer",
    title: "System Design Primer",
    provider: "donnemartin · GitHub",
    description: "Fundamentos de diseño de sistemas escalables, trade-offs, caché, bases de datos, balanceo, colas, disponibilidad y ejercicios de entrevistas.",
    category: "Programación y software",
    type: "Repositorio",
    language: "EN",
    level: "Avanzado",
    license: "CC BY 4.0",
    url: "https://github.com/donnemartin/system-design-primer",
    tags: ["system design", "arquitectura", "escalabilidad", "backend"],
    featured: true,
  },
  {
    id: "refactoring-guru",
    title: "Refactoring.Guru",
    provider: "Refactoring.Guru",
    description: "Patrones de diseño, refactorización y principios de diseño de software explicados visualmente y con ejemplos en varios lenguajes.",
    category: "Programación y software",
    type: "Apuntes",
    language: "ES/EN",
    level: "Intermedio",
    license: "Contenido del autor; acceso web gratuito parcial",
    url: "https://refactoring.guru/es",
    tags: ["patrones", "refactoring", "arquitectura", "solid"],
  },
  {
    id: "freecodecamp",
    title: "freeCodeCamp",
    provider: "freeCodeCamp",
    description: "Currículo interactivo gratuito con certificaciones y proyectos de web, JavaScript, Python, bases de datos, datos, IA y más.",
    category: "Programación y software",
    type: "Curso",
    language: "ES/EN",
    level: "Todos",
    license: "Open source / BSD-3-Clause para el código; contenido según términos",
    url: "https://www.freecodecamp.org/",
    tags: ["programación", "certificación", "proyectos", "javascript", "python"],
    featured: true,
  },
  {
    id: "exercism",
    title: "Exercism",
    provider: "Exercism",
    description: "Práctica gratuita con ejercicios en numerosos lenguajes, tracks estructurados y feedback comunitario.",
    category: "Programación y software",
    type: "Práctica",
    language: "EN",
    level: "Todos",
    license: "Open source / licencias del proyecto",
    url: "https://exercism.org/",
    tags: ["ejercicios", "katas", "lenguajes", "práctica"],
  },
  {
    id: "the-algorithms",
    title: "The Algorithms",
    provider: "TheAlgorithms · GitHub",
    description: "Implementaciones educativas de algoritmos y estructuras de datos en numerosos lenguajes de programación.",
    category: "Programación y software",
    type: "Repositorio",
    language: "EN",
    level: "Intermedio",
    license: "Licencia por repositorio",
    url: "https://the-algorithms.com/",
    tags: ["algoritmos", "código", "lenguajes", "github"],
  },
  {
    id: "pro-git",
    title: "Pro Git",
    provider: "Git",
    description: "Libro oficial y gratuito de Git, disponible online y en múltiples idiomas, incluido español.",
    category: "Programación y software",
    type: "Libro / PDF",
    language: "ES/EN",
    level: "Todos",
    license: "Creative Commons",
    url: "https://git-scm.com/book/es/v2",
    tags: ["git", "control de versiones", "libro", "español"],
  },
  {
    id: "think-python",
    title: "Think Python 2e",
    provider: "Allen B. Downey · Green Tea Press",
    description: "Libro introductorio de Python 3 con progresión pedagógica, ejercicios y material complementario.",
    category: "Programación y software",
    type: "Libro / PDF",
    language: "EN",
    level: "Inicial",
    license: "CC BY-NC 3.0",
    url: "https://greenteapress.com/wp/think-python-2e/",
    downloadUrl: "https://greenteapress.com/thinkpython2/thinkpython2.pdf",
    tags: ["python", "libro", "pdf", "programación"],
    verified: true,
  },
  {
    id: "eloquent-javascript",
    title: "Eloquent JavaScript",
    provider: "Marijn Haverbeke",
    description: "Libro moderno y gratuito de JavaScript que cubre lenguaje, navegador, Node.js y proyectos prácticos.",
    category: "Programación y software",
    type: "Libro / PDF",
    language: "EN",
    level: "Intermedio",
    license: "CC BY-NC 3.0 para el texto",
    url: "https://eloquentjavascript.net/",
    downloadUrl: "https://eloquentjavascript.net/Eloquent_JavaScript.pdf",
    tags: ["javascript", "libro", "pdf", "node", "web"],
  },
  {
    id: "rust-book",
    title: "The Rust Programming Language",
    provider: "Rust Project",
    description: "Libro oficial de Rust, desde ownership y tipos hasta concurrencia, traits, testing y proyectos.",
    category: "Programación y software",
    type: "Libro / PDF",
    language: "EN",
    level: "Intermedio",
    license: "MIT / Apache-2.0 según contenido del proyecto",
    url: "https://doc.rust-lang.org/book/",
    tags: ["rust", "sistemas", "lenguaje", "libro"],
  },
  {
    id: "go-tour",
    title: "A Tour of Go",
    provider: "Go Project",
    description: "Tour interactivo oficial del lenguaje Go con ejemplos ejecutables directamente en el navegador.",
    category: "Programación y software",
    type: "Práctica",
    language: "EN",
    level: "Inicial",
    license: "BSD-style / términos del proyecto Go",
    url: "https://go.dev/tour/",
    tags: ["go", "golang", "interactivo", "programación"],
  },

  {
    id: "odin-project",
    title: "The Odin Project",
    provider: "The Odin Project",
    description: "Currículo open source de desarrollo web full stack basado en proyectos reales, Git, JavaScript, React y backend.",
    category: "Web y móvil",
    type: "Curso",
    language: "EN",
    level: "Inicial",
    license: "Open source; contenido bajo términos del proyecto",
    url: "https://www.theodinproject.com/",
    tags: ["full stack", "javascript", "react", "web", "proyectos"],
    featured: true,
  },
  {
    id: "fullstackopen",
    title: "Full Stack Open",
    provider: "University of Helsinki",
    description: "Curso universitario gratuito de React, Node.js, REST, GraphQL, TypeScript, testing, contenedores y CI/CD.",
    category: "Web y móvil",
    type: "Curso",
    language: "ES/EN",
    level: "Intermedio",
    license: "Creative Commons según material",
    url: "https://fullstackopen.com/es/",
    tags: ["react", "node", "typescript", "graphql", "full stack"],
    featured: true,
  },
  {
    id: "mdn",
    title: "MDN Web Docs",
    provider: "Mozilla",
    description: "Referencia fundamental para HTML, CSS, JavaScript, Web APIs, accesibilidad, HTTP y estándares web.",
    category: "Web y móvil",
    type: "Documentación",
    language: "ES/EN",
    level: "Todos",
    license: "CC BY-SA / licencias del código según contenido",
    url: "https://developer.mozilla.org/es/",
    tags: ["html", "css", "javascript", "web api", "documentación"],
    featured: true,
  },
  {
    id: "javascript-info",
    title: "JavaScript.info",
    provider: "JavaScript.info",
    description: "Tutorial moderno y profundo de JavaScript, desde fundamentos hasta navegador, eventos, red y patrones del lenguaje.",
    category: "Web y móvil",
    type: "Apuntes",
    language: "ES/EN",
    level: "Todos",
    license: "CC BY-NC-SA 4.0",
    url: "https://es.javascript.info/",
    tags: ["javascript", "tutorial", "web", "español"],
  },
  {
    id: "react-docs",
    title: "React Documentation",
    provider: "React",
    description: "Documentación oficial moderna de React con tutorial, hooks, estado, renderizado y patrones recomendados.",
    category: "Web y móvil",
    type: "Documentación",
    language: "ES/EN",
    level: "Todos",
    license: "MIT para React; documentación según proyecto",
    url: "https://react.dev/",
    tags: ["react", "frontend", "javascript", "documentación"],
  },
  {
    id: "typescript-docs",
    title: "TypeScript Handbook",
    provider: "Microsoft",
    description: "Documentación oficial de TypeScript: tipos, narrowing, generics, módulos, configuración y patrones avanzados.",
    category: "Web y móvil",
    type: "Documentación",
    language: "EN",
    level: "Todos",
    license: "Apache/MIT según repositorio",
    url: "https://www.typescriptlang.org/docs/handbook/intro.html",
    tags: ["typescript", "javascript", "frontend", "backend"],
  },
  {
    id: "webdev",
    title: "web.dev",
    provider: "Google",
    description: "Guías oficiales sobre rendimiento web, Core Web Vitals, accesibilidad, PWA, CSS, HTML y prácticas modernas.",
    category: "Web y móvil",
    type: "Documentación",
    language: "ES/EN",
    level: "Intermedio",
    license: "Contenido de Google según términos",
    url: "https://web.dev/",
    tags: ["performance", "pwa", "accessibility", "web vitals"],
  },
  {
    id: "a11y-project",
    title: "The A11Y Project",
    provider: "A11Y Project",
    description: "Checklist, patrones y recursos para construir experiencias web accesibles.",
    category: "Web y móvil",
    type: "Documentación",
    language: "EN",
    level: "Todos",
    license: "Open source / CC según contenido",
    url: "https://www.a11yproject.com/",
    tags: ["accesibilidad", "a11y", "web", "ux"],
  },
  {
    id: "android-dev",
    title: "Android Developers",
    provider: "Google",
    description: "Documentación, cursos, codelabs y buenas prácticas oficiales para Android, Kotlin, Compose y rendimiento móvil.",
    category: "Web y móvil",
    type: "Documentación",
    language: "ES/EN",
    level: "Todos",
    license: "Documentación oficial de Google",
    url: "https://developer.android.com/",
    tags: ["android", "kotlin", "compose", "móvil"],
  },
  {
    id: "flutter-docs",
    title: "Flutter Documentation",
    provider: "Flutter",
    description: "Documentación y codelabs oficiales para crear aplicaciones multiplataforma con Dart y Flutter.",
    category: "Web y móvil",
    type: "Documentación",
    language: "EN",
    level: "Todos",
    license: "BSD-3-Clause para Flutter; documentación según proyecto",
    url: "https://docs.flutter.dev/",
    tags: ["flutter", "dart", "móvil", "multiplataforma"],
  },
  {
    id: "swift-docs",
    title: "Swift Documentation",
    provider: "Swift.org",
    description: "Documentación oficial del lenguaje Swift y su ecosistema, útil para iOS, macOS, servidor y programación de sistemas.",
    category: "Web y móvil",
    type: "Documentación",
    language: "EN",
    level: "Todos",
    license: "Apache 2.0 para Swift; documentación según proyecto",
    url: "https://www.swift.org/documentation/",
    tags: ["swift", "ios", "apple", "móvil"],
  },

  {
    id: "kaggle-learn",
    title: "Kaggle Learn",
    provider: "Kaggle · Google",
    description: "Microcursos prácticos de Python, Pandas, SQL, Machine Learning, Deep Learning, Computer Vision, NLP y Data Visualization.",
    category: "Datos e IA",
    type: "Curso",
    language: "EN",
    level: "Inicial",
    license: "Acceso gratuito; datasets con licencias individuales",
    url: "https://www.kaggle.com/learn",
    tags: ["data science", "machine learning", "python", "sql", "datasets"],
    featured: true,
  },
  {
    id: "fastai",
    title: "Practical Deep Learning for Coders",
    provider: "fast.ai",
    description: "Curso gratuito y práctico de deep learning con enfoque de arriba hacia abajo, notebooks y proyectos reales.",
    category: "Datos e IA",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "Material gratuito / licencias del proyecto",
    url: "https://course.fast.ai/",
    tags: ["deep learning", "pytorch", "ai", "curso"],
    featured: true,
  },
  {
    id: "huggingface-course",
    title: "Hugging Face Learn",
    provider: "Hugging Face",
    description: "Cursos abiertos sobre NLP, Transformers, LLMs, agentes, audio, visión, difusión y herramientas del ecosistema Hugging Face.",
    category: "Datos e IA",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "Open source / licencias por curso y repositorio",
    url: "https://huggingface.co/learn",
    tags: ["llm", "nlp", "transformers", "agents", "machine learning"],
    featured: true,
  },
  {
    id: "google-ml-crash-course",
    title: "Machine Learning Crash Course",
    provider: "Google for Developers",
    description: "Curso oficial de Google sobre fundamentos de ML, regresión, clasificación, redes neuronales, embeddings, producción y responsabilidad.",
    category: "Datos e IA",
    type: "Curso",
    language: "ES/EN",
    level: "Inicial",
    license: "Contenido oficial de Google",
    url: "https://developers.google.com/machine-learning/crash-course",
    tags: ["machine learning", "google", "curso", "ia"],
  },
  {
    id: "d2l",
    title: "Dive into Deep Learning",
    provider: "D2L.ai",
    description: "Libro interactivo open source con matemáticas, código y notebooks en PyTorch/JAX/TensorFlow para deep learning moderno.",
    category: "Datos e IA",
    type: "Libro / PDF",
    language: "EN",
    level: "Intermedio",
    license: "CC BY-SA 4.0 / Apache 2.0 para código",
    url: "https://d2l.ai/",
    downloadUrl: "https://arxiv.org/pdf/2106.11342",
    tags: ["deep learning", "libro", "pytorch", "jax", "tensorflow", "pdf"],
    featured: true,
  },
  {
    id: "math-ml-book",
    title: "Mathematics for Machine Learning",
    provider: "Deisenroth · Faisal · Ong",
    description: "Libro de fundamentos matemáticos para ML: álgebra lineal, geometría, cálculo, probabilidad, optimización y métodos clásicos.",
    category: "Datos e IA",
    type: "Libro / PDF",
    language: "EN",
    level: "Intermedio",
    license: "PDF gratuito autorizado por los autores",
    url: "https://mml-book.github.io/",
    downloadUrl: "https://mml-book.github.io/book/mml-book.pdf",
    tags: ["matemáticas", "machine learning", "pdf", "álgebra", "probabilidad"],
    featured: true,
    verified: true,
  },
  {
    id: "deeplearningbook",
    title: "Deep Learning Book",
    provider: "Goodfellow · Bengio · Courville",
    description: "Texto clásico de deep learning disponible para lectura online legal desde el sitio oficial de los autores.",
    category: "Datos e IA",
    type: "Libro / PDF",
    language: "EN",
    level: "Avanzado",
    license: "Lectura online autorizada; no redistribuir copias",
    url: "https://www.deeplearningbook.org/",
    tags: ["deep learning", "matemáticas", "ai", "libro"],
  },
  {
    id: "paperswithcode",
    title: "Papers with Code",
    provider: "Papers with Code",
    description: "Índice de investigación en machine learning acompañado de implementaciones y benchmarks reproducibles.",
    category: "Datos e IA",
    type: "Paper",
    language: "EN",
    level: "Avanzado",
    license: "Papers y código con licencias individuales",
    url: "https://paperswithcode.com/",
    tags: ["papers", "benchmarks", "machine learning", "código"],
  },
  {
    id: "distill",
    title: "Distill",
    provider: "Distill",
    description: "Archivo de artículos interactivos de machine learning con visualizaciones de alta calidad sobre redes neuronales y representación.",
    category: "Datos e IA",
    type: "Apuntes",
    language: "EN",
    level: "Avanzado",
    license: "CC BY 4.0 salvo indicación",
    url: "https://distill.pub/",
    tags: ["machine learning", "visualización", "artículos", "deep learning"],
  },
  {
    id: "data-engineering-zoomcamp",
    title: "Data Engineering Zoomcamp",
    provider: "DataTalksClub · GitHub",
    description: "Curso gratuito de ingeniería de datos con Docker, Terraform, warehouses, batch, streaming, dbt y orquestación.",
    category: "Datos e IA",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "Open source / licencias del repositorio",
    url: "https://github.com/DataTalksClub/data-engineering-zoomcamp",
    tags: ["data engineering", "docker", "terraform", "dbt", "streaming"],
  },
  {
    id: "duckdb-docs",
    title: "DuckDB Documentation",
    provider: "DuckDB Foundation",
    description: "Documentación de base analítica embebida, SQL, Parquet y procesamiento local de datos.",
    category: "Datos e IA",
    type: "Documentación",
    language: "EN",
    level: "Intermedio",
    license: "MIT para DuckDB",
    url: "https://duckdb.org/docs/",
    tags: ["sql", "analytics", "parquet", "database"],
  },

  {
    id: "owasp-top10",
    title: "OWASP Top 10",
    provider: "OWASP Foundation",
    description: "Documento de referencia sobre los riesgos críticos más comunes en aplicaciones web y prácticas de mitigación.",
    category: "Ciberseguridad",
    type: "Estándar",
    language: "ES/EN",
    level: "Todos",
    license: "Creative Commons / términos OWASP",
    url: "https://owasp.org/www-project-top-ten/",
    tags: ["owasp", "web security", "appsec", "top 10"],
    featured: true,
  },
  {
    id: "owasp-wstg",
    title: "OWASP Web Security Testing Guide",
    provider: "OWASP Foundation",
    description: "Guía abierta y profunda para pruebas de seguridad web dentro de entornos autorizados.",
    category: "Ciberseguridad",
    type: "Libro / PDF",
    language: "EN",
    level: "Avanzado",
    license: "Creative Commons",
    url: "https://owasp.org/www-project-web-security-testing-guide/",
    tags: ["owasp", "pentesting", "web", "testing", "seguridad"],
  },
  {
    id: "owasp-cheatsheets",
    title: "OWASP Cheat Sheet Series",
    provider: "OWASP Foundation",
    description: "Guías prácticas de secure coding, autenticación, sesiones, APIs, criptografía, logging y numerosas áreas de AppSec.",
    category: "Ciberseguridad",
    type: "Apuntes",
    language: "EN",
    level: "Intermedio",
    license: "Creative Commons",
    url: "https://cheatsheetseries.owasp.org/",
    tags: ["appsec", "secure coding", "cheatsheets", "owasp"],
  },
  {
    id: "portswigger-academy",
    title: "Web Security Academy",
    provider: "PortSwigger",
    description: "Laboratorios interactivos gratuitos sobre seguridad web: SQLi, XSS, SSRF, auth, APIs, request smuggling y más.",
    category: "Ciberseguridad",
    type: "Práctica",
    language: "EN",
    level: "Todos",
    license: "Acceso gratuito; términos de PortSwigger",
    url: "https://portswigger.net/web-security",
    tags: ["pentesting", "web security", "labs", "burp suite"],
    featured: true,
  },
  {
    id: "picoctf",
    title: "picoCTF",
    provider: "Carnegie Mellon University",
    description: "Plataforma gratuita de retos CTF educativos para aprender seguridad en un entorno legal y controlado.",
    category: "Ciberseguridad",
    type: "Práctica",
    language: "EN",
    level: "Inicial",
    license: "Acceso gratuito / términos del proyecto",
    url: "https://picoctf.org/",
    tags: ["ctf", "seguridad", "hacking ético", "práctica"],
  },
  {
    id: "overthewire",
    title: "OverTheWire Wargames",
    provider: "OverTheWire",
    description: "Wargames progresivos para Linux, redes y seguridad en servidores preparados específicamente para entrenamiento.",
    category: "Ciberseguridad",
    type: "Práctica",
    language: "EN",
    level: "Inicial",
    license: "Acceso educativo gratuito",
    url: "https://overthewire.org/wargames/",
    tags: ["linux", "wargame", "seguridad", "práctica"],
  },
  {
    id: "pwncollege",
    title: "pwn.college",
    provider: "Arizona State University",
    description: "Plataforma educativa con laboratorios estructurados de seguridad de sistemas, binarios, web y fundamentos ofensivos dentro de sandbox autorizado.",
    category: "Ciberseguridad",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "Material educativo abierto según curso",
    url: "https://pwn.college/",
    tags: ["binary exploitation", "web", "systems", "security"],
  },
  {
    id: "nist-csf",
    title: "NIST Cybersecurity Framework",
    provider: "NIST",
    description: "Marco oficial para gestionar riesgos de ciberseguridad, gobierno, identificación, protección, detección, respuesta y recuperación.",
    category: "Ciberseguridad",
    type: "Estándar",
    language: "EN",
    level: "Intermedio",
    license: "Publicación gubernamental",
    url: "https://www.nist.gov/cyberframework",
    tags: ["nist", "framework", "grc", "risk", "security"],
  },
  {
    id: "mitre-attack",
    title: "MITRE ATT&CK",
    provider: "MITRE",
    description: "Base de conocimiento de tácticas y técnicas adversarias ampliamente usada en operaciones defensivas, threat intelligence y detección.",
    category: "Ciberseguridad",
    type: "Documentación",
    language: "EN",
    level: "Avanzado",
    license: "Términos de uso de MITRE ATT&CK",
    url: "https://attack.mitre.org/",
    tags: ["blue team", "soc", "threat intelligence", "attack"],
  },
  {
    id: "cryptohack",
    title: "CryptoHack",
    provider: "CryptoHack",
    description: "Retos interactivos de criptografía moderna para aprender matemáticas, cifrado, RSA, curvas elípticas y ataques conceptuales en entorno educativo.",
    category: "Ciberseguridad",
    type: "Práctica",
    language: "EN",
    level: "Intermedio",
    license: "Acceso gratuito",
    url: "https://cryptohack.org/",
    tags: ["criptografía", "rsa", "ecc", "ctf"],
  },

  {
    id: "cisco-skills",
    title: "Cisco Networking Academy / Skills for All",
    provider: "Cisco",
    description: "Cursos oficiales de redes, ciberseguridad, Packet Tracer, IoT y fundamentos de infraestructura.",
    category: "Redes y telecom",
    type: "Curso",
    language: "ES/EN",
    level: "Todos",
    license: "Acceso gratuito en cursos seleccionados",
    url: "https://www.netacad.com/",
    tags: ["cisco", "ccna", "packet tracer", "networking", "iot"],
    featured: true,
  },
  {
    id: "ietf-rfc",
    title: "RFC Editor",
    provider: "IETF / RFC Editor",
    description: "Archivo oficial de RFCs que definen los protocolos y estándares fundamentales de Internet.",
    category: "Redes y telecom",
    type: "Estándar",
    language: "EN",
    level: "Avanzado",
    license: "IETF Trust legal provisions",
    url: "https://www.rfc-editor.org/",
    tags: ["ietf", "rfc", "tcp/ip", "protocolos", "internet"],
    featured: true,
  },
  {
    id: "wireshark-docs",
    title: "Wireshark User’s Guide",
    provider: "Wireshark Foundation",
    description: "Documentación oficial para captura, análisis y diagnóstico de protocolos y tráfico de red.",
    category: "Redes y telecom",
    type: "Documentación",
    language: "EN",
    level: "Intermedio",
    license: "GPL / documentación del proyecto",
    url: "https://www.wireshark.org/docs/wsug_html_chunked/",
    tags: ["wireshark", "protocolos", "network analysis", "packets"],
  },
  {
    id: "juniper-open-learning",
    title: "Juniper Open Learning",
    provider: "Juniper Networks",
    description: "Rutas oficiales de aprendizaje sobre routing, switching, automation, security y tecnologías Juniper.",
    category: "Redes y telecom",
    type: "Curso",
    language: "EN",
    level: "Todos",
    license: "Acceso gratuito a contenidos seleccionados",
    url: "https://learningportal.juniper.net/juniper/user_activity_info.aspx?id=11478",
    tags: ["juniper", "routing", "switching", "automation", "networking"],
  },
  {
    id: "3gpp",
    title: "3GPP Specifications",
    provider: "3GPP",
    description: "Especificaciones oficiales para sistemas móviles 3G, LTE, 5G y evolución de telecomunicaciones celulares.",
    category: "Redes y telecom",
    type: "Estándar",
    language: "EN",
    level: "Avanzado",
    license: "Términos 3GPP",
    url: "https://www.3gpp.org/specifications-technologies/specifications-by-series",
    tags: ["5g", "lte", "ran", "core", "telecom"],
  },
  {
    id: "srsran",
    title: "srsRAN Project",
    provider: "SRS",
    description: "Stack open source de radio y 5G para investigación y laboratorios de telecomunicaciones.",
    category: "Redes y telecom",
    type: "Repositorio",
    language: "EN",
    level: "Avanzado",
    license: "AGPL / licencias del proyecto",
    url: "https://github.com/srsran/srsRAN_Project",
    tags: ["5g", "ran", "radio", "telecom", "open source"],
  },
  {
    id: "open5gs",
    title: "Open5GS",
    provider: "Open5GS · GitHub",
    description: "Implementación open source de EPC y 5G Core para laboratorios, investigación y aprendizaje de redes móviles.",
    category: "Redes y telecom",
    type: "Repositorio",
    language: "EN",
    level: "Avanzado",
    license: "AGPL-3.0",
    url: "https://github.com/open5gs/open5gs",
    tags: ["5g core", "epc", "mobile network", "telecom"],
  },

  {
    id: "linux-command-line",
    title: "The Linux Command Line",
    provider: "William Shotts · LinuxCommand.org",
    description: "Libro gratuito sobre shell, comandos, scripting y trabajo práctico en Linux.",
    category: "Cloud, DevOps y sistemas",
    type: "Libro / PDF",
    language: "EN",
    level: "Inicial",
    license: "Creative Commons BY-NC-ND según edición",
    url: "https://linuxcommand.org/tlcl.php",
    tags: ["linux", "shell", "bash", "libro", "sysadmin"],
    featured: true,
  },
  {
    id: "kubernetes-docs",
    title: "Kubernetes Documentation",
    provider: "CNCF / Kubernetes",
    description: "Documentación oficial de Kubernetes: conceptos, workloads, redes, storage, seguridad, administración y extensibilidad.",
    category: "Cloud, DevOps y sistemas",
    type: "Documentación",
    language: "ES/EN",
    level: "Todos",
    license: "CC BY 4.0 / Apache 2.0 para código",
    url: "https://kubernetes.io/docs/home/",
    tags: ["kubernetes", "containers", "cloud native", "devops"],
    featured: true,
  },
  {
    id: "docker-docs",
    title: "Docker Documentation",
    provider: "Docker",
    description: "Documentación oficial sobre contenedores, imágenes, Compose, networking, storage y seguridad.",
    category: "Cloud, DevOps y sistemas",
    type: "Documentación",
    language: "EN",
    level: "Todos",
    license: "Apache 2.0 / términos de Docker",
    url: "https://docs.docker.com/",
    tags: ["docker", "containers", "devops", "compose"],
  },
  {
    id: "terraform-tutorials",
    title: "Terraform Tutorials",
    provider: "HashiCorp",
    description: "Tutoriales oficiales de infraestructura como código para AWS, Azure, Google Cloud y flujos de trabajo con Terraform.",
    category: "Cloud, DevOps y sistemas",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "BUSL/MPL según producto y documentación",
    url: "https://developer.hashicorp.com/terraform/tutorials",
    tags: ["terraform", "iac", "cloud", "automation"],
  },
  {
    id: "microsoft-learn",
    title: "Microsoft Learn",
    provider: "Microsoft",
    description: "Rutas oficiales gratuitas para Azure, Windows, PowerShell, .NET, Security, Data, Power Platform y administración empresarial.",
    category: "Cloud, DevOps y sistemas",
    type: "Curso",
    language: "ES/EN",
    level: "Todos",
    license: "Contenido oficial de Microsoft",
    url: "https://learn.microsoft.com/es-es/training/",
    tags: ["azure", "windows", "powershell", "cloud", "microsoft"],
    featured: true,
  },
  {
    id: "aws-skill-builder",
    title: "AWS Skill Builder",
    provider: "Amazon Web Services",
    description: "Cursos digitales oficiales sobre cloud, arquitectura, seguridad, datos, IA y operaciones en AWS; parte del catálogo es gratuito.",
    category: "Cloud, DevOps y sistemas",
    type: "Curso",
    language: "ES/EN",
    level: "Todos",
    license: "Acceso gratuito y premium según curso",
    url: "https://skillbuilder.aws/",
    tags: ["aws", "cloud", "architecture", "devops"],
  },
  {
    id: "google-cloud-learning",
    title: "Google Cloud Training",
    provider: "Google Cloud",
    description: "Rutas oficiales, labs y documentación para infraestructura, datos, Kubernetes, networking, DevOps e IA en Google Cloud.",
    category: "Cloud, DevOps y sistemas",
    type: "Curso",
    language: "ES/EN",
    level: "Todos",
    license: "Contenido oficial de Google",
    url: "https://cloud.google.com/learn/training",
    tags: ["gcp", "cloud", "kubernetes", "data", "ai"],
  },
  {
    id: "cncf-landscape",
    title: "CNCF Landscape",
    provider: "Cloud Native Computing Foundation",
    description: "Mapa de proyectos y productos cloud native para entender el ecosistema de contenedores, observabilidad, seguridad, service mesh y plataformas.",
    category: "Cloud, DevOps y sistemas",
    type: "Roadmap",
    language: "EN",
    level: "Intermedio",
    license: "Apache 2.0 para el proyecto landscape",
    url: "https://landscape.cncf.io/",
    tags: ["cncf", "cloud native", "kubernetes", "observability"],
  },
  {
    id: "google-sre-books",
    title: "Google SRE Books",
    provider: "Google",
    description: "Libros gratuitos online sobre Site Reliability Engineering, prácticas de producción, monitoreo, incidentes y confiabilidad.",
    category: "Cloud, DevOps y sistemas",
    type: "Libro / PDF",
    language: "EN",
    level: "Avanzado",
    license: "Lectura gratuita autorizada por Google",
    url: "https://sre.google/books/",
    tags: ["sre", "reliability", "operations", "observability", "book"],
    featured: true,
  },

  {
    id: "riscv-specs",
    title: "RISC-V Specifications",
    provider: "RISC-V International",
    description: "Especificaciones abiertas de la ISA RISC-V y documentos técnicos para arquitectura de procesadores.",
    category: "Hardware, IoT y robótica",
    type: "Estándar",
    language: "EN",
    level: "Avanzado",
    license: "Licencias abiertas indicadas por RISC-V",
    url: "https://riscv.org/technical/specifications/",
    tags: ["risc-v", "cpu", "isa", "architecture", "hardware"],
    featured: true,
  },
  {
    id: "ben-eater",
    title: "Ben Eater",
    provider: "Ben Eater · YouTube",
    description: "Series prácticas sobre construcción de CPU de 8 bits, buses, memoria, lógica digital y redes desde primeros principios.",
    category: "Hardware, IoT y robótica",
    type: "Video",
    language: "EN",
    level: "Intermedio",
    license: "YouTube / derechos del autor",
    url: "https://www.youtube.com/@BenEater",
    tags: ["cpu", "digital logic", "hardware", "electronics"],
    featured: true,
  },
  {
    id: "arduino-docs",
    title: "Arduino Documentation",
    provider: "Arduino",
    description: "Documentación oficial de placas, microcontroladores, APIs, tutoriales, ejemplos y ecosistema Arduino.",
    category: "Hardware, IoT y robótica",
    type: "Documentación",
    language: "EN",
    level: "Inicial",
    license: "Licencias del proyecto Arduino",
    url: "https://docs.arduino.cc/",
    tags: ["arduino", "microcontrollers", "iot", "embedded"],
  },
  {
    id: "raspberrypi-docs",
    title: "Raspberry Pi Documentation",
    provider: "Raspberry Pi",
    description: "Guías oficiales de Raspberry Pi, Linux, GPIO, hardware, cámaras, microcontroladores Pico y proyectos.",
    category: "Hardware, IoT y robótica",
    type: "Documentación",
    language: "EN",
    level: "Todos",
    license: "Documentación oficial",
    url: "https://www.raspberrypi.com/documentation/",
    tags: ["raspberry pi", "linux", "gpio", "embedded", "iot"],
  },
  {
    id: "freertos",
    title: "FreeRTOS Documentation",
    provider: "FreeRTOS / AWS",
    description: "Documentación y demos del RTOS ampliamente usado en microcontroladores y sistemas embebidos.",
    category: "Hardware, IoT y robótica",
    type: "Documentación",
    language: "EN",
    level: "Intermedio",
    license: "MIT para FreeRTOS kernel",
    url: "https://www.freertos.org/Documentation/RTOS_book.html",
    tags: ["rtos", "embedded", "microcontroller", "firmware"],
  },
  {
    id: "zephyr",
    title: "Zephyr Project Documentation",
    provider: "Linux Foundation / Zephyr",
    description: "RTOS open source para dispositivos embebidos e IoT con documentación de drivers, networking, Bluetooth y seguridad.",
    category: "Hardware, IoT y robótica",
    type: "Documentación",
    language: "EN",
    level: "Avanzado",
    license: "Apache 2.0",
    url: "https://docs.zephyrproject.org/latest/",
    tags: ["rtos", "embedded", "iot", "bluetooth", "linux foundation"],
  },
  {
    id: "wokwi",
    title: "Wokwi",
    provider: "Wokwi",
    description: "Simulador en navegador para Arduino, ESP32, Raspberry Pi Pico, sensores, displays y prototipos electrónicos.",
    category: "Hardware, IoT y robótica",
    type: "Simulador",
    language: "EN",
    level: "Todos",
    license: "Servicio online; proyectos del usuario con sus propias licencias",
    url: "https://wokwi.com/",
    tags: ["arduino", "esp32", "simulation", "iot", "electronics"],
    featured: true,
  },
  {
    id: "ros-docs",
    title: "ROS 2 Documentation",
    provider: "Open Robotics",
    description: "Documentación oficial del Robot Operating System 2: nodos, topics, services, actions, launch, middleware y tooling.",
    category: "Hardware, IoT y robótica",
    type: "Documentación",
    language: "EN",
    level: "Intermedio",
    license: "Apache 2.0 / BSD según paquetes",
    url: "https://docs.ros.org/en/rolling/",
    tags: ["ros2", "robotics", "middleware", "autonomous systems"],
    featured: true,
  },
  {
    id: "gazebo-docs",
    title: "Gazebo Documentation",
    provider: "Open Robotics",
    description: "Simulación robótica 3D, sensores, física, mundos y flujos integrados con ROS.",
    category: "Hardware, IoT y robótica",
    type: "Simulador",
    language: "EN",
    level: "Intermedio",
    license: "Apache 2.0 / licencias del proyecto",
    url: "https://gazebosim.org/docs",
    tags: ["gazebo", "robotics", "simulation", "ros"],
  },
  {
    id: "openroad",
    title: "OpenROAD Project",
    provider: "OpenROAD",
    description: "Flujo open source de automatización EDA para diseño físico de circuitos integrados y experimentación académica en chips.",
    category: "Hardware, IoT y robótica",
    type: "Repositorio",
    language: "EN",
    level: "Avanzado",
    license: "BSD-3-Clause / licencias de subproyectos",
    url: "https://theopenroadproject.org/",
    tags: ["eda", "asic", "vlsi", "chip design"],
  },

  {
    id: "arxiv-cs",
    title: "arXiv · Computer Science",
    provider: "Cornell University",
    description: "Preprints abiertos de investigación en IA, teoría, sistemas, redes, seguridad, visión, NLP, robótica, computación cuántica y más.",
    category: "Matemáticas e investigación",
    type: "Paper",
    language: "EN",
    level: "Avanzado",
    license: "Licencia indicada por cada preprint",
    url: "https://arxiv.org/archive/cs",
    tags: ["papers", "research", "computer science", "preprints"],
    featured: true,
  },
  {
    id: "semantic-scholar",
    title: "Semantic Scholar",
    provider: "Allen Institute for AI",
    description: "Buscador académico para descubrir papers, autores, citas y relaciones entre publicaciones de computación y ciencia.",
    category: "Matemáticas e investigación",
    type: "Paper",
    language: "EN",
    level: "Todos",
    license: "Metadatos y papers con licencias individuales",
    url: "https://www.semanticscholar.org/",
    tags: ["papers", "search", "research", "citations"],
  },
  {
    id: "core-ac",
    title: "CORE",
    provider: "CORE",
    description: "Agregador de literatura científica de acceso abierto procedente de repositorios y revistas de todo el mundo.",
    category: "Matemáticas e investigación",
    type: "Paper",
    language: "EN",
    level: "Todos",
    license: "Open access / licencias de cada documento",
    url: "https://core.ac.uk/",
    tags: ["papers", "open access", "research", "pdf"],
  },
  {
    id: "doaj",
    title: "Directory of Open Access Journals",
    provider: "DOAJ",
    description: "Directorio de revistas académicas open access para localizar publicaciones legalmente accesibles.",
    category: "Matemáticas e investigación",
    type: "Paper",
    language: "ES/EN",
    level: "Todos",
    license: "Open access / licencias por revista",
    url: "https://doaj.org/",
    tags: ["journals", "open access", "papers", "research"],
  },
  {
    id: "zenodo",
    title: "Zenodo",
    provider: "CERN / OpenAIRE",
    description: "Repositorio de papers, datasets, software, notebooks y materiales de investigación con DOI.",
    category: "Matemáticas e investigación",
    type: "Dataset",
    language: "EN",
    level: "Todos",
    license: "Licencia indicada por cada depósito",
    url: "https://zenodo.org/",
    tags: ["datasets", "papers", "software", "doi", "research"],
  },
  {
    id: "openalex",
    title: "OpenAlex",
    provider: "OurResearch",
    description: "Catálogo abierto de trabajos académicos, autores, instituciones, conceptos y citas, útil para investigación y bibliometría.",
    category: "Matemáticas e investigación",
    type: "Dataset",
    language: "EN",
    level: "Avanzado",
    license: "CC0 para datos OpenAlex",
    url: "https://openalex.org/",
    tags: ["research", "bibliometrics", "dataset", "open data"],
  },
  {
    id: "3b1b-linear-algebra",
    title: "Essence of Linear Algebra",
    provider: "3Blue1Brown",
    description: "Serie visual de referencia para comprender vectores, transformaciones, matrices, determinantes, eigenvectors y espacios vectoriales.",
    category: "Matemáticas e investigación",
    type: "Video",
    language: "EN",
    level: "Inicial",
    license: "YouTube / derechos del autor",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr",
    embedUrl: "https://www.youtube.com/embed/videoseries?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr",
    tags: ["linear algebra", "matemáticas", "visual", "video"],
    featured: true,
  },
  {
    id: "khan-math",
    title: "Khan Academy · Matemáticas",
    provider: "Khan Academy",
    description: "Rutas gratuitas en español de álgebra, cálculo, estadística, probabilidad y matemáticas útiles para computación.",
    category: "Matemáticas e investigación",
    type: "Curso",
    language: "ES",
    level: "Todos",
    license: "CC BY-NC-SA para gran parte del contenido",
    url: "https://es.khanacademy.org/math",
    tags: ["matemáticas", "español", "álgebra", "cálculo", "probabilidad"],
  },

  {
    id: "ibm-quantum-learning",
    title: "IBM Quantum Learning",
    provider: "IBM Quantum",
    description: "Cursos y módulos oficiales sobre información cuántica, circuitos, algoritmos y programación con Qiskit.",
    category: "Cuántica y frontera",
    type: "Curso",
    language: "EN",
    level: "Intermedio",
    license: "Contenido oficial IBM",
    url: "https://learning.quantum.ibm.com/",
    tags: ["quantum", "qiskit", "circuits", "ibm"],
    featured: true,
  },
  {
    id: "qiskit-docs",
    title: "Qiskit Documentation",
    provider: "IBM / Qiskit",
    description: "Documentación del SDK open source Qiskit para circuitos, transpilation, simulación y ejecución en hardware cuántico.",
    category: "Cuántica y frontera",
    type: "Documentación",
    language: "EN",
    level: "Intermedio",
    license: "Apache 2.0",
    url: "https://docs.quantum.ibm.com/",
    tags: ["qiskit", "quantum", "python", "ibm"],
  },
  {
    id: "pennylane",
    title: "PennyLane Demos",
    provider: "Xanadu",
    description: "Tutoriales interactivos de computación cuántica, quantum machine learning y programación diferenciable.",
    category: "Cuántica y frontera",
    type: "Práctica",
    language: "EN",
    level: "Intermedio",
    license: "Apache 2.0 para PennyLane; demos según repositorio",
    url: "https://pennylane.ai/qml/demonstrations",
    tags: ["quantum machine learning", "pennylane", "qml", "tutorials"],
  },
  {
    id: "webgpu",
    title: "WebGPU · MDN",
    provider: "Mozilla MDN",
    description: "Referencia moderna para computación y gráficos GPU desde el navegador mediante WebGPU.",
    category: "Cuántica y frontera",
    type: "Documentación",
    language: "EN",
    level: "Avanzado",
    license: "CC BY-SA / MDN",
    url: "https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API",
    tags: ["webgpu", "gpu", "graphics", "compute"],
  },
  {
    id: "wasm",
    title: "WebAssembly · MDN",
    provider: "Mozilla MDN",
    description: "Documentación y conceptos para ejecutar código compilado de alto rendimiento dentro del navegador.",
    category: "Cuántica y frontera",
    type: "Documentación",
    language: "ES/EN",
    level: "Intermedio",
    license: "CC BY-SA / MDN",
    url: "https://developer.mozilla.org/es/docs/WebAssembly",
    tags: ["webassembly", "wasm", "performance", "browser"],
  },
  {
    id: "learnopengl",
    title: "LearnOpenGL",
    provider: "Joey de Vries",
    description: "Libro/tutorial online de gráficos 3D modernos con OpenGL: pipeline, iluminación, materiales, modelos, PBR y técnicas avanzadas.",
    category: "Cuántica y frontera",
    type: "Libro / PDF",
    language: "EN",
    level: "Intermedio",
    license: "CC BY-NC 4.0 para el contenido",
    url: "https://learnopengl.com/",
    tags: ["opengl", "graphics", "3d", "shaders"],
  },
  {
    id: "godot-docs",
    title: "Godot Engine Documentation",
    provider: "Godot Engine",
    description: "Documentación oficial de motor open source 2D/3D, scripting, física, shaders, XR y exportación multiplataforma.",
    category: "Cuántica y frontera",
    type: "Documentación",
    language: "ES/EN",
    level: "Todos",
    license: "MIT para Godot / CC BY 3.0 documentación",
    url: "https://docs.godotengine.org/es/stable/",
    tags: ["godot", "gamedev", "3d", "2d", "xr"],
  },
  {
    id: "threejs-docs",
    title: "Three.js Documentation & Examples",
    provider: "Three.js",
    description: "Documentación, ejemplos y demos para gráficos 3D WebGL/WebGPU en navegador.",
    category: "Cuántica y frontera",
    type: "Documentación",
    language: "EN",
    level: "Intermedio",
    license: "MIT",
    url: "https://threejs.org/docs/",
    tags: ["threejs", "webgl", "webgpu", "3d", "graphics"],
  },

  {
    id: "scrum-guide",
    title: "Scrum Guide",
    provider: "ScrumGuides.org",
    description: "Guía oficial de Scrum de sus co-creadores, disponible gratuitamente y con traducciones oficiales al español.",
    category: "Gestión y arquitectura",
    type: "Libro / PDF",
    language: "ES/EN",
    level: "Todos",
    license: "Uso permitido según ScrumGuides.org",
    url: "https://scrumguides.org/download.html",
    tags: ["scrum", "agile", "project management", "español", "pdf"],
    featured: true,
    verified: true,
  },
  {
    id: "agile-manifesto",
    title: "Manifesto for Agile Software Development",
    provider: "Agile Manifesto",
    description: "Texto original y principios del desarrollo ágil, disponible en múltiples idiomas incluido español.",
    category: "Gestión y arquitectura",
    type: "Estándar",
    language: "ES/EN",
    level: "Todos",
    license: "Copyright de los autores; libre consulta",
    url: "https://agilemanifesto.org/iso/es/manifesto.html",
    tags: ["agile", "manifesto", "software", "management"],
  },
  {
    id: "swebok",
    title: "SWEBOK Guide",
    provider: "IEEE Computer Society",
    description: "Cuerpo de conocimiento de Ingeniería de Software: requisitos, diseño, construcción, testing, mantenimiento, procesos, calidad y economía.",
    category: "Gestión y arquitectura",
    type: "Estándar",
    language: "EN",
    level: "Avanzado",
    license: "IEEE / acceso según edición",
    url: "https://www.computer.org/education/bodies-of-knowledge/software-engineering",
    tags: ["software engineering", "swebok", "ieee", "standards"],
  },
  {
    id: "sebok",
    title: "SEBoK · Systems Engineering Body of Knowledge",
    provider: "INCOSE / IEEE / Stevens Institute",
    description: "Cuerpo de conocimiento abierto para ingeniería de sistemas, ciclo de vida, arquitectura, modelado y gestión técnica.",
    category: "Gestión y arquitectura",
    type: "Libro / PDF",
    language: "EN",
    level: "Avanzado",
    license: "Creative Commons Attribution-NonCommercial-ShareAlike",
    url: "https://sebokwiki.org/wiki/Guide_to_the_Systems_Engineering_Body_of_Knowledge_(SEBoK)",
    tags: ["systems engineering", "architecture", "sebok", "lifecycle"],
  },
  {
    id: "c4model",
    title: "C4 Model",
    provider: "Simon Brown",
    description: "Modelo simple para comunicar arquitectura de software mediante diagramas de contexto, contenedores, componentes y código.",
    category: "Gestión y arquitectura",
    type: "Documentación",
    language: "EN",
    level: "Intermedio",
    license: "CC BY 4.0 para el sitio/modelo",
    url: "https://c4model.com/",
    tags: ["architecture", "diagrams", "software design", "c4"],
  },
  {
    id: "arc42",
    title: "arc42 Documentation",
    provider: "arc42",
    description: "Plantilla open source para documentar arquitectura de software de forma estructurada y profesional.",
    category: "Gestión y arquitectura",
    type: "Documentación",
    language: "ES/EN",
    level: "Intermedio",
    license: "CC BY-SA 4.0",
    url: "https://arc42.org/",
    tags: ["architecture", "documentation", "software", "template"],
  },
  {
    id: "aws-well-architected",
    title: "AWS Well-Architected Framework",
    provider: "Amazon Web Services",
    description: "Principios y mejores prácticas oficiales para diseñar sistemas cloud seguros, confiables, eficientes, sostenibles y costo-efectivos.",
    category: "Gestión y arquitectura",
    type: "Estándar",
    language: "ES/EN",
    level: "Avanzado",
    license: "Contenido oficial AWS",
    url: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html",
    tags: ["architecture", "aws", "cloud", "reliability", "security"],
  },
  {
    id: "azure-well-architected",
    title: "Azure Well-Architected Framework",
    provider: "Microsoft",
    description: "Guía oficial de arquitectura en Azure para confiabilidad, seguridad, optimización de costos, excelencia operativa y rendimiento.",
    category: "Gestión y arquitectura",
    type: "Estándar",
    language: "ES/EN",
    level: "Avanzado",
    license: "Contenido oficial Microsoft",
    url: "https://learn.microsoft.com/es-es/azure/well-architected/",
    tags: ["architecture", "azure", "cloud", "reliability"],
  },
]

const allResources: ResourceItem[] = [...baseResources, ...expandedSpanishResources]

function normalizeResourceKey(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLocaleLowerCase("es")
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .replace(/[?#].*$/, "")
    .replace(/\/$/, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
}

const seenUrls = new Set<string>()
const seenTitleProvider = new Set<string>()
export const resources: ResourceItem[] = allResources.filter((resource) => {
  const urlKey = normalizeResourceKey(resource.downloadUrl ?? resource.url)
  const titleProviderKey = `${normalizeResourceKey(resource.title)}|${normalizeResourceKey(resource.provider)}`
  if (seenUrls.has(urlKey) || seenTitleProvider.has(titleProviderKey)) return false
  seenUrls.add(urlKey)
  seenTitleProvider.add(titleProviderKey)
  return true
})

export const featuredResources = resources.filter((resource) => resource.featured)
