import { useEffect, useState } from "react";
import Icon from "./Icon";
import {applySnapshot,collectSnapshot,loadLocalSnapshot,pullCloud,pushCloud,saveLocalSnapshot,smartCloudSync,type CampusSnapshot} from "./sync-engine";

export default function SyncCenter(){
  const [online,setOnline]=useState(navigator.onLine);const [last,setLast]=useState<string>("");const [status,setStatus]=useState("Local-first activo");const [installEvent,setInstallEvent]=useState<Event|null>(null);
  useEffect(()=>{const on=()=>setOnline(navigator.onLine);window.addEventListener("online",on);window.addEventListener("offline",on);const before=(e:Event)=>{e.preventDefault();setInstallEvent(e)};window.addEventListener("beforeinstallprompt",before);loadLocalSnapshot().then(s=>s&&setLast(s.createdAt)).catch(()=>{});const endpoint=import.meta.env.VITE_SYNC_ENDPOINT as string|undefined;let timer:number|undefined;if(endpoint){const run=()=>navigator.onLine&&smartCloudSync().then(r=>{setLast(r.snapshot.createdAt);setStatus(`Sincronización automática: ${r.direction==="down"?"nube → dispositivo":"dispositivo → nube"}`)}).catch(()=>{});timer=window.setInterval(run,60000);window.setTimeout(run,2500)}return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",on);window.removeEventListener("beforeinstallprompt",before);if(timer)window.clearInterval(timer)}},[]);
  const save=async()=>{const s=await saveLocalSnapshot();setLast(s.createdAt);setStatus("Copia local guardada en IndexedDB")};
  const exportJson=()=>{const blob=new Blob([JSON.stringify(collectSnapshot(),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`campus-maestro-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
  const importJson=async(file?:File)=>{if(!file)return;const s=JSON.parse(await file.text()) as CampusSnapshot;applySnapshot(s);await saveLocalSnapshot(s);setStatus("Copia importada; recarga para reflejar todos los cambios")};
  const cloud=async(direction:"up"|"down")=>{try{setStatus("Sincronizando…");if(direction==="up")await pushCloud(await saveLocalSnapshot());else{const s=await pullCloud();applySnapshot(s);await saveLocalSnapshot(s)}setStatus("Sincronización de nube completada") }catch(e){setStatus(e instanceof Error?e.message:"No se pudo sincronizar")}};
  const install=async()=>{const e=installEvent as Event & {prompt?:()=>Promise<void>};await e.prompt?.();setInstallEvent(null)};
  return <section className="sync-center page-section reveal-section" id="sincronizacion"><div className="section-head"><span>PLATAFORMA · LOCAL-FIRST</span><h2>Estudia sin conexión.<br/><em>Sincroniza cuando haya nube.</em></h2><p>La base local usa IndexedDB, exportación/importación y PWA. Si VITE_SYNC_ENDPOINT está configurado, el campus compara snapshots y sincroniza automáticamente cada minuto; sin un endpoint real no finge una nube inexistente.</p></div>
    <div className="sync-grid"><article><Icon name="device"/><span>DISPOSITIVO</span><h3>{online?"En línea":"Sin conexión"}</h3><p>El campus y tu copia local siguen disponibles según lo almacenado por el navegador.</p></article><article><Icon name="database"/><span>INDEXEDDB</span><h3>Copia local</h3><p>{last?`Última: ${new Date(last).toLocaleString("es-PE")}`:"Todavía no se creó una copia"}</p><button onClick={save}>Guardar ahora</button></article><article><Icon name="cloud"/><span>NUBE</span><h3>Adaptador preparado</h3><p>{status}</p><div><button onClick={()=>cloud("up")}>Subir</button><button onClick={()=>cloud("down")}>Bajar</button></div></article><article><Icon name="download"/><span>RESPALDO</span><h3>Portable</h3><p>Exporta tu progreso y notas a JSON o impórtalos en otro dispositivo.</p><div><button onClick={exportJson}>Exportar</button><label>Importar<input type="file" accept="application/json" onChange={e=>importJson(e.target.files?.[0])}/></label></div></article><article><Icon name="monitor"/><span>PWA</span><h3>Instalable</h3><p>Manifest, service worker y shell offline preparados para escritorio y móvil.</p><button onClick={install} disabled={!installEvent}>{installEvent?"Instalar aplicación":"Instalación disponible desde el navegador"}</button></article></div>
  </section>;
}
