import { ExternalLink, FlaskConical, Layers3, Sparkles } from "lucide-react"
import { allSourcesV44, enginesV44, frontierV44, lawsV44, minimumCanonV44 } from "./curriculum-v44"
import { navigateTo } from "../v41/v41-router"

export function CanonV44(){return <div className="v44-canon"><div className="v44-section-head"><div><span>NÚCLEO MÍNIMO SIN PERDER COBERTURA</span><h3>Pocas fuentes maestras; muchas evidencias.</h3></div><p>El núcleo combina estándares, universidad en español, currículos abiertos y laboratorios. Las fuentes comunitarias sirven de contraste y práctica, no como autoridad única.</p></div><div className="v44-canon-core">{minimumCanonV44.map((s,i)=><a key={`${s.name}-${i}`} href={s.url} target="_blank" rel="noreferrer"><small>NIVEL {s.tier} · {s.language}</small><strong>{s.name}</strong><p>{s.role}</p><span>Abrir <ExternalLink/></span></a>)}</div><details className="v44-all-sources"><summary>Ver canon ampliado ({allSourcesV44.length} fuentes)</summary><div>{allSourcesV44.map((s,i)=><a key={`${s.name}-${i}`} href={s.url} target="_blank" rel="noreferrer"><b>{s.name}</b><small>{s.kind} · {s.language} · nivel {s.tier}</small></a>)}</div></details></div>}

export function EnginesV44(){return <div className="v44-engines"><div className="v44-section-head"><div><span>MULTI-MOTOR LEARNING OS</span><h3>Un motor distinto para cada problema.</h3></div><p>No existe un único proyecto “mejor” para todo. La arquitectura combina motores especializados y evita herramientas con licencias incompatibles con la exigencia de gratuidad.</p></div><div className="v44-engine-grid">{enginesV44.map(e=><a key={e.name} href={e.url} target="_blank" rel="noreferrer"><div><Layers3/><span>{e.status}</span></div><h4>{e.name}</h4><b>{e.role}</b><p>{e.why}</p><small>{e.license}</small></a>)}</div><div className="v44-lab-bridge"><FlaskConical/><div><small>PUENTE DE LABORATORIOS</small><h4>La Ruta decide qué dominar; Programación ejecuta la práctica.</h4><p>Desde las aulas de Ruta se mantiene la evidencia académica. Los motores browser JupyterLite/Pyodide y Sandpack quedan declarados como la base técnica para profundizar laboratorios sin backend de pago.</p></div><button onClick={()=>{navigateTo("programacion")}}>Abrir Programación</button></div></div>}

export function FrontierV44(){return <div className="v44-frontier"><div className="v44-section-head"><div><span>FRONTERA CON NIVEL DE MADUREZ</span><h3>Aprender futuro sin convertir hype en verdad.</h3></div><p>Las áreas futuras del inventario se enseñan con una etiqueta de madurez y una regla de evidencia.</p></div><div className="v44-frontier-grid">{frontierV44.map(x=><article key={x.title} className={`maturity-${x.maturity.toLowerCase()}`}><small>{x.maturity}</small><h4>{x.title}</h4><div>{x.domains.map(d=><span key={d}>{d}</span>)}</div><p>{x.rule}</p></article>)}</div><div className="v44-laws"><Sparkles/><div><small>LEYES DEL CAMPUS</small>{lawsV44.map(x=><p key={x}>{x}</p>)}</div></div></div>}
